### ISSUE TITLE
Organisation in Mozambique

### ISSUE THREAD

**Issue by PetyaKangalova** [org-id/register#129]
## Request 

**What type of organization do you want identifiers for?** State owned company

**In which countries are the organizations you want identifiers for based?**:  Mozambique

**Do you have examples of organizations you need identifiers for?**

This request relates to issue #43 . We received another request from an organisation ([FIPAG](http://www.fipag.co.mz/index.php/pt/)) in Mozambique that would like to start publishing to IATI. 

> FIPAG is a state owned water drinking company, responsible for asset management and some water operational activities. FIPAG only has a decree and a tax number, but not a registration number.

From the previous research you have done #43 it seems that there is no stable identifier that can be used. I have checked and they are **not** registered with the Mozambique Ministry of Justice (MZ-MOJ). Could you advise whether further research has been done and there is any other alternative code that can be used, or  otherwise I would need to put a proposal for an XI-IATI code asap.

Thanks!

**Comment by BobHarper1** [comment]
Hi @PetyaKangalova 
I don't think FIPAG would be likely to be found on MZ-MOJ as this seems to be for civil society organisations only.

I've had a look back at #43 and I think I've located the area of the website that the dead url used to point to. http://www.portaldogoverno.gov.mz/por/Empresas/Registos which shows the existance of a Commercial Registry.

I think it's possible that FIPAG could be on the Mozambique Commercial Registry. I'm not sure if there is a Company Registration Number as well as the Unique Tax Identifying Number (NUIT) for Mozambique registered businesses, could you ask of FIPAG if they have either of those?

I have however updated the list [MZ-CR](https://github.com/org-id/register/blob/master/lists/mz/mz-cr.json) with some information. There is no online accessible list for this however, so I'm unable to confirm if FIPAG are on it. 

If FIPAG are able to respond with either a Company Registration Number of a Tax Number, I can update the list accordingly.

**Comment by timgdavies** [comment]
A pull request for NUIT is open here: #135 

This will be added in 7 days unless objections are raised.

**Comment by BobHarper1** [comment]
This has been added and resolved (via emails) that FIPAG can use an MZ-NUIT code as an identifier.
