### ISSUE TITLE
RESEARCH: Update on lists for Sweden

### ISSUE THREAD

**Issue by timgdavies** [org-id/register#144]
We currently have two entries for Sweden:

* [SE-BLV](http://org-id.guide/list/SE-BLV)
* [SE-KK](http://org-id.guide/list/SE-KK)

but it appears that both use the same underlying identifier scheme, the [Organisationsnummer](https://sv.wikipedia.org/wiki/Organisationsnummer).

In line with the idea that org-id.guide is a list of lists (or, a list of identifier schemes), we should:

* Deprecate SE-BLV and SE-KK (as these only refer to registration agencies)
* Create a new entry for the Organisationsnummer which [covers all the kinds of entities listed here](https://www.skatteverket.se/foretagochorganisationer/foretagare/startaochregistrera/organisationsnummer.4.361dc8c15312eff6fd235d1.html)

However, to complete this we need to:

* Identify any search services that should be linked to for looking up an Organisationsnummer
* Identify an appropriate prefix for Organisationsnummer (SE-ON?)
* Check the implications of deprecating SE-BLV / SE-KK on existing data, as these have existed for IATI for a while.

**Comment by sven-norlin** [comment]
Re search services; Swedish tax Agency service will give exact result 
https://skatteverket.se/hamtaforetagsinformation

These are the most common search services in sweden
Eniro.se and Hitta.se will give sometimes exact result and sometimes results in the right deriction

**Comment by BobHarper1** [comment]
@sven-norlin Thanks Sven. The Skatteverket service I think it will retrieve company information if the organisationsnummer is known in advance. So I will include the https://snr4.bolagsverket.se/snrgate/startIn.do service as well as the use case for org-id.guide is often that users want to find a number for an organisation that they don't know already.

I have created a pull request for this entry SE-ON. You can find the information and how to preview it here https://github.com/org-id/register/pull/156

Thanks for your help with this addition.

**Comment by sven-norlin** [comment]
For your information, you will get no hits in https://snr4.bolagsverket.se/snrgate/startIn.do if your search the organisation Sida is working with. Niether on name or on organisation number will give any hits. That search service only register comercial companies and non of the framework organisations in Sida db is a Commercial Company.

**Comment by sven-norlin** [comment]
If you want to search on name you can use one of the following
https://eniro.se
https://hitta.se
https://www.merinfo.se
https://www.ratsit.se
https://www.allabolag.se

**Comment by BobHarper1** [comment]
@sven-norlin thank you for the information. Do any of the search services you have listed cover organisations that Sida work with? I think that https://www.allabolag.se does include non-profit organisations and therefore may be preferable to Bolagsverket as a search resolution?

We can include other methods to find out an organisation number from an organisations name, it does not have to be just online search services, so we can include contact details of registration agencies such as Tax Agency.

**Comment by sven-norlin** [comment]
Sven Norlin Today at 13:53 
Hi Bob

Is this settled now that the RegistryAgency for Sweden will be SE-ON ? I noticed that it is not yet changed in http://iatistandard.org/202/codelists/OrganisationRegistrationAgency/ 

BR 
/Sven Norlin

**Comment by sven-norlin** [comment]
Question: "Do any of the search services you have listed cover organisations that Sida work with? I think that https://www.allabolag.se does include non-profit organisations and therefore may be preferable to Bolagsverket as a search resolution?"

Answer: All these include non-profite organisations in search 
https://eniro.se
https://hitta.se
https://www.merinfo.se
https://www.ratsit.se
https://www.allabolag.se

It is just this one that only include companies: 
https://snr4.bolagsverket.se/snrgate/startIn.do

**Comment by BobHarper1** [comment]
This has been resolved (also through emails) and the list SE-ON is now live. Thanks for the help, Sven.
