### ISSUE TITLE
REQUEST: [Registrar of Welfare Organizations - Zimbabwe]

### ISSUE THREAD

**Issue by amy-silcock** [org-id/register#151]
Request for the Registrar of Welfare Organizations in Zimbabwe to be added.

Private Voluntary Organizations need to register with above registrar. They are then given a PVO number e.g.

![image](https://user-images.githubusercontent.com/27764077/33177064-37d8bd24-d059-11e7-94aa-b049632e3ab3.png)

**Comment by amy-silcock** [comment]
Hi, the organisation who wishes to use this code were meant to publish their IATI data yesterday. Any chance this one could be looked at quickly?

Best wishes,

Amy

**Comment by amy-silcock** [comment]
I've seen that the previous IATI codelist has this listed as ZW-PVO Private Voluntary Organisations Council:

http://iatistandard.org/202/codelists/OrganisationRegistrationAgency/

Please can this be added to Org-ID

**Comment by timgdavies** [comment]
I see https://github.com/org-id/register/blob/master/lists/zw/zw-pvo.json in our staged copy - but not sure why this wasn't brought into the org-id.guide list. 

I will update this now and incorporate through the fast-track.

**Comment by timgdavies** [comment]
This list is live now: http://org-id.guide/list/ZW-PVO

**Comment by amy-silcock** [comment]
Thanks Tim!
