### ISSUE TITLE
Suggest correction: Edubase archived - new link needed

### ISSUE THREAD

**Issue by KDuerden** [org-id/register#157]
## Correction

http://org-id.guide/list/GB-EDU link goes to archived link: http://aka.education.gov.uk/edubase/home.xhtml
New service is available: https://get-information-schools.service.gov.uk/
This seems to serve up - EDU & UKPRN results: https://get-information-schools.service.gov.uk/Establishments/Establishment/Details/112085?searchQueryString=SelectedTab%3DEstablishments%26SearchType%3DText%26TextSearchModel.Text%3DDoubletrees%2BSchool%26TextSearchModel.AutoSuggestValue%3D%26f%3Dtrue%26OpenOnly%3Dfalse

**Comment by BobHarper1** [comment]
It seems this is part of the register's takeover by the GDS.

It doesn't seem to be called Edubase anymore so have changed the title.

I've also linked to the registers.gov.uk full datasets that can be downloaded in bulk.

Misleadingly, it does seem to contain schools in Wales (not sure it it's all of them, but the Welsh register proper is in the backlog).

@KDuerden  can you have a quick look at the PR and I will merge?

**Comment by BobHarper1** [comment]
^^ Preview the platform with this list at http://org-id.guide/_preview_branch/GB-EDU (visiting http://org-id.guide/list/GB-EDU when the preview is active or check the files changed options above.

**Comment by KDuerden** [comment]
Language about country coverage needs tightening up - as not UK-wide.

All educational establishments in England must be registered with the Department of Education. Edubase is provided by the Department of Education and provides a URN for each school, university and other educational establishment in England and Wales.

The searchable database returns 30,000 results, and the Alpha English Schools list has 42,357 entries so I think the comment on EduBase CSV may need updating or extra context.

**Comment by BobHarper1** [comment]
I've updated the description as per the above. I'll send an email to the registers team to get some clarity on why there is a discrepancy in the number of records between the searchable database and the nominally-complete register.

**Comment by BobHarper1** [comment]
^^ Re the above, you get 30,000 if you have the defauly 'open' school only option selected. Untick that and you get 49,395 records. https://get-information-schools.service.gov.uk/Establishments/Search?SelectedTab=Establishments&SearchType=EstablishmentAll&TextSearchModel.AutoSuggestValue=&f=true&OpenOnly=false

So I think safe to say this covers  the full Alpha Register for England, and probably some of the Welsh one which is in progress.

**Comment by BobHarper1** [comment]
I think this is resolved
