### ISSUE TITLE
REQUEST: [DMCC in UAE]

### ISSUE THREAD

**Issue by amy-silcock** [org-id/register#164]
## Request

**What type of organization do you want identifiers for?**
Private sector organisations

**In which countries are the organizations you want identifiers for based?**: 
United Arab Emirates
DMCC: https://www.dmcc.ae/

**Do you have examples of organizations you need identifiers for?**
GeoPoliticity
DMCC License Number: JLT-65609
Suggested IATI Org ID: EA-DMCC-JLT-65609

**Comment by BobHarper1** [comment]
#### Notes

In trying to understand what DMCC is and how that is different from [AE-DICC](http://org-id.guide/list/AE-DCCI) it's quite difficult to track down explanatory information. The Dubai Multi Commodities Centre DMCC is a Free Trade Zone within Dubai. It also does seem to be a registering agency, though the '[Business Directory](https://www.dmcc.ae/business-search)' on their website is more about where to find offices in the Zone than registrations. But the DMCC itself does register and license corporations to operate there.

A company could be established within only the DMCC and therefore not be on the DICC list or any other list "[A UAE partner is not required when setting up a DMCC company](A UAE partner is not required when setting up a DMCC company)". Therefore, I think this is a valid proposal.

**Comment by BobHarper1** [comment]
We have other Free Zone authorities in org-id http://org-id.guide/list/AE-HFZA

**Comment by BobHarper1** [comment]
This will be merged, note the change from the originally proposed list code of AE-DU-DMCC to AE-DMCC
