### ISSUE TITLE
REQUEST: Jordan, Ministry of Social Development

### ISSUE THREAD

**Issue by PetyaKangalova** [org-id/register#165]
## Request

**What type of organization do you want identifiers for?** [Non-profit Organization]

**In which countries are the organizations you want identifiers for based?**:  Jordan, Ministry of Social Development (MoSD)

**Do you have examples of organizations you need identifiers for?**  [Queen Rania Foundation for Education & Development ](http://www.qrf.org/)

We have had a request from the Queen Rania Foundation for Education & Development who want to register to IATI. If you need further information I can get back to them and ask.  Thanks!

**Comment by BobHarper1** [comment]
@PetyaKangalova We have a list currently JO-CCD which covers entities in Jordan registered with the Companies Control Department. This includes not-for-profits.

The search interface is only in Arabic, and difficult for non-speakers to navigate, but I have found and entry for the 'Jordanian Foundation for Education and Development' with National establishment number **200105534**. You can get the company registration document through entering the number in the 'Query by national number of origin' option on http://www.ccd.gov.jo/ar/home/e-services/companies-query

Though a different company name, the registration document has text which translates as '_Note that the company was registered under the name of Queen Rania Al-Abdullah Foundation for Education_' so I think this is the correct result. Are you able to get the Foundation to confirm?

The code to use would therefore be JO-CCD-200105534

If this is not suitable I can investigate the Ministry of Social Development list (some info here but apparently no publicly-accessible list http://www.icnl.org/research/monitor/jordan.html)

**Comment by PetyaKangalova** [comment]
@BobHarper1 Thanks for the quick response. I will check with the Foundation and let you know.

**Comment by PetyaKangalova** [comment]
@BobHarper1 This is the response I received:

>  In regards to the company number that you provided, I checked with our finance department as they are the ones that handle such matters and I was informed that this is an old company that was liquidated years ago and no longer exists, which is listed on the CCD website when checking for the company’s national number. We are currently registered under the MoSD charity register which is dedicated for non-profits and is different from the CCD register. 

Would it be possible to continue looking into MoSD? They need to publish by the end of the month. I will copy you in my response to them in case you need additional information.

Many thanks.

**Comment by BobHarper1** [comment]
Thanks @PetyaKangalova, I think it will be possible to add, though there doesn't appear to be any publicly-accessible register, so the publisher will have to know and provide the number.
