### ISSUE TITLE
REQUEST: Registrar of Companies in Mauritius [MU-CR)

### ISSUE THREAD

**Issue by amy-silcock** [org-id/register#174]
## Request

**What type of organization do you want identifiers for?** Private Sector

**In which countries are the organizations you want identifiers for based?**: Mauritius 

**Do you have examples of organizations you need identifiers for?** Pegasys AME (copy of registration certificate sent to you via e-mail)

Registration Certificate shows that they have been registered by the 'Registrar of Companies' in Mauritius. This is part of the process of setting up an organisation: https://www.mcb.mu/en/media/Business%20Registration%20Guideline%202_tcm9-6130.pdf

**Comment by BobHarper1** [comment]
I think this could be progressed through changes to [MU-CR](https://github.com/org-id/register/blob/master/lists/mu/mu-cr.json) (which isn't listed on org-id.guide as "confirmed"is not set to true)

**Comment by BobHarper1** [comment]
There's a difficulty of whether to use the Company Number or Business Registration Number, e.g. both are on https://portalmns.mu/cbris-name-search/MASTActionServlet?do=FormEdit&id=ViewFormCBRIS.xml&key_1=C136127&key_count=1 but differ.

I've opted for Company/Registration number as not all companies have a business registration number, e.g. https://portalmns.mu/cbris-name-search/MASTActionServlet?do=FormEdit&id=ViewFormCBRIS.xml&key_1=C071748&key_count=1

However, non-companies (e.g. foundations) have only a business registration number, so this would be used instead.
