### ISSUE TITLE
PROPOSAL: Registro Único de Contribuyentes de Paraguay

### ISSUE THREAD

**Issue by juanpane** [org-id/register#180]
## Proposal

**The name of the list (or the organization that manages the list)**
_Registro Único de Contribuyentes del Paraguay_ 
Managed by the "_Sub-secretaría de Estado de Tributación (SET)_" of the "_Ministerio de Hacienda_" of Paraguay. 

**A suggested code for the list (optional)**
PY-RUC

**A short description of the list**
The RUC (_Registro Único del Contribuyente_) is the unique taxpayer registry that maintains the personal non-transferable identification number for all those physical persons (national or foreign) and legal entities (for profit and non for profit) that carry out economic activities in the Paraguayan territory. The identification number is created primarily for tax purposes.

**The country or countries that the list covers**
Paraguay

**The legal form or organizations that the list covers**
Legal entities and physical persons

**Any specific sectors that the list covers**
All sectors

**A URL for information on the list, and a URL for looking up identifiers (if available)**
For tutorial on the RUC:
http://www.set.gov.py/portal/PARAGUAY-SET/Tutoriales/ruc/ruc2

For downloading the complete list:
http://www.set.gov.py/portal/PARAGUAY-SET/InformesPeriodicos?folder-id=repository:collaboration:/sites/PARAGUAY-SET/categories/SET/Informes%20Periodicos/listado-de-ruc-con-sus-equivalencias

**Any information on available open data copies of this list**
The official complete list is maintained by the “_Sub-secretaría de Estado de Tributación_” of the “_Ministerio de Hacienda_” of Paraguay (http://www.set.gov.py) and can be downloaded from 
http://www.set.gov.py/portal/PARAGUAY-SET/InformesPeriodicos?folder-id=repository:collaboration:/sites/PARAGUAY-SET/categories/SET/Informes%20Periodicos/listado-de-ruc-con-sus-equivalencias

**One or more examples of identifier from this list, and how you found them**

**RUC**: description
**80013889-9**: DATA SYSTEMS SA EMISORA DE CAPITAL ABIERTO
**80007525-0**: MASTER SOFT SRL

Example RUC extracted from the record package of the example documentation of the Open Contracting Data Standard API implementation of the National Procurement Agency in Paraguay (Dirección Nacional de Contrataciones Públicas) 
https://www.contrataciones.gov.py/datos/api/v2/#!/ocds/getRecordPackage_get_5
https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/record-package/193399

**Comment by BobHarper1** [comment]
This has been added as a proposed list (to be formally added after 7 days). 

I also checked if public agencies were on the list and it appears they are e.g. Ministerio de Educacion 80005190-4, so the list data reflects this.

Many thanks @juanpane for including such complete and helpful information.
