### ISSUE TITLE
PROPOSAL: Clasificación por Entidades del Presupuesto General de la Nación del Paraguay

### ISSUE THREAD

**Issue by juanpane** [org-id/register#181]
## Proposal: 

**The name of the list (or the organization that manages the list)**
Clasificación por Entidades del Presupuesto General de la Nación del Paraguay
Classification by Entities of the National Budget for Paraguay

**A suggested code for the list (optional)**
PY-PGN

**A short description of the list**

From the National Budget Law (Presupuesto General de la Nación (PGN)) of 2016 from Paraguay (http://bit.ly/PGNPY2016)
“The objective of the classification by entities is to organize information related income, spending and budgetary credits from the different state organisms and entities at various institutional levels according to their functions, nature, characteristics and dependencies.”

**The country or countries that the list covers**
Paraguay

**The legal form or organizations that the list covers**
Organizations and institutions from the Paraguayan State

**Any specific sectors that the list covers**
National Public bodies, administrative departments, municipalities of Paraguay

**A URL for information on the list, and a URL for looking up identifiers (if available)**

The list is yearly updated given each the yearly national budget law. The 2016 budget law 2016 is available at http://bit.ly/PGNPY2016.
The list of all entities from 2011 to 2016 is available in open data format at: https://datos.hacienda.gov.py/data/entidad   
Data dictionary: https://datos.hacienda.gov.py/def/entidad 

**Any information on available open data copies of this list**
The list of all entities from 2011 to 2016 is available in open data format at: https://datos.hacienda.gov.py/data/entidad   

**One or more examples of identifier from this list, and how you found them**

ID - description
12 - Poder Ejecutivo
12.001 - Presidencia de la República
12.002 - Vicepresidencia de la República
12-006 - Ministerio de Hacienda

The sample data was obtained from the dataset of public entities at the open data portal from the Ministerio de Hacienda of Paraguay (https://datos.hacienda.gov.py/data/entidad)

**Comment by BobHarper1** [comment]
I'm not entirely convinced that budget items are the same as a register of organisation, or that we need a separate listing for these agencies as they are already covered in another (primary) list.

I found, in creating the new list PY-RUC that government agencies have similar identifiers alongside companies and natural person. The examples e.g. Poder Ejecutivo & Ministerio de Hacienda can be found on http://www.ruc.com.py/ with the same identifiers in https://datos.hacienda.gov.py/data/entidad

Tagging @timgdavies as I'm aware of a previous discussion around this.

**Comment by timgdavies** [comment]
@BobHarper1 Our approach here would be to recognise that PY-PGN *does* contain a list of organisations, so we could include it, but we would want to check that PY-RUC comes higher up the recommended list, so should be used in preference to PY-PGN whenever an identifier is available there.

**Comment by BobHarper1** [comment]
@timgdavies Agreed, and I will add to PY-PGN description that PY-RUC is prefered.
