### ISSUE TITLE
REQUEST: NHS organisations in the United Kingdom [GB-NHS]

### ISSUE THREAD

**Issue by drkane** [org-id/register#184]
## Request

**What type of organization do you want identifiers for?** 
NHS Foundation Trusts (part of government, ish)

**In which countries are the organizations you want identifiers for based?**: 
United Kingdom - England

**Do you have examples of organizations you need identifiers for?**
Central and North-West London NHS Foundation Trust

_Initial research_

There's no register of NHS providers, although there is an [not yet released list of Clinical Commissioning groups on gov.uk registers](https://clinical-commissioning-group.cloudapps.digital/).

NHS Improvement, which regulates NHS Foundation Trusts and some other providers, has a list of "[Registered Healthcare Providers](https://improvement.nhs.uk/resources/nhs-foundation-trust-directory-and-register-licensed-healthcare-providers/)" - I'm not sure what the definition of that is but it seems to be a licensing arrangement. It has a license number for each organisation (eg for the example above their number is 100022). I would perhaps suggest a prefix of "**GB-NHSP-**" (for NHS providers).

I'm not an expert on this area though - it might be good to find an identifier that covers all NHS organisations - foundation trusts, mental health trusts, gp surgeries, etc - similar to UKPRN for education. Not sure if such a thing exists though. There's also sub-national considerations - NHS is devolved so I don't know how it works in Scotland, NI & Wales. (the register above covers only England)

**Comment by drkane** [comment]
Here's GP practices - might need a separate issue: https://digital.nhs.uk/organisation-data-service/data-downloads/gp-data

**Comment by drkane** [comment]
Hang on, that site has a whole organisation data service which might be the place to go for all these codes: https://digital.nhs.uk/organisation-data-service/ - there are lots of separate files with different organisation types, plus [a link to this service](https://isd.digital.nhs.uk/trud3/user/guest/group/0/pack/5) which seems to have a full bulk download.

These records seem to have unique IDs - the one for my example above is `RV3`.

I'd probably suggest using these IDs with a `GB-NHS-` prefix.

**Comment by BobHarper1** [comment]
I'm fairly confident there are no repeats of organisation codes across the separate data files. So I agree with @drkane, making one list `GB-NHS` (that will cover all UK subnational regions) and many types of NHS organisations, even individual GPs are covered. The files are fairly standard in that the organisation code seems to always be in the first column (there is no header row, but a description document which will confirm titles).

This is good!

**Comment by BobHarper1** [comment]
I've added the list to the live site, see http://org-id.guide/list/GB-NHS

**Comment by drkane** [comment]
Awesome - thanks @BobHarper1. 

I think there's a small bug on the page - the examples are showing as `GB-NHS-GB-NHS-01F` - ie with the prefix repeated.

**Comment by BobHarper1** [comment]
Whoopsie, thank you @drkane
