### ISSUE TITLE
Ecuador Company Register

### ISSUE THREAD

**Issue by BobHarper1** [org-id/register#196]
## Proposal

**The name of the list (or the organization that manages the list)** 
Ecuardo Registro Ofical

**A suggested code for the list (optional)** 
EC-CR which [already exists as an unconfirmed list](https://github.com/org-id/register/blob/master/lists/ec/ec-cr.json)

**A short description of the list**

**The country or countries that the list covers**
Ecuador

**The legal form or organizations that the list covers**
Company

**Any specific sectors that the list covers**

**A URL for information on the list, and a URL for looking up identifiers (if available)** http://appscvsmovil.supercias.gob.ec/portaldeinformacion/consulta_cia_param.zul
http://www.supercias.gob.ec/portalinformacion/portal/

**Any information on available open data copies of this list**

**One or more examples of identifier from this list, and how you found them**
Under the 'RUC' column. 

1091700308001
1790863840001
0990559813001

**Comment by timgdavies** [comment]
This is now included.
