### ISSUE TITLE
PROPOSAL: Tanzanian Revenue Authority TZ-TRA

### ISSUE THREAD

**Issue by amy-silcock** [org-id/register#198]
## Proposal

**The name of the list, or the organization that manages the list**

Tanzanian Revenue Authority

**A suggested code for the list [optional]**

TZ-TRA

**A short description of the list**

The Tanzanian Revenue Authority provides Taxpayer Identification Numbers (TIN) for organisations registered in Tanzania. This is issued under section 3A(4) of the Income Tax Act no. 33 of 1973. As amended by the financial laws (miscellaneous amendments) 2000.

**The country or countries that the list covers**

Tanzania

**A URL for information on the list, and a URL for looking up identifiers [if available]**

https://www.tra.go.tz/index.php

**One or more examples of identifier from this list, and how you found them**

As seen on a certificate: 101-091-759

**Comment by BobHarper1** [comment]
I've staged TZ-TRA for merging after 7 days.

The BRELA (list [TZ-BRLA](http://org-id.guide/list/TZ-BRLA)) can provide an alternative in place of no searchable list for TINs. This is noted in the guidance for TZ-TRA

It's possible that the TIN is used in the Tanzanian [BRELA Online System](https://ors.brela.go.tz/orsreg/searchbusinesspublic) company element as the "Incorporation/Compliance number", but it's not possible to confirm that this is the case. 

Not all companies have been transferred to this BRELA system so I can't be sure if the example provided isn't in the system, or isn't the same as the number used in BRELA.

**Comment by timgdavies** [comment]
Interestingly, the registration form at https://gateway.tra.go.tz/OnlineTin/EntityRegistration, if a TIN is entered (without dashes) into §9 returns the name of the organisation - suggesting a hidden API somewhere with TINs and organisation names in.

**Comment by duncandewhurst** [comment]
Can this be closed now?
