### ISSUE TITLE
PROPOSAL: Superintendencia Nacional de los Registros Públicos (Peru): PE-SUNARP

### ISSUE THREAD

**Issue by amy-silcock** [org-id/register#202]
## Proposal

**The name of the list, or the organization that manages the list**
Superintendencia Nacional de los Registros Públicos

**A suggested code for the list [optional]**
PE-SUNARP

**A short description of the list**
The SUNARP is an autonomous decentralized body of the Justice Sector in Peru and the governing body of the National System of Public Registries, and has among its main functions and powers to dictate the policies and technical standards - registry of public records that make up the National System, plan and organize, regulate, direct, coordinate and supervise the registration and publicity of acts and contracts in the Registries that make up the System. 

**The country or countries that the list covers**
Peru

**A URL for information on the list, and a URL for looking up identifiers [if available]**
Website URL https://www.sunarp.gob.pe/index.asp

**One or more examples of identifier from this list, and how you found them**
12623829, as detailed in a registration document

**Comment by timgdavies** [comment]
I've now staged PE-SUNARP for inclusion via #203. Unless objections are raised, this will be merged in around 7 days time.
