### ISSUE TITLE
CORRECTION: FR-INSEE is not deprecated

### ISSUE THREAD

**Issue by ColinMaudry** [org-id/register#204]
## Correction

List: FR-INSEE

Corretion: I don't understand why this list is described as "deprecated", since it's the pillar of identification for State bodies, companies and associations.

This registry is actually open: https://www.data.gouv.fr/fr/datasets/base-sirene-des-entreprises-et-de-leurs-etablissements-siren-siret/

**Comment by timgdavies** [comment]
My understanding is that all numbers that would be under [FR-INSEE](http://org-id.guide/list/FR-INSEE] can also be found in the list [FR-RCS](http://org-id.guide/list/FR-RCS) list. 

We try to avoid instances where someone might publish the same ID with two different prefixes, so in cases like this the narrower list is deprecated in favour of the broader one.

We need to improve the interface and explanation in cases like this.

If we've not understood right the containment of INSEE numbers in RCS let me know and I'll look into revisions of this.
