### ISSUE TITLE
PROPOSAL: Republic of Somaliland, Ministry of Planning and National Development SO-MPND

### ISSUE THREAD

**Issue by amy-silcock** [org-id/register#205]
## Proposal

**The name of the list, or the organization that manages the list**

Republic of Somaliland
Ministry of Planning and National Development 

**A suggested code for the list [optional]**

SO-MPND

**The country or countries that the list covers**

Somaliland

**Any specific sectors that the list covers**

NGOs

**A URL for information on the list, and a URL for looking up identifiers [if available]**

http://slministryofplanning.org/

**One or more examples of identifier from this list, and how you found them**

**L.43.** 31.2072 **.2018M/J** (Registration lasts one year - found on a registration certificate)

**Comment by timgdavies** [comment]
We have staged an entry at https://github.com/org-id/register/pull/212

**Comment by timgdavies** [comment]
This is now merged.
