### ISSUE TITLE
PROPOSAL: Puntland State of Somalia, Ministry of Planning and International Cooperation SO-MOPIC

### ISSUE THREAD

**Issue by amy-silcock** [org-id/register#206]
## Proposal

**The name of the list, or the organization that manages the list**

Puntland State of Somalia
Ministry of Planning and International Cooperation

**A suggested code for the list [optional]**

SO-MOPIC

**The country or countries that the list covers**

Somalia - Puntland Regions

**Any specific sectors that the list covers**

International NGOs

**A URL for information on the list, and a URL for looking up identifiers [if available]**

https://mopicplgov.net/

**One or more examples of identifier from this list, and how you found them**

Ref: MOPIC/0118/2017 (Registration lasts one year - found on a registration certificate)

**Comment by amy-silcock** [comment]
Guidance from a NGO is that their registration number changes each year when they re-register. They have not been able to locate a stable identifier.

**Comment by timgdavies** [comment]
As with #207, it appears we have to use fallback lists in this instance.
