### ISSUE TITLE
PROPOSAL: South Korean Ministry of Foreign Affairs KR-MFA

### ISSUE THREAD

**Issue by amy-silcock** [org-id/register#208]
## Proposal

**The name of the list, or the organization that manages the list**

South Korean Ministry of Foreign Affairs

**A suggested code for the list [optional]**

KR-MFA

**The country or countries that the list covers**

South Korea

**One or more examples of identifier from this list, and how you found them**

Business Registration number: 402-82-24197 (examples from certificate of business registration)

**Comment by timgdavies** [comment]
I'm looking into this. The registration certificate shared appears to show two numbers, and comes from the tax authority - so I'm not sure KR-MFA would be the appropriate code. Will update more next week.

**Comment by duncandewhurst** [comment]
This number looks like the Business Registration Number issued by the National Tax Service, described [here](https://www.oecd.org/tax/automatic-exchange/crs-implementation-and-assistance/tax-identification-numbers/Korea-TIN.pdf).

The middle two digits in the example above designates it as a "head or branch office of a non-profit corporation"

According to the NTS website there should be a couple of other numbers on there, the certificate issuance number and the resident registration number of the person who registered the business.

Where can I find the example certification that was shared?

**Comment by duncandewhurst** [comment]
Proposing KR-BRN as a more appropriate code, see draft on [this branch](https://github.com/org-id/register/tree/KR-BRN)

**Comment by duncandewhurst** [comment]
This list is now [live](http://org-id.guide/list/KR-BRN)
