### ISSUE TITLE
CORRECTION: Ghana Department of Social Welfare

### ISSUE THREAD

**Issue by PetyaKangalova** [org-id/register#210]
## Correction

We have received three new IATI Registry account requests for organisations in Ghana.

Currently on org-id.guide, we have: http://org-id.guide/list/GH-DSW

1. It seems that the Department of Social Welfare has changed name and is now called Department of Social Development- see post in [here](http://mogcsp.gov.gh/department-of-social-developments/). I just wanted to check whether GH-DSW is still the correct list or it needs to change so that we know what to advise the new organisations. Please let me know.

2. If you press 'Visit the Website' it goes back to org-id. Is there an external website that it should be linked to?
![image](https://user-images.githubusercontent.com/24607542/38684112-dedd118a-3e66-11e8-9496-45a7cf7fdb2d.png)

Thanks,
Petya

**Comment by timgdavies** [comment]
Thanks for highlighting this. I've updated the title (but not the list code, as we aim to keep these stable) and I've added a link to the page given - as this appears to be the only available web page.
