### ISSUE TITLE
REQUEST: RW-RGB Rwanda Governance Board

### ISSUE THREAD

**Issue by jahnvidave** [org-id/register#213]
## Request

**What type of organization do you want identifiers for?** NGO or Charity 

**In which countries are the organizations you want identifiers for based?**: Rwanda

**Do you have examples of organizations you need identifiers for?** Registration Number: 101/2014 Registration Agency: Rwanda Governance Board

**Comment by duncandewhurst** [comment]
I've staged [RW-RGB](https://github.com/org-id/register/tree/RW-RGB) for review.

Based on the notices published in the official gazette the identifier format is:

XX/RGB/[NGO|RBO]/YYYY

So since the above identifier is for an NGO it would be:

101/RGB/NGO/2014

**Comment by timgdavies** [comment]
This is now staged for inclusion at https://github.com/org-id/register/pull/214 and should be live in the next 7 days.

**Comment by timgdavies** [comment]
This is now live.
