### ISSUE TITLE
Proposal: Tanzania NGO Registration Agency

### ISSUE THREAD

**Issue by jahnvidave** [org-id/register#220]
## Proposal

**The name of the list (or the organization that manages the list)**
We do not know the name of the agency, but we know that organisations are registered under the Non-Governmental Organizations Act 2002 (Tanzania)

**The country or countries that the list covers**
Tanzania

**The legal form or organizations that the list covers**
NGOs

**One or more examples of identifier from this list, and how you found them**
Registration Number: 08295

**Comment by timgdavies** [comment]
@jahnvidave We've staged a list for the Tanzania National NGO Co-ordination Board, but I notice that:

(a) The organisation behind this request does not appear on the list at http://www.tnnc.go.tz/ngoresults.php under the name I've seen for them;

(b) The registration number  08295 follows a different pattern to the Identifiers we've found (e.g. 00NGO/1787) 

Can you confirm with that organisation whether they are on the list, or if there is some other list their registration may have been taken from?

**Comment by duncandewhurst** [comment]
On the registration certificate for the agency the Registration No. field is populated with: 00NGO/08295

Looking at a few more example certificates I found via a [Google image search](https://www.google.co.nz/search?q=tanzania+ngo+registration+certificate&hl=en&source=lnms&tbm=isch), there doesn't seem to be a consistent number of digits after the "/" and in one case the "/" was omitted:

00NGO/00006744
00NGO/00007227
00NGO/0008891
00NGO00002182
00NGO/0009119

So I think is organisation is likely to belong to this list, but the list on the website appears to be out of date or incomplete.

I've updated the proposed list accordingly - I think this should be OK to merge after 7 days
