### ISSUE TITLE
REQUEST: Multilateral Investment Fund (MIF)

### ISSUE THREAD

**Issue by PetyaKangalova** [org-id/register#222]
## Request

**What type of organization do you want identifiers for?** [Multilateral Investment Fund (MIF)](http://www.fomin.org/en-us/Home/about.aspx) . MIF is an independent fund administered by the Inter-American Development Bank (IDB) and would be publishing separately to IATI so required an unique IATI organisation identifier.

**In which countries are the organizations you want identifiers for based?**: Multilateral

**Do you have examples of organizations you need identifiers for?** I have referred them to the OECD DAC list but the identifiers provided there do not correctly reflect the structure of IADB and MIF, so they would not be able to use  XM-DAC.  

I believe we will have to make a proposal for an XI-IATI code as for the Inter-American Development Bank but wanted to check if there is any other options first.

**Comment by duncandewhurst** [comment]
Hi Petya, it looks like an XI-IATI code is required in this case.

**Comment by andylolz** [comment]
> it looks like an XI-IATI code is required in this case.

@duncandewhurst with the latest DAC update, it looks as though MIF could now be referenced using the following identifier: `XM-DAC-909-5`.

Are you able to confirm that’s the case? Thanks

**Comment by timgdavies** [comment]
We've just been discussing this - so yes, this does look possible. 

We've identified that there might be some wider issues with use of XM-DAC, so planning to talk with IATI team about that more at a meeting in August.
