### ISSUE TITLE
Clarification on ID-KHH

### ISSUE THREAD

**Issue by jahnvidave** [org-id/register#223]
## Clarification

Hi,

I have received a Registration Certificate from an organisation that is registered in Indonesia, who are trying to create their IATI Org ID. I would like to clarify a couple of things regarding how to do this.

I can send this certificate via email, if that would be helpful. Please let me know which email address to send this to.

1) Firstly, the certificate says: 'DECREE OF THE MINISTER OF LAWS AND HUMAN RIGHTS
OF THE REPUBLIC OF INDONESIA'
Can you please confirm that this is the same as the Ministry of Justice and Human Rights (ID-KHH), that is listed here: http://org-id.guide/list/ID-KHH.

2) Secondly, there are two numbers on the certificate: AHU‐000022.AH.01.07.2015 and 6015010634100023.
It is not clear which should be taken as the unique registration number to follow the code ID-KHH. 
Please could you give me some guidance as to which is correct?

Thank you,
Jahnvi

**Comment by duncandewhurst** [comment]
Hi Jahnvi,

Please send a copy of the certificate to contact@org-id.guide and I'll take a look at it.

Best regards,

Duncan

**Comment by jahnvidave** [comment]
Hi Duncan,

Apologies for the delay. I have now emailed the certificate to contact@org-id.guide.

Thanks for your help.

Kind regards,
Jahnvi

**Comment by timgdavies** [comment]
> Firstly, the certificate says: 'DECREE OF THE MINISTER OF LAWS AND HUMAN RIGHTS
OF THE REPUBLIC OF INDONESIA'
> Can you please confirm that this is the same as the Ministry of Justice and Human Rights (ID-KHH), that is listed here: http://org-id.guide/list/ID-KHH.

I can confirm that we understand these two institutions to be the same. The logo on the paperwork shared, and the website linked from the org-id.guide entry match.

> Secondly, there are two numbers on the certificate: AHU‐000022.AH.01.07.2015 and 6015010634100023.
> It is not clear which should be taken as the unique registration number to follow the code ID-KHH.

AHU‐000022.AH.01.07.2015 appears to be the identifier of the declaration, but  6015010634100023 is the registration number, and so should be used the form the identifier.

**ID-KHH-6015010634100023**
