### ISSUE TITLE
PROPOSAL: [Rol Único Tributario de Chile RUT]

### ISSUE THREAD

**Issue by yolile** [org-id/register#225]
## Proposal
Rol Único Tributario de Chile, managed by the Servicio de Impuestos Internos (SII) of the "Ministerio de Hacienda" of Chile.

**A suggested code for the list [optional]**
 CL-RUT

**A short description of the list**
They must obtain a Rol Único Tributario (Rut) every Legal Person or entity without legal personality that, due to its activity or condition, causes or may cause taxes.

**The country or countries that the list covers**
Chile

**The legal form or organizations that the list covers**
Legal persons 

**Any specific sectors that the list covers**
All sectors, private providers and public entities

**A URL for information on the list, and a URL for looking up identifiers [if available]**
How to get the RUT:
http://www.sii.cl/servicios_online/1031-.html

**Any information on available open data copies of this list**
I found some RUTs here: https://www.registros19862.cl/reportes/receptores?institucion%5Brut%5D=&institucion%5Bdescripcion%5D=&clase%5B0%5D=&ubicacion%5Bid_region%5D=&ubicacion%5Bid_provincia%5D=&ubicacion%5Bid_comuna%5D=&commit=Ejecutar+Reporte
And here (for suppliers): http://www.chileproveedores.cl/
 
**One or more examples of identifier from this list, and how you found them**
from: http://webportal.mercadopublico.cl/proveedor/76424135-5?_ga=2.40159906.1248593751.1526648970-160293667.1526648970
**RAZÓN SOCIAL**
ZBOX SPA
**RUT**
76.424.135-5
**GIRO**
EMPRESAS DE SERVICIOS INTEGRALES DE INFORMATICA

from: https://www.registros19862.cl/fichas/ver/rut/61602121/clase/5
  **Rut** : 61.602.121-4
  **Nombre** : HOSPITAL DE PEÑAFLOR
  **Razón Social** : HOSPITAL DE PEÑAFLOR
  **Tipo de Institución** : Empresas
 **Área temática** : Salud

**Comment by timgdavies** [comment]
Thanks @yolile - With apologies for the delay, I've now got CL-RUT staged for inclusion in org-id.guide, such that it should go live in the next 7 days.

**Comment by timgdavies** [comment]
This is now included in the list.
