### ISSUE TITLE
PROPOSAL: Kenya Ministry of Lands, Trustees Registration Agency

### ISSUE THREAD

**Issue by jahnvidave** [org-id/register#231]
## Proposal

**The name of the list (or the organization that manages the list)**
Organisations are registered with the Ministry of Lands, under the Trustees Act of Kenya. 

**The country or countries that the list covers**
Kenya

**The legal form or organizations that the list covers**
Trusts

**One or more examples of identifier from this list, and how you found them**
Registration number: 367/D1/567/4793/DXXVI 
Found on the organisation's Deed of Registration.

**Comment by timgdavies** [comment]
As far as I can see, the Ministry of Lands does not issue identifiers.

The example supplied (offline) shows a stamp from the 'Registrar of Documents' under the ['Registry of Documents Act' (§24)](http://kenyalaw.org/lex/rest//db/kenyalex/Kenya/Legislation/English/Acts%20and%20Regulations/R/Registration%20of%20Documents%20Act%20Cap.%20285%20-%20No.%2026%20of%201902/docs/RegistrationofDocumentsAct26of1902.pdf) which describes how an identifier is assigned to the **document**:

> 24. Method of registration
> (1) Every person desiring to register a document shall produce the original
document to be registered at the office of the registrar.
> (2) Subject to the provisions of this Act, the registrar shall register the document
by filling a photostatic copy thereof in the register in such manner as the Principal
Registrar may direct, and shall number every such copy consecutively and shall
inscribe thereon the day of the month and year when it was presented for
registration.

In the case of a trust, this may be the best identifier available (given the trust deed effectively creates the trust, so the identifier assigned to this document has a relevant status).

**Comment by timgdavies** [comment]
The Kenya Revenue Authority issue PIN (Personal Identification Number) to both individuals and organisations. They say:

> Personal includes both an individual as well as an artificial person (i.e. company, club, Trust, etc)

In this case, a PIN may be preferable to trust deed document registration code. @jahnvidave Can you ask the organisation looking for an identifier if they are aware of the their PIN?

This would likely then get staged as KE-KRA-{PIN}   for 'Kenya Revenue Authority' as the list source.

**Comment by jahnvidave** [comment]
Thank you for the update. I have followed up with the organisation regarding their PIN.

The organization has KRA PIN: P051119468K

**Comment by timgdavies** [comment]
Thanks @jahnvidave - I've stated KE-KRA for inclusion in org-id.guide, which can be merged in 7 days. This would give an IATI string of:

> KE-KRA-P051119468K

I've confirmed the PIN is valid using the checker at https://itax.kra.go.ke/KRA-Portal/pinChecker.htm?actionCode=loadPage&viewType=static which also confirms address details for the organisation.

**Comment by jahnvidave** [comment]
That's great! Thank you Tim.
