### ISSUE TITLE
PROPOSAL: Costa Rica National Registry

### ISSUE THREAD

**Issue by jahnvidave** [org-id/register#235]
## Proposal

**The name of the list (or the organization that manages the list)**
Organisations are registered in the Republic of Costa Rica, on the National Registry (Registro Nacional).

**The country or countries that the list covers**
Costa Rica

**One or more examples of identifier from this list, and how you found them**
From a registration certificate (certificacion de personeria juridica) sent in by an organisation: 
- NUMERO DE CERTIFICACION: RNPDIGITAL-8855032-2018
- PERSONA JURIDICA: 3-006-125548

I will send this certificate in an email.

Thanks,
Jahnvi

**Comment by timgdavies** [comment]
I've checked and after registering at https://www.rnpdigital.com/ it is possible to use the free services to search for a legal entity, and to find a registration number. 

I've staged a new entry in #236 with the code 'CR-RPJ' to stand for Costa Rica 'Registro de Personas Jurídicas' (as the national registry maintains other identifier schemes as well).
