### ISSUE TITLE
REQUEST: Israel Ministry of Interior - NPO Registrar

### ISSUE THREAD

**Issue by amy-silcock** [org-id/register#237]
## Request

**What type of organization do you want identifiers for?** Non Profit Organisations

**In which countries are the organizations you want identifiers for based?**: Israel

**Do you have examples of organizations you need identifiers for?** Musalaha Ministry of Reconciliation

**Comment by timgdavies** [comment]
The notes at http://www.israelnonprofitnews.com/guide-to-non-profits/ suggest that Non-profits in Israel may be in the Register of Companies (http://org-id.guide/list/IL-ROC) 

I will check with @morchickit to confirm.

**Comment by morchickit** [comment]
Well, it is! The ministry of justice holds the register for companies and
charities. It's actually under Rasham Ha'amutot, which the charity
registry, under the companies registries.

Not that Israel also have VAT registry to all companies and charities that
is open!

**Comment by morchickit** [comment]
This link in the data portal link to the Charities dataset and the CIC
dataset - https://data.gov.il/dataset/moj-amutot
Remember that the data is in Hebrew, so you will need to find the Hebrew
name for - Musalaha Ministry of Reconciliation  , I couldn't find it on
Guidestar, which makes me think it is not registered in Israel, at least
not under it Hebrew name מסאלחה . In general I would not trust a program
like that which doesnt not information in Hebrew or Arabic...

Enjoy!

**Comment by amy-silcock** [comment]
@morchickit on Guidestar they are here I think: https://www.guidestar.org.il/organization/580166452

**Comment by morchickit** [comment]
Yes, really odd that on their website they spell their name differently... !

**Comment by timgdavies** [comment]
Thank you both! 

So - checking at the search we have for the Company Register ([IL-ROC](http://org-id.guide/list/IL-ROC)) does not return any results for 580166452, but searching at https://ica.justice.gov.il/Request/OpenRequest?rt=ExposeDocumentsAssociation does - so I'm happy for us to consider these as two separate lists from org-id.guide perspective. 

From https://data.gov.il/dataset/moj-amutot I understand that there may be:

* Companies registered for public benefit (in the ROC)
* Charities registered with Rasham Ha'amutot

It looks like these are ultimately from the same broad identifier scheme, such that Registry of Company numbers begin 51 - 56, and Rasham Ha'amutot numbers begin 58

I think this does support through still having:

- IL-ROC - which will contain all companies, and **some** companies with charitable purpose (codes starting 51-56)
- IL-RA - Which will be a new code for Rasham Ha'amutot entries for charities (codes starting 58)

I can work on staging this in the next day or so. In doing so I'll also link to GuideStar as a useful place to search.

**Comment by timgdavies** [comment]
Thanks @morchickit for all the help on this. I've now got IL-RA staged for inclusion in org-id.guide.
