### ISSUE TITLE
REQUEST: University in Bangladesh

### ISSUE THREAD

**Issue by jahnvidave** [org-id/register#239]
## Request

**What type of organization do you want identifiers for?** 
University - autonomous institution set up by a constitutional act, Act 1, 1998

**In which countries are the organizations you want identifiers for based?**: 
Bangladesh

**Do you have examples of organizations you need identifiers for?**
Bangabandhu Sheikh Mujib Medical University (BSMMU)

**Comment by timgdavies** [comment]
Institutions set up by constitutional acts often do not have official registration numbers.

org-id.guide has [XI-GRID](http://org-id.guide/list/XI-GRID) as an identifier source for academic institutions, which does have an entry for BSMMU here: https://www.grid.ac/institutes/grid.411509.8

This would give an ID of `XI-GRID-grid.411509.8`

I've checked in the search service provided by the Office of the Register of Joint Stock Companies and Firms (ROC), but could not locate any entry for BSMMU, leading me to conclude that the XI-GRID code is the best option.

**Comment by jahnvidave** [comment]
That is great. Thanks Tim!
