### ISSUE TITLE
Request:NGO partner in CAR

### ISSUE THREAD

**Issue by RyanTF** [org-id/register#247]
## Request

**What type of organization do you want identifiers for?** [ Government / NGO or Charity / Government / other]

NGO

**In which countries are the organizations you want identifiers for based?**: 

Central African Republic

**Do you have examples of organizations you need identifiers for?**

the organization is called "Association Centrafricaine de Traduction de la Bible et Alphabetisation"

**Comment by timgdavies** [comment]
I've not been able to find much information on Central African Republic online, with the exception of a government website at http://presidence.govcf.org/le-gouvernement/

This [US State Department briefing](https://www.state.gov/documents/organization/186388.pdf) suggests that: "All associations, including political parties, must apply to the Ministry of Interior for registration, and the government usually granted registration expeditiously."

@RyanTF Can you confirm if "Association Centrafricaine de Traduction de la Bible et Alphabetisation" is registered with the Ministry of Interior, and if so, share a screenshot of, or any details from, a registration certificate that might indicate whether or not a registration number is issued as part of this process. 

I've checked our usual 'fallback' lists of [XM-OCHA](http://org-id.guide/list/XM-OCHA) for mentions of Association Centrafricaine de Traduction de la Bible et Alphabetisation, but did not find them there

**Comment by RyanTF** [comment]
@timgdavies Hi Tim, apologies for the long delay. I know have the organisation certificate with the ministry of interoirs. The organisation code is below:

047/DGAT.DAPA.SAP

I can also send the certificate if need be as a digital document (its in french).

**Comment by RyanTF** [comment]
@ScatteredInk Apologies, I've realised that Tim is now on extended leave etc. is is possible for this to be followed up as soon as possible? We're aiming to train ACTABA on publishing very shortly.

Thank you

**Comment by ScatteredInk** [comment]
@RyanTF Apologies, I missed this notification first time round. I'm closing this as it is being covered in #288 - @kd-ods will have an update shortly.
