### ISSUE TITLE
REQUEST: Trust registered in Botswana

### ISSUE THREAD

**Issue by jahnvidave** [org-id/register#248]
## Request

**What type of organization do you want identifiers for?** 
Trust

**In which countries are the organizations you want identifiers for based?**: 
Botswana

**Do you have examples of organizations you need identifiers for?**
WaterNet
"WaterNet is registered as a Trust in Botswana and the Notarial Deed of Trust Number is MA 810/2006.
WaterNet is also registered with BURS (Botswana Unified Revenue Services) under the Tax reference number  T087389-01-01-0."

**Comment by timgdavies** [comment]
In this case, I think the Taxpayer Identification Number (TIN) looks likely to be the better identifier option, as there will be an authority list of these (even if not public) - as opposed to the trust deed numbers, which are unlikely to be registered anywhere (given I understand that Botswana's trust law does not require registration of trusts). 

I will look at staging BW-TIN shortly. 

Looking at how company Taxpayer Identification Numbers are formatted (without - in), I suspect the constructed ID should then be:

BW-TIN-T08738901010

**Comment by jahnvidave** [comment]
Thank you Tim for your quick response.

I have emailed you a copy of the tax certificate for WaterNet, for your information.

**Comment by timgdavies** [comment]
Having seen the certificate, it appears the final digits are not required, so the identifier would be: BW-TIN-T087389

**Comment by jahnvidave** [comment]
Great. Thank you for clarifying that.
