### ISSUE TITLE
REQUEST: Jersey Aid Agency

### ISSUE THREAD

**Issue by jahnvidave** [org-id/register#250]
## Request

**What type of organization do you want identifiers for?** 
Independent international aid agency

**In which countries are the organizations you want identifiers for based?**: 
Jersey

**Do you have examples of organizations you need identifiers for?**
Jersey Overseas Aid
- "an independent international aid agency funded by the States of Jersey"
- "our organisation is not covered by a registration authority."
- Jersey Overseas Aid Commission was established by The Jersey Overseas Aid Commission (Jersey) Law 2005 (P.14/2005)

**Comment by timgdavies** [comment]
I've checked DAC lists, and it appears Jersey is not covered by the OECD Development Assistance Committee list of donors. 

There was previously a JE-OAS code inherited from the IATI Organisation Registration Agency codelist, but this was deprecated as it related to a single organisation, not a list. 

I've not been able to locate an official list of government agencies. One fall back that has been used in some countries is the Chart of Accounts - but I've also not located this to Jersey.

As Jersey Overseas Aid is not a registered organisation - and we're not able to locate a list of government agency identifiers - it may fall outside the scope of what org-id.guide can help with - and you may need to explore an XI-IATI option here.

**Comment by jahnvidave** [comment]
Thank you for checking through the various lists. We will start the process for an XI-IATI identifier.
