### ISSUE TITLE
REQUEST: University in Tanzania

### ISSUE THREAD

**Issue by jahnvidave** [org-id/register#251]
## Request

**What type of organization do you want identifiers for?** 
University

**In which countries are the organizations you want identifiers for based?**: 
Tanzania

**Do you have examples of organizations you need identifiers for?**
Mzumbe University
Mzumbe University does not have a registration certificate. It was established by 'The Mzumbe University Charter, 2007'. The charter would have been granted under s.25 of the Universities Act, 2005.

I will send a copy of the charter via email.

**Comment by timgdavies** [comment]
As an organisation without registration in a company or charity register, and in the absense of an org-id.guide entry for government-related agencies in Tanzania, we can look at fall-back lists. One of these is XI-GRID which covers educational institutions. 

Mzumbe University is included in the XI-GRID list at https://www.grid.ac/institutes/grid.442465.5 which would give an identifier of:

> XI-GRID-grid.442465.5

**Comment by jahnvidave** [comment]
Thank you Tim. (I had forgotten about the XI-GRID list - again!) This is really helpful.
