### ISSUE TITLE
REQUEST: AgResults Initiative

### ISSUE THREAD

**Issue by jahnvidave** [org-id/register#252]
## Request

**What type of organization do you want identifiers for?** 
Multi-donor initiative

**In which countries are the organizations you want identifiers for based?**: 
N/A

**Do you have examples of organizations you need identifiers for?**
AgResults Initiative
"AgResults is not registered individually. 
It is governed by a “Fund Framework” that outlines responsibilities of each donor and entity involved. 
No donor acts as the lead organization, although all funds are managed by the World Bank as Trustee.
Deloitte Consulting manages the Secretariat but the donors do not allow Deloitte to use its name with respect to AgResults."

We are considering proposing an XI-IATI identifier, if there is no suitable alternative.

**Comment by timgdavies** [comment]
From an organisation identifier point of view - there does not appear to be an organisation to identify here, so unless this is already covered by a DAC type codelist, I'd suggest the XI-IATI route for constructing an IATI identifier for the publisher.

In terms of the **organisation identifiers** within IATI files, I would anticipate that these should really have World Bank as the organisation holding and disbursing the funds.

**Comment by jahnvidave** [comment]
Thank you!

**Comment by andylolz** [comment]
> constructing an IATI identifier for the publisher

…

> In terms of the **organisation identifiers** within IATI files

I am really confused. @timgdavies are you saying these are two different things?

As I understand it, the `iati-identifier` element was renamed as `organisation-identifier` in the upgrade to v2.01 ([reference](http://reference.iatistandard.org/203/organisation-standard/iati-organisations/iati-organisation/organisation-identifier/#id2)). Have I misunderstood? If so, can you explain the difference between these things?

**Comment by andylolz** [comment]
Okay, I think I see. I think when you say “IATI identifier”, you’re talking about the [reporting-org reference](http://reference.iatistandard.org/203/activity-standard/iati-activities/iati-activity/reporting-org/#attributes), as well as the organisation identifier used in the IATI registry metadata. I think “IATI identifier” is used as a shorthand for IATI organisation identifier, which is a reference to the [IATI organisation identifier codelist](http://reference.iatistandard.org/203/codelists/IATIOrganisationIdentifier/).

When you say “organisation identifier”, you’re talking about the organisation identifier used for transactions, e.g. [the provider-org reference](http://reference.iatistandard.org/203/activity-standard/iati-activities/iati-activity/transaction/provider-org/#attributes).

Is that correct?

**Comment by timgdavies** [comment]
Correct.

The use of organisation identifier to construct (a) reporting org reference
and then (b) the activity identifier (composite of reporting org + internal
activity ID) causes issues when a single legal entity wants to report
different funds it hosts as if they are from different organisations.

Meeting with IATI support team @ DI next week and will discuss this and aim
to feedback.

**Comment by andylolz** [comment]
> Meeting with IATI support team @ DI next week and will discuss this and aim to feedback.

Great – thanks.

**Comment by andylolz** [comment]
@timgdavies any news? Looks like this is about to be merged so any feedback you can provide would be great. Specifically on this:

> when a single legal entity wants to report different funds it hosts as if they are from different organisations.

^^ Would be good to know what the benefit of this would be from the perspective of the data user.
