### ISSUE TITLE
REQUEST: Wessex Ghana Stroke Partnership

### ISSUE THREAD

**Issue by jahnvidave** [org-id/register#254]
## Request

**What type of organization do you want identifiers for?** 
Partnership of healthcare professionals

**In which countries are the organizations you want identifiers for based?**: 
UK, Ghana

**Do you have examples of organizations you need identifiers for?**
Wessex Ghana Stroke Partnership
"A voluntary group of healthcare professionals, based in Wessex, UK.  
We have a long established Health Partnership with a team in Accra, Ghana.  
We are not a registered charity.  
We are currently in receipt of a Health Partnership Scheme Grant via THET.
Our funds are hosted by Southern Health NHS Foundation Trust in the UK"

**Comment by timgdavies** [comment]
org-id.guide can only be used to identify legal entities. In this case, the legal entity hosting the partnership appears to be Southern Health NHS Foundation Trust. 

The list for this would be [GB-NHS](http://org-id.guide/list/GB-NHS) and using the Organisation Data Service API (a little tricky to track down!) at [https://directory.spineservices.nhs.uk/ORD/2-0-0/organisations?Name=Southern%20Health%20NHS%20Foundation%20Trust](https://directory.spineservices.nhs.uk/ORD/2-0-0/organisations?Name=Southern%20Health%20NHS%20Foundation%20Trust) provides the code RW1, which would mean the IATI organisation identifier for Southern Health NHS Foundation Trust is GB-NHS-RW1

**Comment by jahnvidave** [comment]
Great! Thanks, Tim, for looking into this, and for tracking down the Trust's API.
