### ISSUE TITLE
PROPOSAL: Georgian Revenue Service, GE-RS

### ISSUE THREAD

**Issue by sofiiashnyr** [org-id/register#259]
## Proposal

The Revenue Service of Georgia (RS) operates under the Ministry of Finance of Georgia and is obligated to register all governmental organizations under the MoF Order #996 on Administration of Taxes which regulates issuing of Identification Numbers to all organizations except entrepreneurs (ltd, Joint Stock Company, Cooperative, etc.), which is issued by the Ministry of Justice (NAPR). National Agency of Public Registry is obligated under the law to to provide information about newly registered businesses to RS. Every new registration is uploaded to RS within 2 minutes. http://www.rs.ge/5385 contains all Georgian organisations capable of procurement.

## Georgian Revenue Service

Revenue Service, the MoF of Georgia

GE-RS

To receive an ID, an organization has to inquire in writing to the MoF. All organizations have 9-digit IDs and Individuals have 11-digit IDs. For taxing purposes, same ID is used for entrepreneurs as their registration ID.

Georgia

Budgetary organisations, legal entities under public law, non-entrepreneurial (non-commercial) legal
entities - a higher education institution and the higher education institution development fund.

Governmental sector

http://www.rs.ge/5385 (in Georgian, with a captcha for each request)

No open data copies of this list found.

Organizations can be searched by their legal name or identification number. Example ID of Gedevan Popkhadze, Bureau of Majoritarian MP of Borjomi Municipality N45 District budgetary organization: 226166895.

**Comment by timgdavies** [comment]
Thanks @sofiiashnyr - I've staged GE-RS for inclusion in org-id.guide as an identifier source for Companies and Government Agencies.
