### ISSUE TITLE
PROPOSAL: Supplier Registration Service, Cabinet Office, UK

### ISSUE THREAD

**Issue by duncandewhurst** [org-id/register#261]
## Proposal

**The name of the list (or the organization that manages the list)**

Supplier Registration Service, Crown Commercial Service, UK

**A suggested code for the list (optional)**

GB-SRS

**A short description of the list**

Crown Commercial Service (part of the Cabinet Office) publishes a list of **buyers** registered on the Supplier Registration Service (also known as SID4GOV). The list also appears to include some private companies, trusts and charities.

**The country or countries that the list covers**

United Kingdom

**The legal form or organizations that the list covers**

Government agencies, companies, trusts, charities

**Any specific sectors that the list covers**

**A URL for information on the list, and a URL for looking up identifiers (if available)**

A csv format download of the list is available at the following URL:

https://supplierregistration.cabinetoffice.gov.uk/notices/buyers.csv

**Any information on available open data copies of this list**

See above, no license is provided with the data. 

**One or more examples of identifier from this list, and how you found them**

Published in OCDS data from Contracts Finder ([example](https://www.contractsfinder.service.gov.uk/Published/Notice/releases//66869a96-5e93-4759-a57c-9974e86137a8.json)):

sid4gov.cabinetoffice.gov.uk/9dg3Y6Xv (for BRAVOSOLUTION UK LIMITED)

From the csv download:

supplierregistration.cabinetoffice.gov.uk/B85F8jBe (for Selsey Town Council)

supplierregistration.cabinetoffice.gov.uk/CkSC98Tg (for OXFORD HOSPITALS CHARITY)

**Comment by timgdavies** [comment]
@duncandewhurst I've staged this for inclusion.
