### ISSUE TITLE
PROPOSAL: [Colombia] [Cédula de Ciudadanía CO-CC]

### ISSUE THREAD

**Issue by yolile** [org-id/register#262]
## Proposal

**The name of the list, or the organization that manages the list**

Cédula de Ciudadanía, emited and managed by [Registraduría Nacional del Estado Civil](https://www.registraduria.gov.co/) 

**A suggested code for the list [optional]**

CO-CC

**A short description of the list**

The citizenship card is the document with which Colombians of legal age can identify themselves in all civil, political, administrative and judicial acts. Source: https://www.registraduria.gov.co/-Historia-de-la-Cedula-de,321-.html

**The country or countries that the list covers**

Colombia

**The legal form or organizations that the list covers**

Colombians of legal age

**A URL for information on the list, and a URL for looking up identifiers [if available]**

https://www.registraduria.gov.co/-Cedula-de-Ciudadania,3689-.html
https://www.registraduria.gov.co/-Historia-de-la-Cedula-de,321-.html

**Any information on available open data copies of this list**

There is not a public list

**One or more examples of identifier from this list, and how you found them**

Example: 1.123.123.123
Source: http://aceproject.org/ero-en/regions/americas/CO/materiales/Colombia%20%28Cedula%20%20de%20Identidad%20%20Amarilla%20de%20Hologramas%29.jpg/view

**Comment by timgdavies** [comment]
@yolile As this is a personal identifier, is there a case for inclusion of this in org-id.guide.

In general we would not include any identifiers for individuals: only for entities (e.g. companies).

Is this a number that a public authority should be able to publish as part of their data?

**Comment by yolile** [comment]
@timgdavies In Colombia Compra they publish this personal identifier for a physical person in the contract stage

**Comment by timgdavies** [comment]
Thanks @yolile. Interesting. This officially falls outside the scope of org-id.guide - but it might overlap with the need that will be emerging for a codelist of *personal identifiers* in the [Beneficial Ownership Data Standard](https://github.com/openownership/data-standard/issues/22).

Are you thinking that each of these people would be listed as 'Parties' to the process, and linked in that way?

**Comment by yolile** [comment]
Yes, these people would be listed as Parties with the 'supplier' role

**Comment by timgdavies** [comment]
@yolile I'm going to talk with the Beneficial Ownership Data Standard team about person identifiers, and see if there is something we can propose for identifiers here.

**Comment by yolile** [comment]
This is the case for Honduras too, they publish the ID number,
passport or residence card number as a supplier identifier, some examples: 

http://sicc.honducompras.gob.hn/HC/Contratos/ContratoDD.aspx?Id=NwAAADcAAAA3AAAAMgAAADkAAAA%3d-2Lgi74%2fBkcQ%3d

http://sicc.honducompras.gob.hn/HC/Contratos/ContratoDD.aspx?Id=NwAAADYAAAA1AAAANQAAADMAAAA%3d-OcYuYrpmGFs%3d

 http://sicc.honducompras.gob.hn/HC/Contratos/ContratoDD.aspx?Id=NwAAADYAAAA1AAAANQAAADMAAAA%3d-OcYuYrpmGFs%3d

There is a solution/proposal for this already?

**Comment by duncandewhurst** [comment]
@yolile please see https://github.com/org-id/register/issues/263#issuecomment-548192311

As this is out of scope of org-id I'll close it, if further discussion is required, let's continue in https://github.com/open-contracting/standard/issues/801
