### ISSUE TITLE
PROPOSAL: [Colombia] [Cédula de Extranjería  CO-CE]

### ISSUE THREAD

**Issue by yolile** [org-id/register#263]
## Proposal

**The name of the list, or the organization that manages the list**

Cédula de Extranjería, managed by [Ministerio de Relaciones Exteriores, Migraciones] (http://migracioncolombia.gov.co)

**A suggested code for the list [optional]**

CO-CE

**A short description of the list**

Identification document issued by Migración Colombia, which is granted to foreigners holding a visa for more than 3 months and their beneficiaries based on the registration of foreigners.

**The country or countries that the list covers**

Colombia

**The legal form or organizations that the list covers**

Foreigners older that 18 years holding a visa for more than 3 months and their beneficiaries based on the registration of foreigners.

**A URL for information on the list, and a URL for looking up identifiers [if available]**

http://migracioncolombia.gov.co/index.php/es/tramites-2016/3281-tramite-cedula-de-extranjeria
http://www.dre.unal.edu.co/fileadmin/docs/movilidad/Tramite_Cedula_de_Extranjeria.pdf

**Any information on available open data copies of this list**

There is not a public list

**One or more examples of identifier from this list, and how you found them**

123.456

Source: https://www.supernotariado.gov.co/portalsnr/images/archivosupernotariado/normatividad2013/circulares/circular692de2013/circular692de2013anexo.pdf

**Comment by timgdavies** [comment]
As discussed in #262 - I'm not sure whether this would qualify for inclusion in org-id.guide, as it identifies individuals rather than organisations.

Are there procurement or other contexts in which these numbers would be published?

**Comment by duncandewhurst** [comment]
@yolile, as Tim suggested, since these are personal identifiers they are out of scope of org-id.

Please follow the [guidance on person identifiers](http://standard.openownership.org/en/latest/schema/guidance/identifiers.html#person-identifiers) from BODS to create a scheme code for these identifiers, per my comment in https://github.com/open-contracting/standard/issues/801
