### ISSUE TITLE
PROPOSAL: Clasificador Institucional del Sector Público GT-CISP

### ISSUE THREAD

**Issue by yolile** [org-id/register#268]
## Proposal

**The name of the list, or the organization that manages the list**

Clasificador Institucional del Sector Público, [Ministerio de Finanzas Públicas of Guatemala](http://www.minfin.gob.gt/)

**A suggested code for the list [optional]**

GTM-CISP

**A short description of the list**

The political-administrative organization of the Public Sector of Guatemala, gives rise to several institutions with relative independence from each other, with precise functions granted by the Political Constitution of the Republic of Guatemala and other laws.
This leads to each having their own annual income budget and Expenditures, and the set of these budgets make up the Sector Budget Public.
The institutional classifier organizes the Public Sector into: General Government and Public enterprises. This sectorization of institutions and units Public Sector Governance is based, not only on the legal aspects of its constitution, but also, in the economic, budgetary and statistical relevance, that make them participants or co-participants in the implementation of State policies.
The institutional classification is a reflection of what the budgetary system and the fiscal accounting define as Public Sector for control purposes budgetary and patrimonial and the generation of fiscal statistics. [1]

**The country or countries that the list covers**

Guatemala

**The legal form or organizations that the list covers**

Public Sector

**Any specific sectors that the list covers**

Public Sector, all institution 

![image](https://user-images.githubusercontent.com/6834122/45236643-7ad89980-b2aa-11e8-85ef-bc546574629f.png) [1]

**A URL for information on the list, and a URL for looking up identifiers [if available]**

Info: http://www.minfin.gob.gt/images/downloads/leyes_manuales/manuales_dtp/clasificaciones_presup_sector_publico.pdf

**Any information on available open data copies of this list**

The list is in the page 29 to 44 in [1]

**One or more examples of identifier from this list, and how you found them**

![image](https://user-images.githubusercontent.com/6834122/45236732-b4110980-b2aa-11e8-870f-4849c0d3f149.png) [1]

id: 11130003, name: Presidencia de la República

Ref: http://www.minfin.gob.gt/images/downloads/leyes_manuales/manuales_dtp/clasificaciones_presup_sector_publico.pdf

**Comment by timgdavies** [comment]
@yolile Apologies for the delay in actioning this request. I've now staged this as **GT-CISP** (Note the use of 2-digit rather than 3-digit ISO code)
