### ISSUE TITLE
REQUEST: Democratic Governance Facility (DGF)

### ISSUE THREAD

**Issue by jahnvidave** [org-id/register#269]
## Request

**What type of organization do you want identifiers for?** 
Governance programme

**In which countries are the organizations you want identifiers for based?**: 
Operating in Uganda, but established by several countries.

**Do you have examples of organizations you need identifiers for?**
Democratic Governance Facility in Uganda (https://www.dgf.ug/)
"we are operating in Uganda, but are not registered there. We operate under a MoU with the government of Uganda and under the mandate of the Royal Danish Embassy."

**Comment by timgdavies** [comment]
Org-id.guide only covers identifiers for legally registered organisations. 

As it appears DGF is a programme, you would either need to make a choice in IATI to allow an identifier for this programme, or to require use of an identifier for the organisation legally hosting the programme (possibly Royal Danish Embassy?).

**Comment by jahnvidave** [comment]
Thank you for your response Tim.

**Comment by jahnvidave** [comment]
There was already an [XI-IATI identifier created for DGF](https://discuss.iatistandard.org/t/added-create-org-identifier-xi-iati-dgf/1174) and added to the IATI [codelist](http://reference.iatistandard.org/203/codelists/IATIOrganisationIdentifier/).
Apologies for overlooking this before.
Closing this issue now.
