### ISSUE TITLE
Correction: GB-SC register search and download links

### ISSUE THREAD

**Issue by jahnvidave** [org-id/register#275]
## Correction

Regarding the list for Scottish Charity Register (GB-SC) - http://org-id.guide/list/GB-SC

The two links provided under 'Find and use identifiers', for register search and download, are no longer correct, as the URLs have changed on the OSCR website. Please can these be updated?

Updated links:
Register search: https://www.oscr.org.uk/about-charities/search-the-register/register-search
Register download: https://www.oscr.org.uk/about-charities/search-the-register/charity-register-download

Thanks,
Jahnvi

**Comment by rory09** [comment]
@timgdavies, passing back to you for review and merge.

**Comment by timgdavies** [comment]
Links updated. Thanks @rory09
