### ISSUE TITLE
PROPOSAL: Uganda Medical and Dental Practitioners Council list

### ISSUE THREAD

**Issue by jahnvidave** [org-id/register#284]
## Proposal

**The name of the list (or the organization that manages the list)**
Uganda Medical and Dental Practitioners Council

**The country or countries that the list covers**
Uganda

**The legal form or organizations that the list covers**
Hospitals and other health care providers

**A URL for information on the list, and a URL for looking up identifiers (if available)**
The UMDPC website includes registers for registered practitioners (individuals) and health units: http://www.umdpc.com/registers.php

List of 'Licensed Health Units 2018': http://www.umdpc.com/registers/LICENSED%20HEALTH%20UNITS%202018.pdf
But this does not include registration numbers.

**One or more examples of identifier from this list, and how you found them**
Benedictine Eye Hospital, Tororo - trying to register with IATI, so sent their certificate to us.
I have sent the certificate to contact@org-id.guide, for your information.

**Comment by kd-ods** [comment]
Having looked into the UMDPC register and at the Eye Hospital's certificate, it's not clear that there is a unique registration number for licenced health units. I have emailed the UMDPC for clarification. (See ODSC issues/17113 for correspondence #internal-use)

**Comment by PetyaKangalova** [comment]
Thanks! Based on recent response via email from Kadie  (below), we will go ahead and proceed with creating an XI-IATI identifier.

> I've been in contact with the Uganda Medical and Dental Practitioners Council to ascertain whether licensed establishments have usable identifiers. A recent reply from the them has established that, although the Council does have unique registration numbers for medical establishments, these are not shared with establishments (by using them on certificates, for instance) and they are not in a publicly available register.
In the short term a fallback identifier source will need to be used for the Eye Hospital if it has no other candidate identifier.

**Comment by PetyaKangalova** [comment]
Hi all. Happy New Year! Jahnvi has added a post on IATI Discuss about this one and some additional information has been provided by Matt Geddes : https://discuss.iatistandard.org/t/new-organisation-identifier-xi-iati-beh/1598/2

Does this help in being able to create an identifier? IT seems that they are on the national health facility master list: http://health.go.ug/sites/default/files/PHC%20GUIDELINES%20%20%20FY2016-17_Final.pdf

**Comment by kd-ods** [comment]
Hi Petya-

It looks like the ID for the Benedictine Eye Hospital which is used on the list of grants in that document is an IFMS supplier ID. This is an internal ID from the Ministry of Finance's 'Integrated Financial Management System': https://www.finance.go.ug/mofped/integrated-financial-management-system. 

As such it's not an openly published ID and its status (whether it is unique, persistent etc.) is undocumented publicly.

Of course this might change in the future, making it a good candidate for inclusion in Org-ID.
