### ISSUE TITLE
PROPOSAL: Afghanistan Tax Identification Number

### ISSUE THREAD

**Issue by duncandewhurst** [org-id/register#287]
## Proposal

**The name of the list (or the organization that manages the list)**

Afghanistan Tax Identification Number

**A suggested code for the list (optional)**

AF-TIN

**A short description of the list**

TIN is a ten digit number which is issued to all individuals, companies and organizations that operate in Afghanistan. It is a permanent identification number and never changes, but the date of issue has to be renewed annually on the date of expiration.

**The country or countries that the list covers**

Afghanistan

**The legal form or organizations that the list covers**

* Individuals, companies and organizations which are, according to the Income Tax Law 2009 and the Customs Law, required to pay taxes or customs duties
* Social, nonprofit and welfare organizations which are required to withhold taxes from the salaries or wages of their employees* Persons who have an account or open an account with a bank or other financial institution; and
* Employees whose incomes are subject to income tax withholding under provisions of the Income Tax Law 2009

**Any specific sectors that the list covers**

n/a

**A URL for information on the list, and a URL for looking up identifiers (if available)**

Information: https://www.ahg.af/data/offer/taxation/English/Guide%2018%20-%20Taxpayer%20Identification%20No.pdf

Identifier lookup: https://www.acbrip.gov.af/companyverification/

**Any information on available open data copies of this list**

n/a

**One or more examples of identifier from this list, and how you found them**

9000082348
9000453309

The TIN is used as an identifier in the [OCDS data](https://ocds.ageops.net/) published by the Afghanistan National Procurement Authority, these identifiers were checked against the lookup on the ACBRIP site.

**Comment by duncandewhurst** [comment]
@rory09 I'm getting a 404 error on http://org-id.guide/list/AF-TIN

**Comment by duncandewhurst** [comment]
All working now

**Comment by siwhitehouse** [comment]
I've just double-checked and http://org-id.guide/list/AF-TIN is live
