### ISSUE TITLE
Request: Rwanda Revenue Authority (TIN numbers)

### ISSUE THREAD

**Issue by jahnvidave** [org-id/register#293]
## Request

**What type of organization do you want identifiers for?** 
Intergovernmental organisation

**In which countries are the organizations you want identifiers for based?**: 
Rwanda

**Do you have examples of organizations you need identifiers for?**
Greater Virunga Transboundary Collaboration (GVTC)
GVTC is an intergovernmental organization, operating under diplomatic number 76 of the Ministry of Foreign Affairs in Rwanda, and is registered with the Rwanda Revenue Authority with TIN number 10319763

**Comment by jahnvidave** [comment]
Hi! I have now sent GVTC's registration certificate in an email to 'contact@org-id.guide'. Thanks

**Comment by kd-ods** [comment]
Looking at the following information on the Rwanda Revenue Authority website it looks like the TIN number is unique and used for all types of tax payer: 

- https://www.rra.gov.rw/index.php?id=45&L=1%27A%3D0
- https://www.rra.gov.rw/index.php?id=163
- https://www.rra.gov.rw/typo3conf/ext/complete/Resources/Public/download/pdf/itangazo_tin_17_feb.pdf

I'll propose that we add this list as RW-RRA, making the identifier of the GVTC: RW-RRA-103197639

**Comment by jahnvidave** [comment]
@kd-ods Thank you Kadie!

**Comment by kd-ods** [comment]
Resolved with addition of http://org-id.guide/list/RW-RRA
