### ISSUE TITLE
Registration Agency needed for Sudan 

### ISSUE THREAD

**Issue by amy-silcock** [org-id/register#305]
## Request

**What type of organization do you want identifiers for?** 
NGO or Charity

**In which countries are the organizations you want identifiers for based?**: 
Sudan

**Do you have examples of organizations you need identifiers for?**
 United Darfur Committees / Saifadine Dahab Yassin

contact@org-id.guide have received e-mails and example registration certificate for this organisation. Potentially from the East Darfur State Humanitarian Aid Commission?

**Comment by siwhitehouse** [comment]
**The name of the list (or the organization that manages the list)**
Humanitarian Aid Commission

A suggested code for the list (optional)
sd-hac

A short description of the list
The Humanitarian Aid Commission, through the registrar general, maintains a list of organisations undertaking voluntary humanitarian work in Sudan.

The country or countries that the list covers
Sudan

The legal form or organizations that the list covers
Charities, Civil Society Organisations, Voluntary organisations

Any specific sectors that the list covers

A URL for information on the list, and a URL for looking up identifiers (if available)
The act establishing the HAC is here https://www.ifrc.org/docs/idrl/858EN.pdf. A Facebook page is maintained here https://www.facebook.com/pg/hac.gov.sd/about/?ref=page_internal. The website at http://hac.gov.sd/index.php/ar/ has been non-responsive while researching this issue.

Any information on available open data copies of this list
n/a

One or more examples of identifier from this list, and how you found them
45 is the identifier on the certificate provided by United Darfur Committees .

**Comment by amy-silcock** [comment]
Thanks Simon,

Feel free to e-mail them directly by responding to the helpdesk ticket

**Comment by siwhitehouse** [comment]
Staged at https://github.com/org-id/register/pull/306

**Comment by siwhitehouse** [comment]
Emails sent to info@hac.gov.sd have bounced.

**Comment by siwhitehouse** [comment]
Following the email bounce I tried contacting HAC through their Facebook account, but didn't receive a response, so we are not able to create an identifier list for them. IATI team are going to create an XI-IATI identifier for them.

**Comment by siwhitehouse** [comment]
Issue closed - no list created

**Comment by Saifadine** [comment]
Pleas try connect https://HumanirarianAID  and Search United Darfur Committees Sudan(UDC)  or https://ops.unocha.org/Projects.aspx?appealid=2932&type=my#original
