### ISSUE TITLE
PROPOSAL:  Spain Ministry of Justice

### ISSUE THREAD

**Issue by rory09** [org-id/register#307]
## Proposal

**The name of the list (or the organization that manages the list)**: The Ministry of Justice

**A suggested code for the list (optional)**: ES-MOJ

**A short description of the list**: The Ministry of Justice keeps a broad array of records, covering organisations, events, and individuals. Some of these records (such as organisations) are public and searchable, whilst others (civil registration) are not. 

**The country or countries that the list covers**: Spain

**The legal form or organizations that the list covers**: "Property and Mercantile", "Mediators and Mediation Institutions", "State competition foundations", "Religious Entities".

**Any specific sectors that the list covers**: see above

**A URL for information on the list, and a URL for looking up identifiers (if available)**: 

* High level records page (including non-organisation sections): http://www.mjusticia.gob.es/cs/Satellite/Portal/es/areas-tematicas/registros
* Property and Mercantile: http://www.mjusticia.gob.es/cs/Satellite/Portal/es/areas-tematicas/registros/propiedad-mercantiles
* Mediators and Mediation Institutions: http://www.mjusticia.gob.es/cs/Satellite/Portal/es/areas-tematicas/registros/mediadores-instituciones
* State Competition Foundations: http://www.mjusticia.gob.es/cs/Satellite/Portal/es/ciudadanos/registros/fundaciones-competencia
* Religious Entities: http://www.mjusticia.gob.es/cs/Satellite/Portal/es/areas-tematicas/registros/entidades-religiosas

**Any information on available open data copies of this list**: there are multiple search interfaces for each of the organisation types listed above, though there does not appear to be any way of bulk downloading the data.

**One or more examples of identifier from this list, and how you found them**

Searching for "AYUDA EN ACCION" on the State Competition Foundations Finder, yields this page: http://fundosbuscador.mjusticia.gob.es/fundosbuscador/DetalleFundacion.action?idFundacion=16524&index=1&lang=es_es

Here you can see the Nº de registro: 539SND

**Note**: this search is very brittle. Searching for "AYUDA ACCION" does not yield any results, nor does searching for words in the wrong order.

**Comment by siwhitehouse** [comment]
Implemented by PR #316 and the list is visible at http://org-id.guide/list/ES-MDJ
