### ISSUE TITLE
REQUEST: Private sector in Ghana

### ISSUE THREAD

**Issue by SJ-bond** [org-id/register#332]
## Request

**What type of organization do you want identifiers for?** [ Government / NGO or Charity / Government / other]
Company (business, private sector)

**In which countries are the organizations you want identifiers for based?**: 
Ghana - companies are registered by the Registrar General's Department: http://rgd.gov.gh/index.php/services/business-registration/  which issues a certificate of incorporation, which has the incorporation number in the top left hand corner, so an organisation identifier could be:

GH-RGD-XXXXX where XXXX is the incorporation number.

**Do you have examples of organizations you need identifiers for?**
Opportunity International Savings and Loan Ltd (a partner organisation for Opportunity International UK)

**Comment by siwhitehouse** [comment]
The associated pull request has been merged and so the Registrar General's Department is now listed on orgid. See http://org-id.guide/list/GH-RGD
