### ISSUE TITLE
PROPOSAL: Ghana, Registrar General's Department [GH-RGD]

### ISSUE THREAD

**Issue by SJ-bond** [org-id/register#333]
## Proposal

**The name of the list, or the organization that manages the list**
Registrar General's Department, Ghana

**A suggested code for the list [optional]**
GH-RGD-
**A short description of the list**
The Registrar General's Department is mandated by the Government to ensure an efficient and effective administration of entities inter –alia the registration of businesses, industrial property, marriages, administration of estates, and public trustees, to provide customer friendly services and accurate data for national planning. All registered entities receive a certificate of incorporation which has a unique number on the top left hand side.

**The country or countries that the list covers**
Ghana

**The legal form or organizations that the list covers**
Companies and businesses - all NGOs also have to register with the RGD prior to local registration with the local Department of Social Welfare.

**Any specific sectors that the list covers**
All
**A URL for information on the list, and a URL for looking up identifiers [if available]**
http://rgd.gov.gh/

**Any information on available open data copies of this list**
not known

**One or more examples of identifier from this list, and how you found them**
Approached by Opportunity International Savings and Loans Ltd, which is a partner of Opportunity International UK, delivering microfinance programmes in Ghana, and are required to use IATI as funding originates from DFID. OISL confirmed they are registered with the RGD but not DSW (Department of Social Welfare) as they are not an NGO. But the only option currently on org-id is to use the DSW code. Therefore requesting RGD is added as an option to cover private sector organisations delivering international development programmes in Ghana.

**Comment by siwhitehouse** [comment]
Hi there

I've taken a look at the website for the Registrar General's Department and I have not been able to find an online register there, which means that I can't find example certificates of incorporation.

A search online does pull out some examples.

http://evanmike.com/certificates-of-incorporation/
Shows a certificate with 'CS160152013' in the top left hand corner
The incorporation date is 19.02.1996 and the date of signing is 12.03.2013
There is reference to the old TIN and old RGD numbers

https://www.btccl-ghana.com/Cert.html
Shows a certificate with 'CS142392016' in the top left hand corner.
The incorporation date is the same as the date of signing and is 12.08.2016

It looks as though Ghana changed the system for TIN and RGD numbers and that some companies will have those on their certificates when they have re-registered (possibly as part of the change).

I've checked with another five examples and they all correspond to RGD numbers of the form 

'CS' + 5 digit number + year of signing of the incorporation certificate.

I think we can make an argument that these identifiers are both unique and stable. The process for registration is explained here

http://rgd.gov.gh/index.php/services/business-registration/

There is an annual renewal, but no updated certificate is mentioned (stable) and the 5 digit number is sufficient to provide uniqueness on a yearly basis.

Do we want to check with the Registrar General's Department and confirm this?

**Comment by siwhitehouse** [comment]
There is a search form at 

https://egovonline.gegov.gov.gh/RGDPortalWeb/portal/RGDHome/eghana.portal?_nfpb=true&_st=&_pageLabel=portal_RGDHome_NameSearchPage_page&linksPageTitle=Name+Search&service=namesearch#wlp_portal_RGDHome_NameSearchPage_page

A successful search returns: 

Entity Name, Entity Type, Status and Expiry Date

but not the RGD identifier.

**Comment by siwhitehouse** [comment]
I've created a pull request to add the Registrar General's Department at #336

**Comment by siwhitehouse** [comment]
This has been merged, but I still get a 404 error from http://org-id.guide/list/GH-RGD.

The relevant file [gh-rgd](https://github.com/org-id/register/blob/master/lists/gh/gh-rgd.json) appears here https://github.com/org-id/register/tree/master/lists/gh 

Pinging colleagues for help. @kd-ods @rory09 

"lastUpdated": "2016-09-17"

is the only thing that stands out as wrong in the file that I can see.

**Comment by siwhitehouse** [comment]
I hadn't completed the process, d'oh!
