### ISSUE TITLE
REQUEST: Government Agency in Argentina

### ISSUE THREAD

**Issue by dbianco** [org-id/register#337]
## Request

**What type of organization do you want identifiers for?** 
Government

**In which countries are the organizations you want identifiers for based?**: 
Argentina

**Do you have examples of organizations you need identifiers for?**
Direccion Nacional de Vialidad (DNV)

**Short description**
The Direccion Nacional de Vialidad is publicating in next months in his site a page with open data based on the OCDS schema, so we wanted to add a unique identifier for this agency. 

**Specific sectors that the list covers**
Should cover all sectors

**A suggested code for the list [optional]**
AR-DNV 

**URL**
https://www.argentina.gob.ar/transporte/vialidad-nacional/

**Support information**
We already registered a OCID in OCDS web page. See it at http://standard.open-contracting.org/latest/en/implementation/registration/?highlight=ocid#ocid-prefix

**Comment by siwhitehouse** [comment]
Hello Daniel

My apologies for the delay in replying to you.

Can I just check with you that the DNV will be publishing OCDS data? The reason I ask is that org-id identifiers are issued to organisations that provide unique identifiers for companies, charities, government agencies and other kinds of organizations.

Is there a government organization in Argentina that issues unique identifiers to the DNV and other agencies of government?

**Comment by dbianco** [comment]
Hi Simon!
Yes, DNV (Direccion Nacional de Vialidad) will be publishing OCDS data to the public in his site, the goverment as an organization called AFIP that gives uniques ids to private and public entities. For DNV the id is 30546675676 and could be checked on the AFIP site: https://seti.afip.gob.ar/padron-puc-constancia-internet/ConsultaConstanciaAction.do
Let me know if that works for you
Best regards

**Comment by siwhitehouse** [comment]
Hi Daniel

Thank you. So, the CUIT (Código Único de Identificación Tributaria) is the unique taxpayer code for self-employed workers, businesses and public organisations in Argentina. I can see that we already have the [CUIT as a list in org-id](http://org-id.guide/list/AR-CUIT)

Am I right in thinking that the DNV has a need to publish organisation ids for the DNV and also for businesses that are involved in its contracting processes?

If so, then you can already construct identifiers using AR-CUIT. My reading of http://standard.open-contracting.org/latest/en/schema/release/ is that you can use

{
          "identifier": {
            "scheme": "AR-CUIT",
            "id": "30546675676",
            "legalName": "Direccion Nacional de Vialidad",
            "uri": "https://www.argentina.gob.ar/transporte/vialidad-nacional"
          },

within your ocds data to represent the DNV. The pattern will be the same for any of the businesses that are involved in the DNV's contracting processes.

I'd add a big caveat that I am not an expert in OCDS and, if necessary, you should check this with one of my colleagues on the OCDS helpdesk. I'll also ask one of them to review this update for us.

I hope this helps. Please let me know if this answers your question.

All the best
Simon

**Comment by mrshll1001** [comment]
Hi both,

Simon's reply is almost complete but I thought I'd post a reply for clarity. In OCDS the `parties/id` field for an Organization is the full id with the scheme and identifier, and then the identifier details are also included. The full example would be:

```json
{
      "name": "Direccion Nacional de Vialidad",
      "id": "AR-CUIT-30546675676",
      "identifer": {
        "scheme": "AR-CUIT",
        "id": "30546675676",
        "legalName": "Direccion Nacional de Vialidad",
        "uri": "https://www.argentina.gob.ar/transporte/vialidad-nacional"
      },
      "roles": [
        "procuringEntity"
      ]
}
```
Of course, the `roles` array would [change](http://standard.open-contracting.org/latest/en/schema/codelists/?highlight=party%20roles#party-role) depending on if the organization was a buyer, supplier, etc.

Hope that helps!
Matt

**Comment by dbianco** [comment]
Yes, I will use AR_CUIT at package level, that was the motivation for this request (you could see it at http://standard.open-contracting.org/latest/en/release-package-schema.json) 
Thanks for your help!
