### ISSUE TITLE
PROPOSAL: Singapore Commissioner of Charities (SG-COC)

### ISSUE THREAD

**Issue by KDuerden** [org-id/register#354]
## Proposal
Commissioner of Charities
https://www.charities.gov.sg/Pages/Home.aspx

**A suggested code for the list [optional]**

**A short description of the list**
Register of Charities and Institutions of a Public Character

**The country or countries that the list covers**
Singapore

**The legal form or organizations that the list covers**
Charities and IPCs
https://www.charities.gov.sg/setting-up-a-charity/Pages/About-Charities-and-IPCs.aspx

**Any specific sectors that the list covers**

**A URL for information on the list, and a URL for looking up identifiers [if available]**
https://www.charities.gov.sg/_layouts/MCYSCPSearch/MCYSCPSearchCriteriaPage.aspx
**Any information on available open data copies of this list**

**One or more examples of identifier from this list, and how you found them**
The Mission to Seafarers Singapore
UEN No: S83SS0014K 
Singapore Maritime Foundation
UEN No: 200400944W

Source is org ID provided in publisher data

**Comment by siwhitehouse** [comment]
Implemented by #355

**Comment by siwhitehouse** [comment]
@KDuerden Thanks for raising this. I've staged the new entry for SG-COC which should go live on org-id next Monday.
