### ISSUE TITLE
PROPOSAL: Higher Education Statistics Agency - GB-HESA

### ISSUE THREAD

**Issue by drkane** [org-id/register#358]
## Proposal

**The name of the list, or the organization that manages the list**
Higher Education Statistics Agency

**A suggested code for the list [optional]**
GB-HESA

**A short description of the list**
A list of Higher Education providers in the UK, maintained for statistical purposes by the Higher Education Statistics Agency.

**The country or countries that the list covers**
United Kingdom

**The legal form or organizations that the list covers**
Universities and other higher education providers

**Any specific sectors that the list covers**
Higher education

**A URL for information on the list, and a URL for looking up identifiers [if available]**
https://www.hesa.ac.uk/support/providers

**Any information on available open data copies of this list**
[Website terms and conditions](https://www.hesa.ac.uk/about/website/terms) suggest the list is available under CC attribution licence

**One or more examples of identifier from this list, and how you found them**
Aberystwyth University - GB-HESA-0177 - also known as GB-UKPRN-10007856

**Comment by kd-ods** [comment]
@drkane Thanks for raising this proposal. An Org-ID entry has been drafted on the basis of the information you provided (#373). It will be made live on the Org-ID website after 7 days. If you have any further comments or would like to see any changes to the entry, please let us know in the next week if possible.

**Comment by drkane** [comment]
Looks great! Thanks very much.

That CSV download looks useful too - I've just been using the list on the providers page but a CSV file would be better.

**Comment by siwhitehouse** [comment]
Once again, apologies for the delay @drkane. I've merged the new list and it is visible at http://org-id.guide/list/GB-HESA

I'll close the issue with this, but please do review the entry and reopen if you think it needs any changes.
