### ISSUE TITLE
PROPOSAL: Schools in Wales GB-WALEDU

### ISSUE THREAD

**Issue by drkane** [org-id/register#359]
## Proposal

**The name of the list, or the organization that manages the list**
Schools in Wales, maintained by Welsh Government

**A suggested code for the list [optional]**
GB-WALEDU

**A short description of the list**
A list of schools in Wales

**The country or countries that the list covers**
UK (Wales)

**The legal form or organizations that the list covers**
School

**Any specific sectors that the list covers**
Education

**A URL for information on the list, and a URL for looking up identifiers [if available]**
https://gov.wales/address-list-schools

**Any information on available open data copies of this list**
List available at the above URL. Assuming OGL as per rest of the 

**One or more examples of identifier from this list, and how you found them**
Ysgol Gynradd Amlwch - GB-WALEDU-6602130 - found in ODS spreadsheet download from link above.

**Comment by siwhitehouse** [comment]
Once again, apologies for the delay @drkane. I've merged the new list and it is visible at http://org-id.guide/list/GB-WALEDU

I'll close the issue with this, but please do review the entry and reopen if you think it needs any changes.
