### ISSUE TITLE
REQUEST: Organization in Senegal

### ISSUE THREAD

**Issue by PetyaKangalova** [org-id/register#36]
## Request

**What type of organization do you want identifiers for?** [Regional NGO]

**In which countries are the organizations you want identifiers for based?**: Senegal

**Do you have examples of organizations you need identifiers for?** [Panos Institute West Africa](http://www.panos-ao.org/en/index.php)

**Comment by timgdavies** [comment]
For organisations in Senegal, registration appears to take place via different ministries depending on the organisation type. I've not been able to locate any public lists from the ministries. 

However, it is possible that most organisations will have a tax identification number, the 'Numéro d'identification nationale des entreprises et des associations (NINEA)'

There does not appear to be a public list of these available either, but it does appear they are widely used. 

It would be worth asking Panos Institute West Africa if they have a NINEA - although their status may be special as they describe themselves as "registered in Senegal, where they enjoys a Headquarters Agreement with the state of Senegal."

Note also that 'Panos Institute' exists in the OECD DAC list as XM-DAC-21031, although it is not clear if this identifies 'The Panos Network' or a specific one of the Panos Institutes (see http://www.panos-ao.org/en/index.php?p=pages&page=apropos) and so is not an ideal identifier. 

In the absence of an identifier that clearly picks out the right legal entity, leaving identifiers blank, and including only the name is preferable. 

### Sources
* http://www.icnl.org/research/monitor/Senegal.html 
* http://www.doingbusiness.org/data/exploreeconomies/senegal/starting-a-business
* https://www.wikiprocedure.com/index.php/Senegal_-_Obtain_a_Tax_Identification_Number

**Comment by PetyaKangalova** [comment]
Many thanks. I have gone back to Panos Institute West Africa to see if they have a NINEA number and will update you once I hear back from them.

**Comment by PetyaKangalova** [comment]
I have now heard from the Panos Institute West Africa and they have provided me with their NINEA number.  I wasn't able to identify the code on org-id.guide for using the Numéro d'identification nationale des entreprises et des associations (NINEA) reference number in Senegal. Could this be added to the org-id list so that they can create their IATI organisation identifier?

Let me know if you need any additional information.

**Comment by PetyaKangalova** [comment]
@timgdavies Has there been any progress in researching this one and what the code will be in org-id? The Panos Institute West Africa identified their NINEA number and would like to publish soon.  Let me know if you need more information.

**Comment by PetyaKangalova** [comment]
@timgdavies  @BobHarper1  Any further research on this one? I would like to get back to PIWA this week confirming what code they should use with their NINEA number.  Many thanks.

**Comment by timgdavies** [comment]
@PetyaKangalova Sorry - I'd missed the alerts on this one. Will get back to you by the end of the week latest.

**Comment by BobHarper1** [comment]
NINEA was added as a list
