### ISSUE TITLE
Correction to GB-EDU

### ISSUE THREAD

**Issue by drkane** [org-id/register#360]
## Correction

The entry for [GB-EDU](https://github.com/org-id/register/blob/master/lists/gb/gb-edu.json) suggests that the list covers schools in England and Wales, which it previously did. But the list now only covers England according to [the source website](https://get-information-schools.service.gov.uk/).

Remove "GB-WLS" from `subnationalCoverage` and make amendments to text.

(Having said that, there are still entries for Welsh schools in the database, so I'm a bit confused... eg - https://get-information-schools.service.gov.uk/Establishments/Establishment/Details/400041)

**Comment by siwhitehouse** [comment]
Thanks for raising this issue David.
My assumption here is that the list that you are proposing in #359 is the canonical one as the devolved Welsh government have responsibility for education.
I've sent an email to Edubase

"The text on https://get-information-schools.service.gov.uk/ states that "This is a register of schools and colleges in England." but searching returns a list of schools in Wales as well.

Is this list or the one at https://gov.wales/address-list-schools the canonical source and do you expect to maintain a directory of Welsh schools in the future? "

Let's see what they come back with and I'll edit the entry accordingly.

**Comment by siwhitehouse** [comment]
I've had a response:

"The Welsh Government is the definitive source of information about schools in Wales."

**Comment by siwhitehouse** [comment]
Considering #362 and  #359 I think we will want to change the list code to something like GB-ENGEDU.  I'm not entirely certain how to make that change. I've assigned @kd-ods for advice on that. I'll also take a look through previous issues to see if this has been done before. I can't find anything in the [handbook](http://docs.org-id.guide/en/latest/). If it doesn't exist we should create some documentation for this.

**Comment by kd-ods** [comment]
@siwhitehouse - there's a ['Former list code' field](http://docs.org-id.guide/en/latest/schema/#schema-overview). "In some cases a list code may be changed. This field will list deprecated codes for this list."

Will that do?

**Comment by siwhitehouse** [comment]
@kd-ods at the moment the filename is gb-edu.json. 

So, one way of making the adjustment would be to set 
`"deprecated":true,`
in that file and then create a new file called gb-engedu.json that uses
`"formerPrefixes": [GB-EDU]`
There should also be some explanation in one of the text fields about what has changed.
If we do that then I think we should probably also add 
`"formerPrefixes": [GB-EDU]` to the new gb-waledu.json file that is in the pull request at #367 

Does that sound right to you?

**Comment by drkane** [comment]
Changing the prefix would have an impact on data already published by 360Giving publishers - we currently have around 668 grants (out of c330,000) that use "GB-EDU" as their prefix, of which 2 publishers account for 80% and another 9 publishers for the remaining 20%.

Obviously that's just from our perspective and I don't know if there would be an impact on other orgid users.

I'm also not sure what tooling already relies on the org-id list (for example when checking if a prefix is valid) and whether it takes into account the `formerPrefixes` field.

**Comment by KDuerden** [comment]
Why does the prefix actually need to be depreciated? Isn't it the prefix for that list and the IDs found on it? The IDs are still valid so isn't it just our understanding of the scope that needs changing.
As @drkane highlights, it would be disruptive to get data publishers to change (and unlikely to happen quickly). 

The change to the text to say it includes welsh schools wasn't made that long ago, and was triggered by me reporting a broken link: https://github.com/org-id/register/issues/157

**Comment by siwhitehouse** [comment]
Thanks @drkane and @KDuerden for pointing out the disruption that changing the org-id prefix would cause and my apologies for not considering this in my comment above. I'm inclined to agree that we don't change the prefix.

Putting that to one side. We do have the situation where there is a new registrar in Wales and they are taking over the responsibility for registering Welsh schools, where these had previously been done across England and Wales.

#367 establishes the list for Wales. It states that it should be preferred over GB-EDU when creating a unique identifier for Welsh schools and other education establishments.

So, publishers might now:

- keep using the old GB-EDU prefix for all Welsh schools
- keep using the old GB-EDU prefix for Welsh schools that are already in their data, but issue GB-WALEDU prefixes for 'new' schools
- keep using the old GB-EDU prefix for data published up until now and start using the GB-WALEDU prefix for new data publications from now on
- change all of the prefixes in their data to GB-WALEDU for Welsh schools that are already in their data and issue GB-WALEDU prefixes for 'new' schools

I'm sure there are other scenarios I haven't covered above. Publishers' decisions will also depend on the context in which data is being published. 

I've searched old issues and re-read the handbook, but I haven't found a previous example or documentation about how to handle splitting a register in two.

**Comment by KDuerden** [comment]
thanks @siwhitehouse 
It looks like only two publishers have used GB-EDU for welsh schools, so we can raise this new source of IDs with them when they next update.

**Comment by drkane** [comment]
Helpfully the Get Information About Schools service includes the "DfE number" which appears to correlate with the Welsh school number, so it should be relatively easy to move between the two if needed. Not sure how the two are kept in sync though.

Eg [GB-EDU-400188](https://get-information-schools.service.gov.uk/Establishments/Establishment/Details/400188#school-dashboard) - the DfE number shown is 661/3013 and the equivalent welsh record number is GB-WALEDU-6613013

**Comment by siwhitehouse** [comment]
@drkane My memory may be a bit faulty here, but I think the URNs were intended to replace DfE numbers, so I don't think people should rely on that link being maintained.

DfE number is 3 digits/4 digits with the first 3 digits equal to the local authority code and the last four digits uniquely identifying the school within that LA.

**Comment by siwhitehouse** [comment]
I've merged in the edits to this list and it is visible at http://org-id.guide/list/GB-EDU

I'll close the issue with this, but please do review the entry and reopen if you think it needs any changes.
