### ISSUE TITLE
PROPOSAL: Community Amateur Sports Clubs - GB-CASC

### ISSUE THREAD

**Issue by drkane** [org-id/register#361]
## Proposal

**The name of the list, or the organization that manages the list**
 Community amateur sports clubs (CASCs) registered with HMRC 

**A suggested code for the list [optional]**
GB-CASC

**A short description of the list**
A list of sport clubs registered with HMRC for tax purposes

**The country or countries that the list covers**
United Kingdom

**The legal form or organizations that the list covers**
Community Amateur Sports Club (CASC)

**Any specific sectors that the list covers**
Sports

**A URL for information on the list, and a URL for looking up identifiers [if available]**
https://www.gov.uk/government/publications/community-amateur-sports-clubs-casc-registered-with-hmrc--2

**Any information on available open data copies of this list**

**One or more examples of identifier from this list, and how you found them**
Unfortunately no identifiers are included in the data made available by HMRC

**Comment by kd-ods** [comment]
@drkane - As you say, no identifiers are included in the HMRC data, making this list of limited use. However, I have found references [here](https://www.gov.uk/government/publications/charities-detailed-guidance-notes/chapter-6-claims-and-returns) and [here](https://www.tax.service.gov.uk/shortforms/form/CHYCASC) to a 'unique charity reference number from HMRC' and 'If you are a Community Amateur Sports Club (CASC) your reference will start with a ‘CH’'.

I have found one example online of a 'CH'-prefixed reference ID: CH10135.

At this point, I am uncertain whether this list is suitable for addition to Org-ID at all given:

1. That these HMRC references are not widely shared or published online.
2. The scope of this HMRC list covering CASCs extends to cover all charities registered with HMRC as well.

@siwhitehouse - I'd be grateful for your thoughts on this too.

**Comment by drkane** [comment]
Thanks @kd-ods - I hadn't thought that the registration numbers might align with other HMRC ones. I wonder how much overlap there is with http://org-id.guide/list/GB-REV. Frustrating how impossible it is to get lists out of HMRC!

**Comment by kd-ods** [comment]
Ahhh - yes, @drkane - well spotted. I think expanding the scope of http://org-id.guide/list/GB-REV to include all Charity/CASC HMRC reference types would be the way to go on this.

Would appreciate @siwhitehouse your thoughts on whether amending this existing list is a good idea.

**Comment by KDuerden** [comment]
This is really interesting and useful! 
The GB-REV list has always been a bit difficult because none of the references from HMRC are officially listed anywhere, and so far FOI requests to publish this data have been refused citing privacy. 
You do see them on websites sometimes and some will provide them to funders as evidence of their charitable / tax exempt status but the picture is very patchy and not really something that can be independently verified, as far as I can tell. In current 360Giving data there are 17 funders using it for 94 recipients.

Returning to the CASCs case, @drkane has produced an ID which is a hash of the name and postcode: https://dev.findthatcharity.uk/orgid/type/Community%20Amateur%20Sports%20Club
We wanted to check what scope there is for this list to be classed as third-party one - like XI-PB for example? 360Giving could host the file on github and be responsible for the list.

**Comment by kd-ods** [comment]
@siwhitehouse and I have been talking about your Find that Charity CASC list, @drkane. 

One question for you, @drkane:

1) How do/will you handle the case of a sports club changing its name with HMRC?

**Comment by drkane** [comment]
@kd-ods - good question, without a good answer. This would result in a different ID being created, which is obviously not ideal.

The main reason for creating the ID in this way would just be that it gives something different to an ID that ends up like "GB-CASC-bowlington-bowls-club" but in practice it would be the same. It could be that manually maintaining the list is needed to look out for things like name changes (although I'm not sure anyone's got the time for manually maintaining it).

It's a sub-optimal solution compared to HMRC releasing the IDs, but it might be the best we can do at the moment.

**Comment by kd-ods** [comment]
Thanks @drkane. @siwhitehouse and I will think on this and get back to you.

**Comment by kd-ods** [comment]
@drkane @KDuerden - Having talked to Simon, we agree that this GB-CASC list should be be added to org-id as an interim solution. We'd ask, though, that at the point that HMRC publishes the charity and CASC reference IDs (if ever):

- you update the GB-CASC list to show the HMRC IDs alongside the CASC hash IDs,
- we effectively retire the GB-CASC list, pointing people to use of the HMRC identifiers instead.

Does that sound OK?

@KDuerden, you mentioned 360Giving hosting the GB-CASC list on a github repo. That sounds like a good idea. Agree, @drkane? Once it's in place, we can set up the org-id entry.

**Comment by drkane** [comment]
Hi @kd-ods - that sounds great to me. I'll put together the github repo soon.

Thanks again for your help.

**Comment by drkane** [comment]
GitHub repo is now here: https://github.com/ThreeSixtyGiving/cascs. Our `canonical` list would be https://github.com/ThreeSixtyGiving/cascs/blob/master/cascs.csv
