### ISSUE TITLE
PROPOSAL: Schools in Scotland - GB-SCOTEDU

### ISSUE THREAD

**Issue by drkane** [org-id/register#362]
## Proposal

**The name of the list, or the organization that manages the list**
Scottish Government - School Contact List

**A suggested code for the list [optional]**
GB-SCOTEDU

**A short description of the list**
List of schools in Scotland

**The country or countries that the list covers**
United Kingdom (Scotland only)

**The legal form or organizations that the list covers**
School

**Any specific sectors that the list covers**
Education

**A URL for information on the list, and a URL for looking up identifiers [if available]**
https://www2.gov.scot/Topics/Statistics/Browse/School-Education/Datasets/contactdetails

**Any information on available open data copies of this list**

**One or more examples of identifier from this list, and how you found them**
GB-SCOTEDU-5244439  Aberdeen Grammar School

**Comment by siwhitehouse** [comment]
Thanks for raising this David. I've sent an email to scotxed@gov.scot asking them how the SEED codes are composed.

I know that the old Edubase codes in England and Wales were of the form 'LLLSSSS' where 'LLL' was a code for the Local Authority and 'SSSS' was the code for the school within it. There were also rules for the composition of the schools part, so it was possible to identify primary and secondary schools, for instance.

I'll wait to see if I get an answer before raising a pull request to set this up.

**Comment by siwhitehouse** [comment]
I've received the following response "The structure of the code is that it is a numeric and 7 digits long."

**Comment by drkane** [comment]
Helpful! Looking at the data, it seems that the first 3 digits of the code is the same for schools in the same local authority, so it looks like the LLL part of the code still holds true.

**Comment by siwhitehouse** [comment]
I can see plenty of exceptions though. For example:

| Local Authority       | School Name           | Seed Code |
| ------------- | ------------- | ----- |
| Aberdeen City | Abbotswell | 5237521
| Aberdeen City | Aberdeen Grammar | 5244439

and there are instances where schools in different local authorities have the same 3-digit suffix. For example:

| Local Authority       | School Name           | Seed Code |
| ------------- | ------------- | ----- |
| Aberdeenshire | Elrick | 5233224
| Aberdeen City | Balgownie | 5234026

I'm inclined to write up the proposal without any comment about how the 7 digit coade are constructed.

**Comment by drkane** [comment]
Makes sense - I hadn't noticed that.

**Comment by siwhitehouse** [comment]
Once again, apologies for the delay @drkane. I've merged the new list and it is visible at http://org-id.guide/list/GB-SCOTEDU

I'll close the issue with this, but please do review the entry and reopen if you think it needs any changes.

**Comment by KDuerden** [comment]
I get 404 error from this link: http://org-id.guide/list/GB-SCOTEDU
Similarly, I can see the new schools lists via this view but both Wales & Scottish records give 404: http://org-id.guide/results?structure=all&coverage=all&sector=education

**Comment by siwhitehouse** [comment]
I've seen this behaviour on other new lists before. I'm going to raise a separate issue for it, citing this as an example.

Thanks for picking this up, @KDuerden

**Comment by drkane** [comment]
@siwhitehouse @kd-ods - thanks for getting all these lists up (weird 404 error notwithstanding!), really appreciate your help.
