### ISSUE TITLE
PROPOSAL: new list PSB for China

### ISSUE THREAD

**Issue by theaschepers** [org-id/register#363]
## Proposal

**Public Security Bureau**

**PSB**

**Quote received from our colleagues at Plan International China: "The Overseas NGO Management Law became effective in China since January 2017. Main step involved for getting an organization registered under the new law is to identify an appropriate Professional Supervision Unit (PSU) whose area of work is relevant to INGOs’ key area of interventions and the PSU’s willingness to take on the responsibility for becoming that INGOs’ supervisory agency (PSU). Once such an approval is obtained, then INGOs can get their registration done with the Public Security Bureau (PSB)." I have understood that every NGO has to have their registration checked and reconfirmed every year**

**China**

**INGOs**

**Any specific sectors that the list covers**

**A URL for information on the list, and a URL for looking up identifiers (if available)**

**Any information on available open data copies of this list**

**Plan International China uses this ID: "统一社会信用代码：G1610000713522976L". The Chinese part translates to Unified Social Credit Code. Another number that appears often is 00004203 and it's not entirely clear to me which one is the best one to use, and which one refers to the PSB. I'm attaching two documents as examples, and the english text of the law from 2017. I will ask for clarification about these IDs as soon as the China office opens again.
[Overseas NGO Management Law.pdf](https://github.com/org-id/register/files/3686116/Overseas.NGO.Management.Law.pdf)
![Plan CHN registration](https://user-images.githubusercontent.com/56119194/66128276-d1b7bc00-e5ed-11e9-8285-c5f0809acc12.jpg)
![Plan CHN annual check-2019](https://user-images.githubusercontent.com/56119194/66128283-d41a1600-e5ed-11e9-99fc-3615085f26f5.jpg)
**

**Comment by theaschepers** [comment]
Apologies everyone. I have no idea how Github works, I hope the post makes sense.

**Comment by siwhitehouse** [comment]
Hi Thea

Thanks for posting this proposal. From your comments above and the document you've linked to it looks like the Public Security Bureau in China is the registrar for International Non-Government Organisations who are already established outside China and so they are not their primary registrar.

Looking at the [second document](https://user-images.githubusercontent.com/56119194/66128283-d41a1600-e5ed-11e9-99fc-3615085f26f5.jpg) I can see that each year a stamp is added to the certificate. So, the identifiers on the document don't change over time.

If you can find out what those two identifiers are that will help us to look at setting the list up. Also, do you know if there is a list of registered NGOs available online, or offline if not, please?

Oh, and no need to apologise, you've raised a decent looking proposal in the right place. Thank you.

**Comment by theaschepers** [comment]
Hi Simon, thanks very much. I see I didn't quite get the formatting right, but I'm glad it made sense.
I've asked our colleagues in China. I don't think there is much hope for an online source but we'll give it a shot. I have also asked where national NGOs are registered, if anywhere. Will report back when I hear from them.

**Comment by theaschepers** [comment]
Some info from our office in China: 

- the long ID starting with G is the correct one. It's called the 'unified social credit number'. The shorter number is an ID for a certificate.
- there’s an online service platform for overseas NGO, anyone can check the list through this platform(Chinese version only), the website is :
http://ngo.mps.gov.cn/ngo/portal/toInfogs.do
- national NGOs could register under ministry of civil affairs or local level government, and there’s an online service platform for national NGOs/NPOs, here’s the website:
http://www.chinanpo.gov.cn/index.html. This should become a separate list.
- anyone can check relevant information through below link:
http://www.chinanpo.gov.cn/search/orgindex.html 

I don't know what the last link is exactly, it's in Chinese. I hope this helps though.
