### ISSUE TITLE
PROPOSAL: new list RNGO for Zambia

### ISSUE THREAD

**Issue by theaschepers** [org-id/register#368]
## Proposal

**The name of the list (or the organization that manages the list)**
Department of Registrar for NGOs (part of the Ministry of Community Development and Social Services)

**A suggested code for the list (optional)**
RNGO (this code is part of the ID already)

**A short description of the list**
All NGOs in Zambia need to be registered here to be allowed to operate. 

**The country or countries that the list covers**
Zambia

**The legal form or organizations that the list covers**
NGOs. 

**Any specific sectors that the list covers**
Only NGOs, including INGOs. Commercial sector is covered by the existing list of Patents and Companies Registration Agency (PACRA) but NGOs don't seem to be included in that list so this list is a necessary addition. 

**A URL for information on the list, and a URL for looking up identifiers (if available)**
Info: https://www.mcdsw.gov.zm/?page_id=5232
No online list

**Any information on available open data copies of this list**
None

**One or more examples of identifier from this list, and how you found them**
Plan International Zambia: RNGO/101/0147/2014 (provided by the organisation, 
[NGOCERTIFICATE.pdf](https://github.com/org-id/register/files/3701681/NGOCERTIFICATE.pdf)
see attachment)

**Comment by siwhitehouse** [comment]
Thank you for raising this proposal Thea. Do you know how the identifier is constructed, please?

I assume that the 2014 at the end represents the first year that Plan International were registered as an international NGO. This is helpful as it means that identifiers appear to be stable. Have you any ide what the " ..... /101/0147/....." in the middle represents?

**Comment by theaschepers** [comment]
Hi Simon, I have no idea, sorry... I have the same assumption about the year but the rest is unclear to me. I can ask, but I'm not sure if anyone is able to clarify.

**Comment by theaschepers** [comment]
I had another look at the certificate just now, and it looks like 2014 might be the date of the certificate, valid for 5 years, so probably to be renewed soon. Plan has been active in Zambia much longer than since 2014 so that would make sense. First certificate probably was valid from 2009 when the law was implemented (according to the document), and 2014 was the second one.
