### ISSUE TITLE
PROPOSAL: GT-CUI -- Código Único de Identificación de personas de Guatemala

### ISSUE THREAD

**Issue by juanpane** [org-id/register#378]
## Proposal

**The name of the list, or the organization that manages the list**
Código Único de Identificación de personas de Guatemala

**A suggested code for the list [optional]**
GT-CUI

**A short description of the list**
[ES]
El Código Único de Identificación (CUI) de personas de Guatemala es mantenido por el Registro Nacional de las personas de Guatemala (https://www.renap.gob.gt/)

En el artículo 4 de la Ley del Registro Nacional de las Personas de Guatemala quedó establecido que el Código Único de Identificación –CUI- se le asignará a todas las personas desde la inscripción de su nacimiento y permanecerá invariable hasta su muerte.

El CUI está compuesto por 13 dígitos, los últimos cuatro corresponden a dos dígitos de identificación del departamento de su nacimiento y dos dígitos de identificación del municipio de su nacimiento.

En el artículo 61 de la ley en mención, se establece que desde el 1 de enero del año 2017, el CUI sustituye los números que están en los registros públicos de todos los sistemas de identificación.

[EN]

The Unique Identification code for people in Guatemala is maintained by the National Registry of people (https://www.renap.gob.gt/)

Article 4 of the Law of the National Registry of Persons of Guatemala defines the Unique Identification Code - CUI - that is  assigned to all persons from the time of their birth registration and will remain unchanged until their death.

The CUI is composed of 13 digits, the last four correspond to two digits of identification of the department of his birth and two digits of identification of the municipality of his birth.

Article 61 of the law establishes that since January 1, 2017, the CUI replaces the numbers that are in the public records of all identification systems in Guatemala.

**The country or countries that the list covers**
Guatemala

**The legal form or organizations that the list covers**
All the citizens from Guatemala

**Any specific sectors that the list covers**
Citizens

**A URL for information on the list, and a URL for looking up identifiers [if available]**
Information: https://www.renap.gob.gt/noticias/que-es-el-cui
Lookup: https://portal.sat.gob.gt/portal/consulta-cui-nit/

**Any information on available open data copies of this list**
N/A
**One or more examples of identifier from this list, and how you found them**
As from Guatecompras, the national procurement system from Guatemala, we have these examples:

CUI| Name
------------ | -------------		 
1924118530114 | Ader Augusto Guerra Lezana
2157888770101 | Luis Estuardo Solis Lezzana
2253760670114 | Claudia Marisol Lezana Perez

**Comment by duncandewhurst** [comment]
Per https://github.com/org-id/register/issues/379#issuecomment-548191210 these appear to be personal identifiers and are therefore out of scope of org-id. Please refer to the guidance in that comment for how to create scheme code.
