### ISSUE TITLE
PROPOSAL: [CL-MercadoPublico]

### ISSUE THREAD

**Issue by nenita05leyla** [org-id/register#380]
## Proposal

**The name of the list, or the organization that manages the list**
**Name List:** CL-MercadoPublico
**Manager Organization:** Dirección de Compras y Contratación Pública 

**A short description of the list**
**Description:** Public Buyer Units of Chile. 

**The country or countries that the list covers:**
**Countries:** Chile

**The legal form or organizations that the list covers:**
Public Buyer Units of Chile. 

**Any specific sectors that the list covers**
Govermment

**A URL for information on the list, and a URL for looking up identifiers [if available]**
**URL example:** http://apipre.mercadopublico.cl/APISOCDS/Comprador/Unidad/2544

**Any information on available open data copies of this list**
http://datosabiertos.chilecompra.cl/Home/OrganismoComprador

**One or more examples of identifier from this list, and how you found them**
http://apipre.mercadopublico.cl/APISOCDS/ocds/tender/1548-28-LE16
{
"name": "Hospital Santa Barbara | Hospital Santa Barbara",
"id": "61.607.304-4",
"identifier": {
"id": "2544",
"legalName": "Hospital Santa Barbara",
"scheme": "CL-MercadoPublico",
"uri": "http://apipre.mercadopublico.cl/APISOCDS/Comprador/Unidad/2544"
}

**Comment by duncandewhurst** [comment]
@nenita05leyla thanks for this proposal.

To help me understand the source of this request, please could you confirm whether you are working with the publisher (ChileCompra) or whether you are a user of the Mercardo Publico OCDS API?

Some more information is required before this code can be added to org-id.guide, please can you:

1. Confirm you are happy with the proposed code for the list: `CL-MP`. This will need updating in the Mercado Publico OCDS API.

2. Confirm you are happy with the proposed name for the list: ES: Unidad Comprador Mercado Público, Chile | EN: Public Market Buyer Units, Chile.

3. Confirm you are happy with proposed description for this list:

> Mercado Público is an electronic platform managed by Chilecompra, part of the Ministry of Finance, where public organizations make purchases.
> 
> Units of public entities registered as buyers on Mercado Público are assigned an identifier in the system. This identifier is used in the data from the Mercado Público OCDS API.
> 
> The use of Mercado Público buyer unit identifiers is considered a temporary measure. They should only be used when no other stable identifier for a government agency is available

4. Describe how organizations on this list are assigned an identifier.

5. Confirm whether these identifiers are either:
  a. Internal to Mercado Publico (i.e. they are not used in any other datasets, other than the Mercado Publico OCDS API); or
  b. Used in other systems or datasets (please provide examples)

6. Confirm whether it is possible to download a list of all identifiers in the list and provide a download link if so

cc @yolile @romifz for awareness and in case you can help with any of the above questions

**Comment by yolile** [comment]
@duncandewhurst 

> To help me understand the source of this request, please could you confirm whether you are working with the publisher (ChileCompra) or whether you are a user of the Mercardo Publico OCDS API?

She is working with the publisher

> Confirm you are happy with the proposed code for the list: CL-MP. This will need updating in the Mercado Publico OCDS API.

Yes, they are already using that code, eg https://apis.mercadopublico.cl/OCDS/data/award/1395-107-LP19

> Describe how organizations on this list are assigned an identifier.

The suppliers must register themself in:
http://www.mercadopublico.cl/Home/Autenticacion?esNuevaHome=true&_ga=2.149382326.1266329389.1594135793-177513299.1588687860 if they want to bid

> Confirm whether it is possible to download a list of all identifiers in the list and provide a download link if so

There is only an endpoint to get a supplier data by its code:
https://desarrolladores.mercadopublico.cl/docs/services/5a9ed02f718ed712f4403e75/operations/5d0bda438c3b1ec42b59566b?
that is used by OCDS eg in https://apis.mercadopublico.cl/OCDS/data/award/1395-107-LP19,  https://apis.mercadopublico.cl/OCDS/data/comprador/unidad/2391

**Comment by duncandewhurst** [comment]
Thanks @yolile. The original proposal was about buyer identifiers (the `/comprador/` endpoint) so I wasn't aware that the list also covered suppliers.

Is there one combined list for both buyers and suppliers? Or do the `/comprador/` and `/proveedor/` endpoints refer to different lists?

**Comment by yolile** [comment]
> Is there one combined list for both buyers and suppliers? Or do the /comprador/ and /proveedor/ endpoints refer to different lists?

No, there is not a combined one. But they are using the CL-MP code for both, suppliers and buyers

**Comment by duncandewhurst** [comment]
Thanks @yolile 

In that case, how would a user know which endpoint to look up the identifier in?

Also, can the same identifier appear in both lists?

**Comment by yolile** [comment]
> In that case, how would a user know which endpoint to look up the identifier in?

In OCDS Chile Compra includes the URI for each party, too, but maybe the users can also distinguish them with the numbers range used, as buyers seem to have lower numbers than suppliers. I checked this and in `/comprador/` endpoint the numbers from 1000 to 6600 are for buyers and from 6601 onwards are for suppliers, so

> Is there one combined list for both buyers and suppliers? Or do the /comprador/ and /proveedor/ endpoints refer to different lists?

Yes, it seems like the `/comprador/` endpoint is the completest one (buyers + suppliers), and the `/proveedor/` one is just for suppliers
