### ISSUE TITLE
PROPOSAL: Research Organization Registry: XI-ROR

### ISSUE THREAD

**Issue by KDuerden** [org-id/register#384]
## Proposal

**The name of the list, or the organization that manages the list**
Research Organization Registry
https://ror.community/

**A suggested code for the list [optional]**
XI-ROR

**A short description of the list**
A community-led project to develop an open, sustainable, usable, and unique identifier for every research organization in the world.

**The country or countries that the list covers**
Global

**The legal form or organizations that the list covers**
“Research organization” is defined as any organization that conducts, produces, manages, or touches research.  The list includes universities and other education establishments, companies, healthcare, non-profits, government and a range of other entity types.

**Any specific sectors that the list covers**
Research and education

**A URL for information on the list, and a URL for looking up identifiers [if available]**
Further details about the list: https://ror.org/
Online search: https://ror.org/search

**Any information on available open data copies of this list**
Data can be downloaded via https://github.com/ror-community/ror-api
All ROR IDs and metadata are provided under the Creative Commons Public Domain 1.0 International Licence.

**One or more examples of identifier from this list, and how you found them**
Searched via https://ror.org/search
Gatsby Charitable Foundation: https://ror.org/0290hax27
Wellcome Trust: https://ror.org/029chgv08
Queen’s University Belfast: https://ror.org/00hswnk62

**Comment by mariagould** [comment]
Thanks so much for opening this! One quick change to the details above: the ROR website is https://ror.org. The URL ror.community is outdated and will be redirected to ror.org soon.

**Comment by siwhitehouse** [comment]
myself and @mrshll1001 took a look at this yesterday. The Research Organization Registry creates unique identifiers and clearly state this on their site. The identifiers also look stable and the database was seeded from GRID, which is already listed on org-id.

**Comment by stevieflow** [comment]
Discussed on call with @siwhitehouse @mrshll1001 & @KDuerden 29 April 2020

We agreed to include this on org-id. No other queries.

One query - which doesn't affect the inclusion, but would help for clarification guidance to users - is whether entries on ROR would be either/both university institutions and specific departments/facility.  @KDuerden to discuss with @mariagould

**Comment by mariagould** [comment]
Glad to see this progressing. To clarify the scope/hierarchy question posed here: ROR is meant to focus on top-level affiliations. It is by design not focused on identifying all individual departments within a university, for instance. That being said, there are use cases for separate research facilities/institutes within/associated with universities, for instance, and ROR does have entries for these if they are considered distinct affiliations. 

I hope this helps.

**Comment by siwhitehouse** [comment]
This was implemented by #397
