### ISSUE TITLE
PROPOSAL: Brazilian National Registry of Legal Entities (BR-CNPJ)

### ISSUE THREAD

**Issue by Inova-MPRJ** [org-id/register#393]
## Proposal

**The name of the list, or the organization that manages the list**
Cadastro Nacional da Pessoa Jurídica (National Registry of Legal Entities)
Receita Federal do Brasil: http://receita.economia.gov.br/orientacao/tributaria/cadastros/cadastro-nacional-de-pessoas-juridicas-cnpj

**A suggested code for the list [optional]**
BR-CNPJ

**A short description of the list**
CNPJ is an identification number issued to Brazilian companies by the Department of Federal Revenue of Brazil. The CNPJ consists of a 14-digit number formatted as 00.000.000/0001-00 — The first eight digits identify the company, the four digits after the slash identify the branch or subsidiary ("0001" defaults to the headquarters), and the last two are check digits. (From [Wikipedia](https://en.wikipedia.org/wiki/CNPJ))

**The country or countries that the list covers**
Brazil

**The legal form or organizations that the list covers**
All sorts of legal entities in Brazil (public, for-profits and non-profits).

**Any specific sectors that the list covers**
All sectors.

**A URL for information on the list, and a URL for looking up identifiers [if available]**
[Schema](http://receita.economia.gov.br/orientacao/tributaria/cadastros/cadastro-nacional-de-pessoas-juridicas-cnpj/dados-publicos-cnpj#parent-fieldname-text).
[Registry status codelist](http://receita.economia.gov.br/orientacao/tributaria/cadastros/cadastro-nacional-de-pessoas-juridicas-cnpj/DominiosMotivoSituaoCadastral.csv).
[Associate/representative codelist](http://receita.economia.gov.br/orientacao/tributaria/cadastros/cadastro-nacional-de-pessoas-juridicas-cnpj/DominiosMotivoSituaoCadastral.csv)
URL for looking up identifiers: http://servicos.receita.fazenda.gov.br/Servicos/cnpjreva/Cnpjreva_Solicitacao.asp (*Captcha protected*)

**Any information on available open data copies of this list**
Raw data [here](http://receita.economia.gov.br/orientacao/tributaria/cadastros/cadastro-nacional-de-pessoas-juridicas-cnpj/dados-publicos-cnpj#parent-fieldname-text). R implementation [here](https://github.com/georgevbsantiago/qsacnpj); Python implementations [here](https://github.com/fabioserpa/CNPJ-full) and [here](https://github.com/turicas/socios-brasil) (all three documented in Portuguese).

**One or more examples of identifier from this list, and how you found them**
Ministério Público do Estado do Rio de Janeiro: **BR-CNPJ-28.305.936/0001-40** (found [here](http://www.mprj.mp.br/#footer))

**Comment by Inova-MPRJ** [comment]
Duplicate of [Issue #365 ](https://github.com/org-id/register/issues/365)

**Comment by augusto-herrmann** [comment]
It's not a duplicate. [BR-CNPJ](https://org-id.guide/list/BR-CNPJ) points to the cpnj.info website, which is a __third party__ site, but it wrongly attributed as a __primary__ source.

Conversely, on this issue here, all the information above point to the official source.

Sure, it's easier to use than the primary source, but there are other third party sites that are easier to use as well. For example [Brasil.io](https://brasil.io/dataset/socios-brasil/empresas/), [Base dos Dados Mais](https://basedosdados.github.io/mais/), etc.

Or should I open another issue for that?

**Comment by augusto-herrmann** [comment]
I've opened PR #488 for that.
