### ISSUE TITLE
UPDATE

### ISSUE THREAD

**Issue by TrudyJOA** [org-id/register#399]
#285  Correction

I work for Jersey Overseas Aid, a Jersey Governemnet aid donor and we would like to publish our data to IATI, we previously had a code but it was withdrawn but no one in JOA knows how this was set up or indeed how it was withdrawn.

Is it possible to reinstate please?

Thanks for any help.

Kind regards
TRudy

**Comment by kd-ods** [comment]
Hello @TrudyJOA,  I can see an old issue relating to your organisation here #250. I think you need to contact the IATI helpdesk about this and see if an XI-IATI code or similar was forged for you in the past: https://iatistandard.org/en/guidance/get-support/

**Comment by siwhitehouse** [comment]
Closing issue with the advice given to @TrudyJOA
