### ISSUE TITLE
REQUEST: Turkey's Department of Organisation Management

### ISSUE THREAD

**Issue by amy-silcock** [org-id/register#40]
<!-- You have an organization/organization to identify. You%--!>

"In Turkey we are registered under Turkish governmental department called " il dernekler Muduru" in English "Department of Organization Management" it's the department responsible for all the registration of the organizations in Turkey."
<p>
<p>
Example of a registered organisation:<p>
Name: Local Development and Small Projects Support (LDSPS) <p>
Website: www.ldspd.org <p>
Registration Number: 27-018-163 <p>
Contact: bakri.azzin@ldsps.org<p>

**Comment by amy-silcock** [comment]
here is the website of the Department: https://www.dernekler.gov.tr/en/default.aspx 
also please note: that the name of LDSPS in the registration is "YEREL KALKINMA VE KÜÇÜK ISLETMELERE DESTRK YARDIMLASMA VE DAYANISMA DERN" which the translation of "local Development and small projects Support" into the Turkish language.

**Comment by timgdavies** [comment]
The Turkish Ministry of Interior have the 'Department of Associations' which registers:

* [Associations](https://www.dernekler.gov.tr/tr/Anasayfalinkler/Dernek_kurulusu_icin_gerekli_belgeler.aspx)
* Political parties
* Unions

I've not been able to identify whether or not there could be clashes between identifiers issues to associations, political parties and unions, so I will create a proposed code for:

- 'TR-MOI' (Ministry of Interior) 

to cover **only associations** for the time being, with the potential to extend this to cover other kinds of entities registered with Ministry of Interior departments, assuming we do not later discover potential clashing identifiers.

Although the website suggests that it may be possible to search registered organisation information, I've not been able to locate comprehensive search tools that expose identifiers.
