### ISSUE TITLE
PROPOSAL: Bolivia Identify Tax Number BO-NIT

### ISSUE THREAD

**Issue by yolile** [org-id/register#402]
## Proposal

**The name of the list, or the organization that manages the list**

Número de Identificación Tributaria managed by the Administración Tributaria Nacional de Bolivia

**A suggested code for the list [optional]**

BO-NIT

**A short description of the list**

The NIT or Identify Tax Number is the number assigned by the Tax Administration to a natural person, a legal entity at the time of registration for any economic activity, by virtue of which they are taxable persons of some of the taxes established by Law.
https://impuestos.com.bo/rnd-03-13/

**The country or countries that the list covers**
Bolivia

**The legal form or organizations that the list covers**

(a) For natural persons, owners of sole proprietorships and undivided successions, the number of identity card plus control codes assigned by the Tax Administration.

(b) For legal persons, foreigners, natural persons with RUN and owners of sole proprietorships with RUN, by a number and control codes granted by the Tax Administration.

https://impuestos.com.bo/rnd-03-13/

**Any specific sectors that the list covers**

**A URL for information on the list, and a URL for looking up identifiers [if available]**

https://impuestos.com.bo/rnd-03-13/

**Any information on available open data copies of this list**

**One or more examples of identifier from this list, and how you found them**

1003579028  Servicio de Impuestos Nacionales

https://www.impuestos.gob.bo/page/262

OCDS related

**Comment by kd-ods** [comment]
Thanks, @yolile. Have you sent a related query to the OCDS helpdesk?

(I've assigned this proposal to @mrshll1001 who works on the helpdesk.)

**Comment by mrshll1001** [comment]
Cheers @kd-ods and @yolile for the detailed request I've started researching this

**Comment by mrshll1001** [comment]
Hey @yolile, I'm trying to navigate the https://www.impuestos.gob.bo site to find more identifiers. How do I find a list of them? Your example https://www.impuestos.gob.bo/page/262 1003579028 Servicio de Impuestos Nacionales is for the Tax Service which doesn't sound like a taxable person.

Adjacent pages https://www.impuestos.gob.bo/page/261 and https://www.impuestos.gob.bo/page/263 appear to be unrelated so I'm not sure where I'm supposed to be looking for NIT identifers?

**Comment by yolile** [comment]
@mrshll1001 I couldn't find an official NIT list, but here are more examples: https://www.senapi.gob.bo/contrataciones/nomina-de-proveedores

**Comment by mrshll1001** [comment]
That's great thanks @yolile.

There are some cases where the SIN is missing `No registra` in [this file](https://www.senapi.gob.bo/sites/default/files/senapi/media/20190614192103-nomina-de-proveedores-2019.pdf). What occurs during these cases?

Also this looks to be a list of suppliers by year with their SINs but I think what we're looking for is a link to where the SINS may be available. Is there a look-up or portal to look up suppliers by their SIN? Similar to the BO-CINS list in #404 ?

**Comment by mrshll1001** [comment]
I've raised a PR for this.

**Comment by mrshll1001** [comment]
The PR has been merged now :-)
