### ISSUE TITLE
PROPOSAL: Bolivia Clasificador Institucional BO-CI

### ISSUE THREAD

**Issue by yolile** [org-id/register#403]
## Proposal

**The name of the list, or the organization that manages the list**

Clasificador Institucional managed by the Ministerio de Economía y Finanzas de Bolivia

**A suggested code for the list [optional]**

BO-CI

**A short description of the list**
The institutional classifier reflects the organizational structure of the public sector, taking into account the legal nature, institutional level and entity (code, name and acronym), for the administration of State resources, according to competencies in current regulations.
https://medios.economiayfinanzas.gob.bo/MH/documentos/DC_interes/2018/CLASIFICADORES_2019.pdf

**The country or countries that the list covers**
Bolivia

**The legal form or organizations that the list covers**
Public entities

**Any specific sectors that the list covers**
Public sector

**A URL for information on the list, and a URL for looking up identifiers [if available]**

https://www.sicoes.gob.bo/portal/clasificadores/institucional.php
https://medios.economiayfinanzas.gob.bo/MH/documentos/DC_interes/2018/CLASIFICADORES_2019.pdf

**Any information on available open data copies of this list**
https://www.sicoes.gob.bo/portal/clasificadores/institucional.php

**One or more examples of identifier from this list, and how you found them**

0065-10 | Viceministerio De Inversion Publica Y Financiamiento Externo - Vipfe
0359-00 | Prefectura Del Departamento De Pando
https://www.sicoes.gob.bo/portal/clasificadores/institucional.php

OCDS related

**Comment by mrshll1001** [comment]
Cheers @yolile I've started the research for this

**Comment by yolile** [comment]
I suggested the use of "BO-CI" as the scheme code but the Bolivian folks say that in Bolivia "CI" is short for "Cédula de Identidad", another identifier, so we should think in a best name.

**Comment by mrshll1001** [comment]
I've had a look through this and I think this is a strong candidate for inclusion as it's clear the identifiers are taken from an official list.

Re the name; would "BO-CINS" make sense? where the INS portion is short for Institucional?

**Comment by yolile** [comment]
@mrshll1001 yes, it makes sense!

**Comment by mrshll1001** [comment]
@yolile great :-) I'll get to adding this to the site

**Comment by mrshll1001** [comment]
I've raised a PR in #404

**Comment by mrshll1001** [comment]
#404 has been merged now :-)
