### ISSUE TITLE
Bolivian lists not viewable on front end

### ISSUE THREAD

**Issue by kd-ods** [org-id/register#414]
When using the dropdowns to select [all Bolivian lists](http://org-id.guide/results?structure=all&coverage=BO&sector=all), a 500 Server error results.

This problem is possibly because the [BO-CR list isn't validating](https://org-id-register.netlify.app/type/lists/record/bo-cr/) and generates a 404 error when trying to retrieve it at http://org-id.guide/list/BO-CR. The **other** Bolivian list is retrievable directly at http://org-id.guide/list/BO-NIT.

**Comment by odscjames** [comment]
When looking at the list page, the error that comes up is:

     KeyError: 'subnationalCoverage'

From prefix_finder/frontend/views.py in filter_and_score_results at line 260

**Comment by odscjames** [comment]
The fix is now live
