### ISSUE TITLE
REQUEST: Swedish Tax Department

### ISSUE THREAD

**Issue by amy-silcock** [org-id/register#42]
Hi,

The organisation International IDEA is based in Sweden but their organisation number comes from the Swedish Tax department.

Please could you look into creating a code for Swedish Tax Department.

Tim - I am copying you into the zendesk ticket we have so that you can see the current discussion and get in contact with Gideon Nhundu (G.Nhundu@idea.int) who is our contact there.

Thanks, Amy

**Comment by timgdavies** [comment]
IDEA are an international organisation, and listed in the XM-DAC list as XM-DAC-47058

As I understand, any tax department identifier would be a secondary identifier, and so would not be preferred over the XM-DAC code. 

From the initial research I've done, and the suggestion from IDEA, Swedish Tax Office numbers may not be public identifiers, so I'd suggest no further research on this unless there is a case where we have other Sweden registered organisations who do not have local company numbers etc.
