### ISSUE TITLE
PROPOSAL:  Austrian Central Register of Associations AT-ZVR

### ISSUE THREAD

**Issue by amy-silcock** [org-id/register#429]
## Proposal

**The name of the list, or the organization that manages the list**
Austrian Central Register of Associations (ZVR)

**A suggested code for the list [optional]**
AT-ZVR

**A short description of the list**
The Federal Ministry of the Interior maintains the Central Register of Associations (ZVR). This contains details and the ID for each registered association in Austria.

**The country or countries that the list covers**
Austria

**The legal form or organizations that the list covers**
Associations in Austria

**A URL for information on the list, and a URL for looking up identifiers [if available]**
https://citizen.bmi.gv.at/at.gv.bmi.fnsweb-p/zvn/public/Registerauszug

**One or more examples of identifier from this list, and how you found them**
Light for the World International. They provided the link to the look up and their ZVR number: ZVR-315688676

Searching by their ZVR number brings up their organisation details.

Suggested Full org id: AT-ZVR-315688676

**Comment by PetyaKangalova** [comment]
Hi ORG-ID team :) I wondered if the information provided above by Amy is sufficient to add to your list. Do let us know as we are working closely with the organisation in setting their account. As the Registration Agency has a public record, I am willing to allow them to start using it so that they can publish to IATI within their planned timeframe.

Happy to support with setting this up if you need any additional information.

**Comment by kd-ods** [comment]
@PetyaKangalova @amy-silcock - Hi both. As you know we're not researching lists and adding them unless we have a specific arrangements with a project at the moment. I'll DM you with an idea about you doing the research and submitting a pull request directly.

**Comment by stevieflow** [comment]
@amy-silcock my German isn't good enough (maybe @markbrough can help?) but did you find any English language pages / text?

**Comment by markbrough** [comment]
From a quick look around the Interior Ministry's website, there doesn't appear to be any English language version available. I am happy to help with translation, but from a quick look at the ZVR website, the information Amy added looks correct to me!

**Comment by amy-silcock** [comment]
@stevieflow I just google translate the page. Thanks for the confirmation @markbrough! 👍

**Comment by kd-ods** [comment]
See http://org-id.guide/list/AT-ZVR for published list. (Do a hard reload of the webpage if you get a 404 errror: CTRL + F5 or equivalent.)
