### ISSUE TITLE
REQUEST: Agência de Desenvolvimento do Vale do Zambeze - Mozambique

### ISSUE THREAD

**Issue by amy-silcock** [org-id/register#43]
Hi Tim,

The Agência de Desenvolvimento do Vale do Zambeze is a government Agency in Mozambique. Please can you start the process of setting up a government IATI org ID code for them.

Website: http://www.agenciadozambeze.gov.mz/

Our contacts:
- rmendiate@gmail.com
- joepvonk@gmail.com

The information I have so far is:
"The Agência do Zambeze is a public-sector agency under the Ministry of Economics and Finance. The mission of the Agência do Zambeze, which was established in 2010, is to promote the socio-economic and sustainable development of the Lower Zambezi River Basin. This Basin comprises 34 districts in four provinces: Manica, Sofala, Tete and Zambezi. In addition to these districts the Agency’s geographical remit also comprise 6 districts that fall outside the River Basin area."

**Comment by timgdavies** [comment]
Exploring the government portal for Mozambique (http://www.portaldogoverno.gov.mz/) I've not located stable identifiers for departments or agencies.

Whilst [investigative dashboard](https://investigativedashboard.org/databases/countries/MZ) suggests there may be a company register available, the link is dead and this appears to no longer be available online. 

Agência do Zambeze are not included in the XM-OCHA or XM-DAC fallback lists, nor currently in XI-IATI, nor in Wikipedia, though it might be most appropriate at the present time to provide an entry in XI-IATI, unless some other list they appear in can be identified.

**Comment by BobHarper1** [comment]
I trust this has been resolved through https://github.com/org-id/register/issues/129 as another state-owned enterprise did have a Tax Identifier Code ([NUIT](http://org-id.guide/list/MZ-NUIT))
