### ISSUE TITLE
PROPOSAL: New list BI-NIF code verification

### ISSUE THREAD

**Issue by andreaszenasidi** [org-id/register#437]
## Proposal

I am reaching out to verify that the **BDI-NIF** code is the correct one to use for companies in Burundi. An IATI publisher needs to use this code as soon as possible. I will prepare and submit the new list to org-id shortly.

**The name of the list (or the organization that manages the list)**
Office Burundais des Recettes

**A suggested code for the list (optional)**
BDI-NIF

**A short description of the list**
The Tax Identification Number (Numero d’Identification Fiscale) is issued to registered companies operating in Burundi. There is publicly available register of assigned Tax Identification Numbers.

**The country or countries that the list covers**
Burundi

**A URL for information on the list, and a URL for looking up identifiers (if available)**
https://www.obr.bi/index.php/en/
https://www.obr.bi/index.php/en/verification-de-validite-de-documents?option=com_odvc&view=odvc&id=1&type_doc=4

@theaschepers This list is for _Auxfin Burundi_, they recieved funds from the Dutch Ministry of Foreign Affairs.

**Comment by kd-ods** [comment]
Hi @andreaszenasidi. You should use the two character iso 3166 (alpha-2) country code for Burundi which is BI. So the list code will be BI-NIF.

(You can search directly for country codes on the ISO site: https://www.iso.org/obp/ui/#home)

**Comment by andreaszenasidi** [comment]
@kd-ods thank you for your fast answer! I will let the publisher knwo they can use **BI-NIF**

**Comment by andreaszenasidi** [comment]
@kd-ods I created a new [pull request](https://github.com/org-id/register/pull/438) for the new bi-nif.json orgid. Please reach out if changes are needed. Thank you!

**Comment by kd-ods** [comment]
List now available at: http://org-id.guide/list/BI-NIF
