### ISSUE TITLE
REQUEST: YMCA Liberia

### ISSUE THREAD

**Issue by amy-silcock** [org-id/register#44]
Hi Tim,

YMCA Liberia are needing an organisation identifier. The information I currently have is:

- They are currently registered with the Ministry of Planning and Economic Affairs (MPEA), and their registration code is: MPEA/NGO/AC#0298.

- However, the Ministry does not exist anymore and has been replaced by the Ministry of Finance and Development Planning.

Please could you look in this.

**Comment by timgdavies** [comment]
Wiki-procedure has useful context on the registration of Liberian CSOs and NGOs

https://www.wikiprocedure.com/index.php/Liberia_-_Register_a_Civil_society

> Civil societies are Non Profit Organizations (NGOs) / institutions that show interests and will of citizens. They are either individuals or organizations which are independent of the government in a given society. 
>
> The civil society organizations include Community Based Organizations (CBOs), Faith Based Organizations (FBOs), Non Profit Organizations (NPOs), Trade Unions, Indigenous Peoples Movements (IPMs), Foundations among others. 
>
> In Liberia, the Associations Law is mandated with the incorporation of all Civil Society Organizations (CSOs) through the Ministry of Foreign Affairs, which makes the organizations legal entities and the Non Government Organization (NGO) Policy administered by the Ministry of Planning and Economic Affairs is used to control activities of Non Government Organizations (NGOs).
>
> Therefore civil societies should register with the Ministry of Foreign Affairs and the Ministry of Planning and Economic Affairs and thereafter register with the National Civil Society Council of Liberia which coordinates Civil Society Organizations in the country.

Later text suggests that NGO registration (formerly with MPEA) is open to unincorporated and incorporated entities, suggesting that MPEA registration (or whatever succeeds it) is registration of the 'status' (secondary identifiers) whereas MFA registration is legal registration (primary). However, I've not been able to confirm what kind of documents or numbers MFA may assign. 

Additionally: The National Civil Society Council of Liberia (http://ncscliberia.org/) have a website and link to a database (http://csoliberia.org/), but this appears to only have six entries at present, and does not provide identifiers for these. 

From additional communication, I see that YMCA Liberia are checking if they will have a new registration number issued, or will maintain their current number.

In the event they maintain their current registration, then it would seem reasonable for us to create a list entry based on the information below.

If it appears all MPEA numbers will convert into new MFDP assigned identifiers, we may wish to only include a list for this. 

**The name of the list, or the organization that manages the list**

Ministry of Planning and Economic Affairs (Liberia)

**A suggested code for the list [optional]**

LR-MPEA 

**A short description of the list**

The Ministry of Planning and Economic Affairs (Liberia) held responsibility for regulating the activities of Non-Governmental Organisations (NGOs). It issues a "Certificate of Accreditation" to organisations, which should be renewed every three years [1].

[1]: https://www.wikiprocedure.com/index.php/Liberia_-_Register_a_Civil_society

**The country or countries that the list covers**

Liberia

**The legal form or organizations that the list covers**

Charity / NGO

**Any specific sectors that the list covers**

None

**A URL for information on the list, and a URL for looking up identifiers [if available]**

None available. 

**Any information on available open data copies of this list**

None available.

**One or more examples of identifier from this list, and how you found them**

MPEA/NGO/AC#0298. 

Provided by an organisation - found on their registration certificate. 

**How should these identifiers be written out**

Suggested rendering would be: LR-MPEA-NGO-AC-0298  (replacing special characters with -)
