### ISSUE TITLE
PROPOSAL: New List [Pakistan - Societies Registration Act 1860]

### ISSUE THREAD

**Issue by AudreyIATI** [org-id/register#441]
## Proposal

**What open data standard are you working with? (e.g. 'OCDS', '360Giving', 'BODS' etc.)**

IATI

**The name of the list (or the organization that manages the list)**

Societies Registration Act 1860 (Pakistan)

**A suggested code for the list (optional)**

PK-SRA

**A short description of the list**

Organisations in Pakistan registered under the Societies Registration Act, 1860

**The country or countries that the list covers**

Pakistan

**The legal form or organizations that the list covers**

According to Societies Registration Act, 1860 the society may be registered for the grant of charitable assistance, for the promotion of science, literature, the fine arts, for instruction, the diffusion of useful knowledge, diffusion of political education the foundation or maintenance of libraries or reading rooms, public museums and galleries of paintings and other works of art, collection of natural history, mechanical and philosophical inventions, instruments or designs.

**Any specific sectors that the list covers**

**A URL for information on the list, and a URL for looking up identifiers (if available)**

n/a (paper based)

**Any information on available open data copies of this list**

**One or more examples of identifier from this list, and how you found them**

Society Registration Certificate (paper based)

**Comment by kd-ods** [comment]
Hi @AudreyIATI - Looking at this and the related pull request (#440), we're going to need to work out if there is actually a unique, persistent ID given to organisations registered under the act. There has been a related issue in the past: #295.

(Also, I assume that whatever organisation you're trying to find an ID for, it isn't registered [under this list](http://org-id.guide/list/PK-VSWA)?)

Can you have a look at that previous issue (#295) and see if the information you have seen on paper certificates moves things forward?

**Comment by AudreyIATI** [comment]
Hi @kd-ods - thank you for your response.
I can confirm that they are not already registered under the list linked above.

Their original email to the IATI Support Helpdesk stated:

_None of the registration agencies listed for Pakistan on your website apply to us. Since we are registered under the Societies Registration Act 1860, our registration certificate (attached) only specifies the Office of the Registrar, Joint Stock Companies, Lahore, which does not have a website._

I also read through #295  and notice plenty of similarities (but no concrete resolution?) compared to the case in my pull request. 

Happy to send over the registration certificate as Jahnvi did in #295  via email to check for a unique, persistent ID?
Alternatively I can go back to the organisation and request additional information?

Thanks,
Audrey

**Comment by kd-ods** [comment]
> Happy to send over the registration certificate as Jahnvi did in #295 via email to check for a unique, persistent ID?

I'm afraid we don't have the resources to do this level of research and support now, @AudreyIATI. If you can ascertain that there is a unique, stable ID issued by a registrar and it is detailed on the organisation's certificate of registration, then we will be able to add the registrar to org-id. What I understand from #295 is that the Societies Registration Act 1860 (Pakistan) is the law under which the org is registered, and so would be unsuitable for an entry in org-id in any case; the registrars administering the law would be admissible to org-id (if we can establish that orgs are issued unique IDs). (So you may wish to close your current pull request on that basis.)

> Alternatively I can go back to the organisation and request additional information?

Going back to them and asking if they have a [taxpayer number or an exemption certificate](https://github.com/org-id/register/issues/295#issuecomment-467007863) (or are registered for any other reason with state or regional authorities) is a good option.

In the absence of any other usable identifier I think you'll need to look at issuing an XI-IATI identifier.

**Comment by AudreyIATI** [comment]
Hi @kd-ods - thank you for this, I'll update the publisher and let you know.

**Comment by AudreyIATI** [comment]
Hi @kd-ods, finally heard back from the publisher:

- Is there a unique, stable ID issued by a registrar and it is detailed on the organisation's certificate of registration? 
**It is RP/2711/L/S/87/307 and is unique to our organisation.**

- Please ask the HRCP if they have a taxpayer number or an exemption certificate (or are registered with state or regional authorities). 
**Yes, HRCP has a taxpayer registration certificate. Our national tax number is 4174941-3.**

What would you advise?

Thanks,
Audrey

**Comment by kd-ods** [comment]
Hi @AudreyIATI 

It looks to me like the national tax number (NTN) is the one to go for here.

I used this verification service: https://e.fbr.gov.pk/esbn/Verification#:

> Go to Active Taxpayer List (income tax)
> Parameter type: NTN
> Registration number: 4174941
> Verify

And it returned to me the record for the Human Rights Commission of Pakistan.

So it looks the org-id entry to create is PK-NTN. And the entry should give a bit of detail about the makeup of the tax numbers (i.e the digit after the dash is a check number).

**Comment by AudreyIATI** [comment]
Hi Kadie,

Any update on this?
Asking because the publisher followed up.

Thanks,
Audrey

**Comment by kd-ods** [comment]
Hi @AudreyIATI. I realise my last comment wasn't very clear. I think your next steps are to create a PK-NTN (National Tax Number, Pakistan) entry for org-id and to use that for this particular case of the Human Rights Commission of Pakistan.

Is that OK?

**Comment by AudreyIATI** [comment]
Hi Kadie,

Thank you for this - makes perfect sense.
I'll do that using the information I have available and drop a note here,

Thanks,
Audrey

**Comment by kd-ods** [comment]
@AudreyIATI - shall I close https://github.com/org-id/register/pull/440 and delete the AudreyIATI-patch-1 branch on which that work sits? (If you're going to address this proposal by creating PK-NTN, you're probably best starting afresh.)

**Comment by AudreyIATI** [comment]
Hi again @kd-ods,

PR created [here](https://github.com/org-id/register/pull/461)

Thanks,
Audrey

**Comment by AudreyIATI** [comment]
Hi @kd-ods - following up to see if there's any update?

Thanks,
Audrey

**Comment by kd-ods** [comment]
Hi @AudreyIATI  - 

I'll take a look at the PR before the end of the week.

**Comment by AudreyIATI** [comment]
Perfect - thank you!

**Comment by AudreyIATI** [comment]
Thank you for comments @kd-ods - will make changes and revert

**Comment by kd-ods** [comment]
PK-NTN now available at: http://org-id.guide/list/PK-NTN
