### ISSUE TITLE
PROPOSAL: New list NG-TIN code verification

### ISSUE THREAD

**Issue by andreaszenasidi** [org-id/register#442]
## Proposal

I am reaching out to verify that the NG-TIN code is the correct one to use for government agencies e.g. federal and state ministries of health in Nigeria. A few IATI publishers need to use this code as soon as possible. I will prepare and submit the new list to org-id shortly.

**The name of the list (or the organization that manages the list)**
Federal Inland Revenue Services (FIRS)

**A suggested code for the list (optional)**
NG-TIN

**A short description of the list**
The Tax Identification Number is issued to registered companies, individuals and government agencies operating in Nigeria.

**The country or countries that the list covers**
Nigeria

A URL for information on the list, and a URL for looking up identifiers (if available)
https://firs.gov.ng/ (this website doesn't seem to work)
https://apps.firs.gov.ng/tinverification/

**Comment by kd-ods** [comment]
> "NG-TIN code is the correct one to use for government agencies e.g. federal and state ministries of health in Nigeria"

There may well be a better ID to use for government agencies in Nigeria. (Some countries do have coding systems to help identify state agencies and departments.) You'll need to do some digging around to see if some such codelist exists.

In the absence of such a list, falling back to a TIN (if uniquely assigned to an agency) would be ok.

Either way, adding NG-TIN to org-id would be useful.

**Comment by andreaszenasidi** [comment]
@kd-ods thanks for your prompt answer. We are working on finding out if the codes from the national budget could be used for government ministries, we are still waiting to see if state ministries (not only federal level) also have some form of unique code in the budget. But as you said as well, we were thinking to add NG-TIN to org.id since it can be used for other entities as well.
