### ISSUE TITLE
QUESTION: Spain ES-RMC and CIF numbers

### ISSUE THREAD

**Issue by andreaszenasidi** [org-id/register#444]
@kd-ods I am a bit confused whether the código de identificación fiscal (CIF) number of Spanish organisations (an example is [here](http://justicia.gencat.cat/ca/serveis/guia_d_entitats/?idEntitat=107752#)) belongs to the registrar [ES-RMC](http://org-id.guide/list/ES-RMC) or if we need a new org.id entry for CIF numbers.
It seems like organisations consider this CIF number as their unique identifier.

Thanks in advance!

**Comment by kd-ods** [comment]
tbh @andreaszenasidi - that ES-RMC org-id entry is entirely unclear and the data isn't open so I can't check whether CIF is the only identifier listed for orgs. I doubt that it is - there's likely to be company numbers etc. listed too.

If you can find the Spanish tax agency responsible for issuing CIFs (and NIFs and NIEs?) then it would be good to have that in org-id. (And potentially retire the ES-RMC list.)

**Comment by andreaszenasidi** [comment]
@kd-ods  thanks for your fast answer! I did more digging and found that the 'Registradores' is responsible for maintaining the Business Registers (Registros Mercantiles de España). Info from [here](https://e-justice.europa.eu/content_business_registers_in_member_states-106-es-en.do?member=1). 

You are able to search for NIF (pre 2008 called CIF, but apparently the name is still used) [here](https://www.registradores.org/directorio/-/registros/mercantil). In my opinion, this is not the same as the Central Commercial Register (http://org-id.guide/list/ES-RMC). I propose to add this as a new org.id and remove the Central one.

I did run into a problem though when I search for this CIF http://justicia.gencat.cat/ca/serveis/guia_d_entitats/?idEntitat=107752# in the above [website](https://www.registradores.org/directorio/-/registros/mercantil); it does not find it, but for other CIF's e.g. G85960730 it works, so I am unsure if the search works well.

**Comment by andreaszenasidi** [comment]
### **Proposal**
I would like to verify that the ES-REG code is the correct one to use for NGOs in Spain. An IATI publishers need to use this code as soon as possible. I will prepare and submit the new list to org-id shortly.

**The name of the list (or the organization that manages the list)**
Registros Mercantiles de España
I could not find any abbreviation for them, thus I used _REG_ in the code.

**A suggested code for the list** 
ES-REG

**A short description of the list**
'Registradores' (Registrars) are responsible for maintaining the following registers:
1. Land and Property Registers ('Registros de la Propiedad de Bienes Inmuebles', generically known as the Land Registers (“Registros de la Propiedad”).
2. Movable Property Registers ('Registros de la Propiedad de Bienes Muebles').
3. Business Registers ('Registros Mercantiles'). These are CIF/NIF numbers.
4. Register of General Contract Conditions ('Registro de Condiciones Generales de la Contratación')
Source: https://e-justice.europa.eu/content_business_registers_in_member_states-106-es-en.do?member=1 

**The country or countries that the list covers**
Spain

**A URL for information on the list, and a URL for looking up identifiers**
https://sede.registradores.org/site/invitado/mercantil/busqueda#noback

**Comment by kd-ods** [comment]
@andreaszenasidi, it looks to me like the Spanish tax agency, the Agencia Tributaria, is responsible for allocating NIFs:

"Inside the scope of the responsibilities of the State, it falls to the Tax Agency to allocate a Tax ID Number to the legal persons and organisations that request one"

From [this page](https://www.agenciatributaria.es/AEAT.internet/en_gb/Inicio/La_Agencia_Tributaria/Campanas/Censos__NIF_y_domicilio_fiscal/Empresas_y_profesionales__Declaracion_censal__Modelos_036_y_037/Informacion/NIF_de_personas_juridicas_y_entidades.shtml) which details the composition of NIFs.

I therefore think that an ES-NIF list might be the best option even though it looks like there is no public lookup for NIFs.
