### ISSUE TITLE
PROPOSAL: New List [Liberia Ministry of Health]

### ISSUE THREAD

**Issue by AudreyIATI** [org-id/register#446]
## Proposal

**What open data standard are you working with? (e.g. 'OCDS', '360Giving', 'BODS' etc.)**
IATI

**The name of the list (or the organization that manages the list)**
Ministry of Health Liberia

**A suggested code for the list (optional)**
LR-GOV-310

**A short description of the list**
The organisation code in the Liberia government Chart of Accounts for the Ministry of Health is 310. This is the code used in the national budget. The organisation codes are readily available in these documents and don't change from year to year, unless a Ministry is newly created or ceases to exist. 

**The country or countries that the list covers**
Liberia

**The legal form or organizations that the list covers**
Government Ministry

**Any specific sectors that the list covers**
Health

**A URL for information on the list, and a URL for looking up identifiers (if available)**
https://mfdp.gov.lr/index.php/docs/the-national-budget 
http://moh.gov.lr/ 

**Any information on available open data copies of this list**
n/a

**One or more examples of identifier from this list, and how you found them**
List of Govt Ministry codes, found in the National  Budget Doc
https://mfdp.gov.lr/index.php/docs/the-national-budget

**Comment by kd-ods** [comment]
Hi @AudreyIATI - these do look like they're potentially stable codes. I've done some additional online searching and I can't find out much more. It would be nice if Liberia's Ministry of Finance and Development (which I understand is responsible for govt budget reporting) had an independent and public listing of the 'spending entity' codes. I've also seen them referred to as 'ministry codes'. 

This might be worth an email to the Ministry, asking if such a list might be published online.

**Comment by AudreyIATI** [comment]
Hi @kd-ods - thanks for the update. I'll go back to the publisher to ask for more info and let you know how I get on.

**Comment by AudreyIATI** [comment]
Hi @kd-ods - hypothetically, would it be possible to register the MOH under the suggested code with the current information supplied? I understand from SightSavers (who are working with the MOH) that public listings may not be available.

**Comment by kd-ods** [comment]
Yes, I think we could add this list, as LR-GOV, @AudreyIATI. Although we would need to be clear which arm of govt maintains the list (Liberia's Ministry of Finance and Development, as far as I understand it).

(In the initial proposal, the fields should be:

**The name of the list (or the organization that manages the list)**
Liberia's Ministry of Finance and Development

**A suggested code for the list (optional)**
LR-GOV

**Any specific sectors that the list covers**
All govt departments
)

**Comment by AudreyIATI** [comment]
Hi @kd-ods - since my last message we've encountered some "red tape" surrounding this issue. Until we've reached consensus on how to manage this type of publisher, there's no need to progress this request.
I'll close it now, but resurrect it later if need be.
Thanks for your help!
Audrey
