### ISSUE TITLE
PROPOSAL: New South African public university registrar

### ISSUE THREAD

**Issue by andreaszenasidi** [org-id/register#448]
I am trying to find a suitable registrar for a South African public University. They are not registered as a nonprofit, thus [ZA-NPO](http://org-id.guide/list/ZA-NPO) can't be used for them.

I did some research on other options, I found that the Department of Higher Education and Training (DHET) does  the registration and accreditation status of universities, however, they do not issue a registration number for public universities only for private ones. Here is an extract from an accreditation letter sent by a university:
**In terms of the Higher Education Act (Act 101 of 1997) and the SU Statute (Government Notice No. 42636 Notice  1062  of  16  August  2019)  Stellenbosch  University  is  a  public  higher  education  institution.  Please  note that, in terms of the Act, only private providers are given registration numbers.**

Looking at other universities accreditation statuses as well seems like the government notice number and date is what is considered unique for a university. Cape Town uni has: **Government Notice No. 1199 of 20 September 2002.**
http://www.rci.uct.ac.za/rcips/contracts/admin_info

Could I use this number as a registration number? For example for Stellenbosch  University we could use _42636-1062-16082019_

Alternatively, they have an Income Tax Number issued by the [South African Revenue Service (SARS)](https://www.sars.gov.za/businesses-and-employers/ ). Ex. 9045478147

Which new registrar would be preferred for universities, DHET or SARS?

**Comment by kd-ods** [comment]
Hi @andreaszenasidi -

In the short term, have you had a look at [XI-GRID and XI-ROR](http://org-id.guide/results?structure=all&coverage=all&sector=education) to find an ID for this public University?

> Which new registrar would be preferred for universities, DHET or SARS?

If **one of them** has a publicly searchable list of IDs, then let's add that one to org-id.

If **neither or both** have a publicly searchable list of IDs, then add SARS (since that has widest coverage). (However if there is any doubt about making Tax Numbers for institutions public, then go down the DHET route.)

**Comment by andreaszenasidi** [comment]
@kd-ods thanks very much for the clarification! I have looked into the XI-GRID, however, if the organisation publishes their data using GRID we won't be able to change their identifier since their activity IDs contain the org id and this ID shouldn't change after publication. Thus, it's preferred to wait until we have the final org.id.

DHET has a [searchable DB](https://www.dhet.gov.za/SitePages/DocRegisters.aspx) (PDF document), however, this is limited to private institutions (tertiary education). There is no DB for public universities or colleges. SARS does not have a publicly searchable list of tax identifiers. 

Considering these limitations and your point about the wider coverage, I will create a new SARS registrar.

**Comment by andreaszenasidi** [comment]
@kd-ods I hope I created the correct registrar, I was not certain if I should create only for the Corporate Tax Identifier (CIT) or SARS as a whole.
