### ISSUE TITLE
PROPOSAL: Superintendencia Nacional de Aduanas y de Administración Tributaria (Perú) - SUNAT

### ISSUE THREAD

**Issue by nativaldezt** [org-id/register#451]
## Proposal

**What open data standard are you working with?**
OCDS

**The name of the list (or the organization that manages the list)**
Superintendencia Nacional de Aduanas y de Administración Tributaria - SUNAT

**A suggested code for the list (optional)**
PE-SUNAT

**A short description of the list**
The SUNAT according to its creation Law No. 24829, is a specialized technical agency, attached to the Ministry of Economy and Finance. Its main purpose is to administer the taxes of the national government and the tax and non-tax concepts entrusted to it by Law or according to the inter-institutional agreements entered into, providing the resources required for fiscal solvency and macroeconomic stability; ensuring the correct application of the regulations governing the matter and combating tax and customs crimes in accordance with its powers.

**The country or countries that the list covers**
Perú

**The legal form or organizations that the list covers**
All organizations that have RUC

**A URL for information on the list, and a URL for looking up identifiers (if available)**
Web site  https://www.sunat.gob.pe/
RUC search https://e-consultaruc.sunat.gob.pe/cl-ti-itmrconsruc/jcrS00Alias

**One or more examples of identifier from this list, and how you found them**
20131380951 - MUNICIPALIDAD METROPOLITANA DE LIMA

**Comment by kd-ods** [comment]
Thanks @nativaldezt - I've assigned this to Matt, who works on the OCDS helpdesk. (And I'm around to advise if nec.)

**Comment by mrshll1001** [comment]
I've submitted a PR for this now.

@nativaldezt, I couldn't find a license on the SUNAT website for the data; if you knew how SUNAT license the information in the list that'd be great! But fine if not.

**Comment by nativaldezt** [comment]
I don't think they have a license, but if you want I ask them.

**Comment by mrshll1001** [comment]
> I don't think they have a license, but if you want I ask them.

I think that's fine. We can list it as not licensed.
