### ISSUE TITLE
Update FI-PRO

### ISSUE THREAD

**Issue by kd-ods** [org-id/register#454]
**What open data standard are you working with? (e.g. 'OCDS', '360Giving', 'BODS' etc.)**

OCDS - see https://github.com/open-contracting/standard/issues/987

**Updates and corrections**
The existing org-id entry [FI-PRO](http://org-id.guide/list/FI-PRO) seems to map to the Y-tunnus Identifier Scheme (code 0037) in iso 6523, only this is not immediately apparent. That's because the org-id entry is centred on the ultimate agency that is [responsible](https://en.wikipedia.org/wiki/Finnish_Trade_Register) for the identifier scheme, rather than the scheme itself.

I wouldn't necessarily recommend a change to the org-id scheme identifier (FI-PRO), but the current details should be checked and updated, to make clear that the ord-id entry relates to the y-tunnus identifier.

**Comment by duncandewhurst** [comment]
> The existing org-id entry [FI-PRO](http://org-id.guide/list/FI-PRO) seems to map to the Y-tunnus Identifier Scheme (code 0037) in iso 6523, only this is not immediately apparent.

Noting that code `0037` in ISO6523 is actually the LY-tunnus, not the Y-tunnus. There is a new code in ISO6523 for the Y-tunnus: `0212`.

According to [Wikipedia](https://fi.wikipedia.org/wiki/Y-tunnus), the Y-tunnus number replaced the LY-tunnus number in 2001. That page also mentions that existing companies were assigned a Y-tunnus number matched their old LY-tunnus number, so I don't think we need to add a separate org-id entry for LY-tunnus.
