### ISSUE TITLE
PROPOSAL: New list KH-NNGO code verification

### ISSUE THREAD

**Issue by andreaszenasidi** [org-id/register#470]
**Proposal**

I am reaching out to verify that the KH-NNGO code is the correct one to use for national NGOs in Cambodia. 
A publisher needs to use this code as soon as possible. I will prepare and submit the new list to org-id shortly.

**The name of the list (or the organization that manages the list)**
Minostry of Interior National NGO Registrar

**A suggested code for the list (optional)**
KH-NNGO

**A short description of the list**
Local NGOs are required to be registered at the Ministry of Interior.

**The country or countries that the list covers**
Cambodia

**A URL for information on the list, and a URL for looking up identifiers (if available)**
https://cambodiacounsel.com/ngo-registration/
https://www.licadho-cambodia.org/delusion2011/laws/NGOAssociationLaw-3rdDraft-English.pdf

**Example of a translated certificate**
![image](https://user-images.githubusercontent.com/74558657/141319064-b18460e5-4848-49e9-9dad-061273950b86.png)

**Comment by kd-ods** [comment]
@andreaszenasidi - is a registration number issued to the NGO which can then act as an identifier?

**Comment by andreaszenasidi** [comment]
@kd-ods the number in the left top corner is the nr. In the example, it's 502.

**Comment by kd-ods** [comment]
Great. Thanks for confirming, @andreaszenasidi.

Yes - go ahead and use KH-NNGO.
