### ISSUE TITLE
PROPOSAL: New list PA-PRP code verification

### ISSUE THREAD

**Issue by andreaszenasidi** [org-id/register#476]
**Proposal**

I am reaching out to verify that the PA-PRP code is the correct one to use for foundations and corporations in Panama.
A publisher needs to use this code as soon as possible. I will prepare and submit the new list to org-id shortly.

**The name of the list (or the organization that manages the list)**
Public Registry of Panama (Registro Público de Panamá)

**A suggested code for the list (optional)**
PA-PRP

**A short description of the list**
The Public Registry of Panama is a dependency of the Ministry of Government and Justice and it's the sole property registry of Panama [1]. Corporations and Foundations are required to be registered in the Public Registry of Panama.
[1]. https://registro-publico.gob.pa/index.php?option=com_content&view=article&id=147&Itemid=501

**The country or countries that the list covers**
Panama

**A URL for information on the list, and a URL for looking up identifiers (if available)**
https://www.panadata.net/en/organizaciones

**Registration number**
Is the ID from the Panadata website. E.g. 5789 for Fundacion Avina
https://www.panadata.net/en/organizaciones/2432535
I have seen other documents from Fundacion Avina in which they were referring to this 5789 as their Company registration number (Ficha)

**Comment by kd-ods** [comment]
@andreaszenasidi - PA-PRP is the right code for this list.

Is the panadata.net site a state-run portal for public information? If not and there is public access via a state agency, then we should use that instead. (Failing that, we can keep the panadata links, I think. As long as we acknowledge that it's a third-party site and not state-run.) Does that sound ok?

**Comment by andreaszenasidi** [comment]
@kd-ods thanks for checking. Panadata.net doesn't seem to be a state-sun portal, but the state-run one requires registration with passport number etc. https://www.rp.gob.pa/
