### ISSUE TITLE
PROPOSAL: New list EG-CRE code verification

### ISSUE THREAD

**Issue by andreaszenasidi** [org-id/register#482]
**Proposal**
I am reaching out to verify that the EG-CRE code is the correct one to use for a joint-stock company in Egypt. The publisher has a mid-January deadline to publish to IATI, thus would be important to know if the proposed code is fine to use so they can start using the identifier.

**The name of the list (or the organization that manages the list)**
Commercial Registry Egypt

**A suggested code for the list (optional)**
EG-CRE

**A short description of the list**
The Ministry of Supply and Internal Trade, Internal Trade Development Authority is in charge of registering limited liability companies, joint stocks, foreign branches and representative offices and maintaining the Commercial Registry in Egypt.
http://itda.gov.eg/

**The country or countries that the list covers**
Egypt

**A URL for information on the list, and a URL for looking up identifiers (if available)**
http://itda.gov.eg/

**Registration number**
117508

**Comment by kd-ods** [comment]
@andreaszenasidi - Using 'EG-CRE' is only advisable if this style of company registration number is the ONLY such registration number that the Commercial Registry of Egypt issues. (For example, if they also issue VAT numbers, or they issue different identifiers for different types of entity, then we need to know that.) 

I've done some searching around but I can find what the definitive name for the company number is. If you could find that, then we could append the initials to the list name code. Maybe if you have a company registration certificate, you can work that out.

Also, it looks like Egyptian citizens can [request](http://www.itda.gov.eg/cra/AvailableServices.aspx) extracts from the register. But there's no way of check company numbers without registering.

**Comment by andreaszenasidi** [comment]
@kd-ods I have seen an extract from the commercial registry and the number is just called Registration Number. I also saw a Tax Card of the same company and the tax number and card are issued by the Ministry of Finance, Egyptian Tax Authority. It doesn't seem to be part of the Commercial Registry.

I tried to find out more from the [website](http://itda.gov.eg/), but based on the information I read they are issuing only this number. Maybe, **EG-CR** would be a more suitable name for the registrar.

**Comment by andreaszenasidi** [comment]
@kd-ods I was trying to create EG-CR entry, however seems like one exists already in the source code, but is not visible in [org.id](http://org-id.guide/results?structure=all&coverage=EG&sector=all).
https://github.com/org-id/register/blob/master/lists/eg/eg-cr.json

Could you please advise how to proceed?

**Comment by kd-ods** [comment]
Hi @andreaszenasidi -

It looks like 'confirmed' is null in that legacy entry; so it was never entered onto org-id.guide. That means we can go ahead and overwrite it. 

Practically, that means creating the new JSON entry as you normally would on the [editing app](https://org-id-register.netlify.app/) BUT not using the 'Edit on GitHub' button. Instead, you can:

- copy your JSON data from the app
- on the existing [eg-cr.json page](https://github.com/org-id/register/blob/main/lists/eg/) use the pencil icon ('Edit this file') to go into edit mode.
- delete the old data and paste in your new JSON data
- create a new branch for the commit as you normal would and open a PR. 

Email me, @andreaszenasidi, if you'd like me to talk you through that on a call.

**Comment by andreaszenasidi** [comment]
@kd-ods thanks for the clarification. I followed your instructions and submitted a new PR.

**Comment by andreaszenasidi** [comment]
Hi @kd-ods, do you have any updates on this new list, please? The publisher is blocked from registering until this is not approved. Many thanks.
