### ISSUE TITLE
PROPOSAL: New list LR-MFDP code verification

### ISSUE THREAD

**Issue by andreaszenasidi** [org-id/register#483]
**Proposal**
I am reaching out to verify that the LB-MFDP code is the correct one to use for CSOs and NGOs in Liberia. There was a previous [github issue](https://github.com/org-id/register/issues/44) opened about this but it was closed. The NGO that is trying to use the registrar clarified that their registration number does not change, even though they need to renew their certificate of accreditation yearly. 

**The name of the list (or the organization that manages the list)**
Ministry of Finance and Development Planning

**A suggested code for the list (optional)**
LB-MFDP

**A short description of the list**
The Ministry of Finance and Development Planning keeps a registry of all registered and accredited NGOs in Liberia. 
https://www.mfdp.gov.lr/index.php/budget-planning/assistant-min-regional-sectoral/ngo-unit

**The country or countries that the list covers**
Liberia

**A URL for information on the list, and a URL for looking up identifiers (if available)**
https://www.mfdp.gov.lr/

**Registration number**
0961

**Comment by kd-ods** [comment]
Hi @andreaszenasidi. The country code for Liberia should be LR. The MFDP might also maintain other registration lists, so I'd suggest:

LR-MFDPNGO
