### ISSUE TITLE
GB-GOR has link that 404's

### ISSUE THREAD

**Issue by odscjames** [org-id/register#498]
http://org-id.guide/list/GB-GOR -> https://government-organisation.register.gov.uk/records

**Comment by siwhitehouse** [comment]
The GB-GOR register was retired.

> "[GOV.UK Registers was a service provided by the Government Digital Service which retired on March 15 2021](https://www.data.gov.uk/dataset/a8f488fd-eaea-4176-92b0-6d0437b4d121/historical-gov-uk-registers)."

The register has been archived

https://github.com/openregister/registers-data-archive

and so I propose that we amend the org-id listing to reflect this, while still making it visible to people who wish to reference it and/or use codes from the list.
