### ISSUE TITLE
PROPOSAL: MX-CMX_CSR - Current Supplier Registry of the Mexico City

### ISSUE THREAD

**Issue by Ravf95** [org-id/register#507]
## Proposal

**The name of the list (or the organization that manages the list)**
Padrón de proveedores vigente de la Ciudad de México - Current supplier registry (Mexico City) managed by the Secretaría de Administración y Finanzas (SAF) of the city.

**A suggested code for the list (optional)**
MX-CMX_CSR

**A short description of the list**
Dataset that contains the legal entities that are currently registered in the Registry of Suppliers of the Public Administration of Mexico City.

**The country or countries that the list covers**
Mexico City, Mexico

**The legal form or organizations that the list covers**
All registered suppliers from Mexico City

**A URL for information on the list, and a URL for looking up identifiers (if available)**
https://datos.cdmx.gob.mx/dataset/tabla-padron-de-proveedores-vigente-sheet1

**Any information on available open data copies of this list**
https://datos.cdmx.gob.mx/dataset/tabla-padron-de-proveedores-vigente-sheet1

**One or more examples of identifier from this list, and how you found them**
|RFC|Razon_Social|Tipo_Persona|
| ------------- | ------------- |------------- |
|EPT050527UQ6|EDIFICACIONES Y PROYECTOS TORRES S.A. DE C.V.|MORAL|
|SID0901299G2|SNAP IN DATA, S.A. DE C.V.|MORAL|

**Additional information** 
* Each entity has a valid RFC code (related to MX-RFC)
* This is for OCDS data publication (México ADIP)

**Comment by kd-ods** [comment]
@Ravf95 - If the organisations in this dataset are identified using the [MX-RFC list](http://org-id.guide/list/MX-RFC], then there is no need to add this as a source of identifiers. As far as I can understand.

**Comment by dramirezc511** [comment]
In MX-RFC list are all people who pays taxes (enterprises and citizens), but the list we would like to register is all potential suppliers admitted by Mexico City government (those who fulfill number of requirements to participate in public procurements)

**Comment by kd-ods** [comment]
@dramirezc511 - it's great that RFC identifiers are being used in this data. So - as I understand it - this is not a source of **new** identifiers that should be added to org-id.guide.

(cc @mrshll1001 in case I'm missing some OCDS context here.)

**Comment by Ravf95** [comment]
@dramirezc511 I close this issue, you can use the existing schema "MX-RFC" and then mark those suppliers that are registered in the registry using the [organization classification](https://extensions.open-contracting.org/es/extensions/organizationClassification/1.1/) extension with a local schema like a "CDMX_PADRON_PROVEEDORES", please feel free to reopen this issue if the recommendation isn't clear or if I'm missing something

**Comment by dramirezc511** [comment]
ok perfect, thank you @Ravf95 , we will do it in that way
