### ISSUE TITLE
Question: Namibia Minisry of Finance, Inland Revenue registration number

### ISSUE THREAD

**Issue by titiolukole** [org-id/register#512]
![image (1)](https://user-images.githubusercontent.com/102729339/169255673-19243542-3dbb-4763-bb7c-6472be16494b.png)
![image](https://user-images.githubusercontent.com/102729339/169254913-ae19963c-7709-4d08-b904-cfd869612639.png)

Hi Kadie, please see images attached. Could we use this number as a registration nr? 

Thanks

**Comment by kd-ods** [comment]
Hello @titiolukole -

Are you looking for an identification number for inclusion in IATI data? If so, I recommend you contact the [IATI Helpdesk](https://iatistandard.org/en/guidance/get-support/).

(On the matter of ID numbers in this income tax filing. I'm not sure what country this is from. I also noticed that the hand-written file ID number is very similar but not identical to the reference number in 'Your ref' at the top. That raises some questions about the reliability of this ID number as a unique identifier.)

**Comment by kd-ods** [comment]
@titiolukole - I think it's your or the IATI helpdesk's call on whether or not 4322-224-011 is a reliable enough reference for this organisation. Regardless, you'll need to know whether such references are unique only at the regional office level, or whether no other organisation can be issued that reference by by other regional offices too. Then you can enter Namibia's Inland Revenue agency (or the Windhoek Regional Office) to org-id.

**Comment by kd-ods** [comment]
resolved with https://github.com/org-id/register/pull/519
