### ISSUE TITLE
PROPOSAL: add a new list for Luxembourg

### ISSUE THREAD

**Issue by cooperationlu** [org-id/register#513]
Hi,

I work for the LU MFA and I want to propose to include a list on org-id.guide for Luxembourg.
 
**What open data standard are you working with? (e.g. 'OCDS', '360Giving', 'BODS' etc.)**
We will soon work with IATI and we need identifiers for our NGOs based in Luxembourg.

**The name of the list (or the organization that manages the list)**
 Luxembourg Trade and Companies Register (Registre de commerce et des sociétés – RCS)

**A suggested code for the list **
LU-RCS

**A short description of the list**
The Luxembourg Trade and Companies Register (Registre de commerce et des sociétés – RCS) is a public register and can be freely accessed. It contains information about traders and companies which, by law, must be disclosed and published. This information is published on the RESA publication platform (https://www.lbr.lu/mjrcs-resa/). The RCS is managed by the Luxembourg Business Registers (LBR) (https://www.lbr.lu/).

The information that is published serves to identify the trader or company, and includes particulars such as a company's articles of association, its rules of procedure, the liability of its directors and officers, and the company accounts.

The information that the trader/company will be required to disclose for publication depends on the legal form of the business, its size and its sector of activity.

All companies that are newly incorporated in Luxembourg must be registered with the RCS, and their articles of association must be filed with the latter in full or in extract form depending of the legal form of the business.

Subsequent amendments to published information must also be published.

The LBR ensures interoperability between the Luxembourg RCS and the business registers of other EU member states through the Business Registers Interconnection System.

**The country or countries that the list covers**
Luxembourg

**The legal form or organizations that the list covers**
see description

**Any specific sectors that the list covers**
see description

**A URL for information on the list, and a URL for looking up identifiers (if available)**
see description

Kind regards,
Sonja Closener
Ministry of Foreign and European Affairs
Luxembourg

**Comment by kd-ods** [comment]
Thank you @cooperationlu. The [IATI Helpdesk](https://iatistandard.org/en/guidance/get-support/) will be able to review this proposal and create a pull request. @titiolukole may be able to take this forward.

**Comment by kd-ods** [comment]
Closed by https://github.com/org-id/register/pull/517

See: http://org-id.guide/list/LU-RCS
