### ISSUE TITLE
PROPOSAL: Yemen Ministry of Industry and Trade

### ISSUE THREAD

**Issue by odscrachel** [org-id/register#556]
## Proposal

**What open data standard are you working with? (e.g. 'OCDS', '360Giving', 'BODS' etc.)**

IATI

**The name of the list (or the organization that manages the list)**

Yemen Ministry of Industry and Trade 

**A suggested code for the list (optional)**

YE-CR - The CR in the identifier stands for commercial registry.

**A short description of the list**

The Yemen Ministry of Industry and Trade manages the commercial registry of trade names for corporations and sole traders. https://moit-ye.com/ 

**The country or countries that the list covers**

Republic of Yemen

**The legal form or organizations that the list covers**

Sole traders and corporations

**Any specific sectors that the list covers**

Private sector 

**A URL for information on the list, and a URL for looking up identifiers (if available)**

https://moit.gov.ye/tn-searc/index.php

**Comment by odscrachel** [comment]
I'll prepare a PR

**Comment by kd-ods** [comment]
@odscrachel - it looks like there's already a stub file (unpublished) for this registry: https://github.com/org-id/register/blob/main/lists/ye/ye-cr.json (from years ago). So please, go ahead and update it. (You can copy and paste the old JSON into the [datatig form](https://org-id-register.netlify.app/type/lists/newweb/) using the JSON button at the top. Then edit the info using the form. Ping me if you need to.)

**Comment by kd-ods** [comment]
^ Or you can ignore me and just overwrite it! I'm sure the old one is very out of date.

**Comment by odscrachel** [comment]
@kd-ods could you update my permissions, I don't currently have access to create the PR. Thanks

**Comment by kd-ods** [comment]
Updated list now live: http://org-id.guide/list/YE-CR
