### ISSUE TITLE
Inclusion of spanish 'Registro de Fundaciones' on the IATI-list of Registries

### ISSUE THREAD

**Issue by olehjo** [org-id/register#558]
Proposal

We are using the IATI-standards list of registries to validate the unique org_id's we publish for receiving partners in our own IATI-activity_files

The Spanish Ministry of Justice maintains a list that serves as a registry for Foundations, in Spain: Registro de Fundaciones

This registry is proposed added to the list, with the code 'ES-RdF'

The list covers foundations based in Spain

The english version of their webside seems to be out of order, but in Spanish, the registry present itself https://www.mjusticia.gob.es/ca/ciudadania/registros/fundaciones-competencia/informacion-general/registro-fundaciones

**Comment by kd-ods** [comment]
@stevieflow - assigning this issue to you. Please let me know if/when you need my involvement.

**Comment by siwhitehouse** [comment]
Thanks to @olehjo for raising this issue

I've taken a look at the registration of foundations on the Ministry of Justice site. 

There is a [search function](https://fundosbuscador.mjusticia.gob.es/fundosbuscador/cargaBuscador.action?lang=es_es) 

Here is an [example result for Safeguard Defenders](https://fundosbuscador.mjusticia.gob.es/fundosbuscador/DetalleFundacion.action?idFundacion=18223&index=1&lang=es_ES) 

There is what looks like [a full download of the foundations database](https://www.mjusticia.gob.es/es/ciudadania/registros/fundaciones-competencia/datos-abiertos) as well. Data is in XML format. There are over 5000 registrations 

Identifiers appear to be persistent and unique. Using the example of Safeguard Defenders there are three identifiers in the data, this is consistent across the whole of the downloaded dataset

```
<Fundacion idfundacion="18223">
```
Probably an internal database reference being published. They look to be incremental starting from various points (10001, 4004, 5002)
```
<NumRegistro>2250JUS</NumRegistro>
```
This looks like it is the identifier issued by the MoJ when the foundation registers. The pattern is three or four digits followed by a three-letter code. I've not found any duplicates, but I haven't searched extensively. Examples of the three-letter code include: 'JUS', 'EDU', 'ECO' suggesting a category/sector in which the foundation operates.

```
<NIFFundacion>G88426192</NIFFundacion>
```
Número de Identificación Fiscal is one of the tax id numbers in Spain.

I'll create a pull request for <NumRegistro> and link it to this issue.

**Comment by stevieflow** [comment]
Great, thanks @siwhitehouse

**Comment by siwhitehouse** [comment]
@olehjo PR #561 has been created to update the entry for the Ministry of Justice in Spain, which covers foundations. We'll keep this issue open until the PR is merged, following the review process.
