### ISSUE TITLE
UPDATE

### ISSUE THREAD

**Issue by jodear** [org-id/register#562]
## NOTE

As of 18th Dec 2019, we (Open Data Service Co-operative) are not currently adding new, unsolicited entries to org-id while we focus our efforts on improving the service. Some open data standards have made arrangements to add fully researched org-id entries. Requests from those organisations will be dealt with under those arrangements; please make sure you mention the open data standard related to your request or proposal (e.g. 'OCDS', '360Giving', 'BODS' etc.). See the root README.md for more information. 

## Proposal

**What open data standard are you working with? (e.g. 'OCDS', '360Giving', 'BODS' etc.)**
We, ADB(Asian Development Bank), are working with the IATI organization to submit funding data for transparency.

**The name of the list (or the organization that manages the list)**
It is just a partial list but the ones suggested for adding mostly came from SEC of the Philippines.

**A suggested code for the list (optional)**

**A short description of the list**
These are some of the Philippine participating organizations in our IATI data that need an org-id for IATI's requirements.

**The country or countries that the list covers**
The Philippines.

**The legal form or organizations that the list covers**
These are Philippine organizations that are recipients of project funding from ADB (Asian Development Bank)

**Any specific sectors that the list covers**
From different sectors.

**A URL for information on the list, and a URL for looking up identifiers (if available)**
https://checkwithsec.sec.gov.ph/
https://www.dof.gov.ph/advocacies/mdfo/
https://www.energy.com.ph/
https://icrs.gcg.gov.ph/profiles/sbc/

**Any information on available open data copies of this list**
None, except from the IATI participating-org database.

**One or more examples of identifier from this list, and how you found them**
AP Renewables, Inc. = CS200715979 - found by searching PH SEC webpage https://checkwithsec.sec.gov.ph/

Attached file - list of organizations to be added in org-id:
[IATI participating-org with no org-ids.xlsx](https://github.com/org-id/register/files/13959062/IATI.participating-org.with.no.org-ids.xlsx)

**Comment by kd-ods** [comment]
Hi @jodear - there is already an org-id entry for the Philippines SEC: http://org-id.guide/list/PH-SEC 

I've assigned this issue to @siwhitehouse on the IATI support desk, in case - on review -  there are other lists that need to be added.

**Comment by jodear** [comment]
Thanks for the quick reply!

So that's how you use that PH-SEC thing - just search the SEC id from the
PH SEC website (https://checkwithsec.sec.gov.ph/) and use it. I tried to
download the list from your PH-SEC page (https://org-id.guide/list/PH-SEC)
but did not get anything, so I thought I still need to ask you to add them.

How about the PH-COA identifiers? I have a couple of PH organizations that
can't be found in the list.  How can I add them?
🙂
Edmund
IT Consultant / UNEP-BCH Regional Adviser / Mentor
Email: ***@***.***
Web: http://baytechph.com <http://revillaconsulting.com>
Mobile: +63 917 838 7195
FB Msgr: edmund.revilla

**Comment by siwhitehouse** [comment]
Thanks @kd-ods - I think that we can update the https://org-id.guide/list/PH-SEC list to include a link to the search that @jodear references. We didn't find that previously.

@jodear the PH-COA identifiers have been included because they were listed on the Unified Accounts Code Structure page on the Phillipines government website. If the PH organisations don't appear on there then we have no way of referencing them, unfortunately. I'd recommend checking with the organisations themselves if possible.

**Comment by kd-ods** [comment]
The updated info is now available on the SEC page: http://org-id.guide/list/PH-SEC

@siwhitehouse - I'll leave you to close this issue once everything is resolved.

**Comment by jodear** [comment]
Great! Thanks!

**Comment by siwhitehouse** [comment]
Thanks for closing this @jodear

**Comment by markbrough** [comment]
Hi @jodear -- I'm maintaining the Gov ID Finder site, which displays a list of codes on the UASC codelist for the Philippines, to make the PH-COA codelist more accessible:
https://gov-id-finder.codeforiati.org/countries/PH

If you have an updated source for COA codes for the Philippines, please feel free to share (preferably as a Pull Request!)
https://github.com/codeforiati/gov-id-finder-data
