### ISSUE TITLE
Proposal: Church of England Church Codes

### ISSUE THREAD

**Issue by KDuerden** [org-id/register#564]
## Proposal

**What open data standard are you working with? (e.g. 'OCDS', '360Giving', 'BODS' etc.)**

360Giving

**The name of the list (or the organization that manages the list)**

Church of England

**A suggested code for the list (optional)**

GB-COE

**A short description of the list**

Church Codes are a unique identification number supplied to each church building by the Church of England Central Services, which is part of the administrative bodies of the National Church Institutions that work together to support the mission and ministries of the Church of England. This code provides a unique number for the property assets of the Church of England.

Church codes can be accessed by searching the Church Heritage Record which is a site operated by the Archbishops’ Council. This [website states](https://facultyonline.churchofengland.org/about-the-church-heritage-record):

_… the Church Heritage Record: a digital database of church buildings integrated with a Geographic Information System (GIS), which can be used for planning and development control, but also fulfils an educational and engagement role.
The Church Heritage Record contains over 16,000 entries on church buildings in England, covering a wide variety of topics from architectural history and archaeology, to the surrounding natural environment. The information contained within has been developed and added to through desk-based research and fieldwork reports, as well as through local initiatives and thematic projects._

Church codes also appear on the entries from the [A Church Near You](https://www.achurchnearyou.com/) online search tool but this is not the recommended way to search for church codes due to how the codes are utilised across multiple church systems.

**The country or countries that the list covers**

England (sub-region of United Kingdom) and Wales (16 churches)

**The legal form or organizations that the list covers**

Church of England churches which are ‘excepted’ from charity registration if their income is £100,000 or less. This means they don’t have to register or submit annual returns but otherwise the Charity Commission regulates them just like registered charities.

This means that there are many thousands of churches which it is currently not possible to identify using a charity number. These church codes provide well managed and maintained alternative ways of uniquely identifying churches. However if a church has a charity number, or has been recognised by the HMRC, these codes should be used in preference to the church code. 

**Any specific sectors that the list covers**

Church of England churches

**A URL for information on the list, and a URL for looking up identifiers (if available)**

https://facultyonline.churchofengland.org/churches

**Any information on available open data copies of this list**

There is currently no bulk open data access to the register of church codes.
Church codes appear in published open data of grants awarded to Church of England churches.

**One or more examples of identifier from this list, and how you found them**

The format of church codes is six digits, starting with a number 6. There is a small number of church codes (76) which start with a number 8, which are chapels.

Churches and codes can be found via the map/location search or via the ‘’Find churches by grade, period, size, etc’ advance search interface, by church name: https://facultyonline.churchofengland.org/churches 

For example:

- Ashen: St Augustine Of Canterbury, church code: 608393
[https://facultyonline.churchofengland.org//CHR/ChurchDetails.aspx?id=2545](https://facultyonline.churchofengland.org/CHR/ChurchDetails.aspx?id=2545) 
- Hartpury: St Mary the Virgin, church code: 616142
[https://facultyonline.churchofengland.org//CHR/ChurchDetails.aspx?id=5581](https://facultyonline.churchofengland.org/CHR/ChurchDetails.aspx?id=5581)

Suggested organisation identifier format

- GB-COE-608393
- GB-COE-616142

Examples of 360Giving open grants data published by the Archbishop’s Council using the church codes as an organisation identifier:

- https://grantnav.threesixtygiving.org/org/360G-CCB-608393
- https://grantnav.threesixtygiving.org/org/360G-CCB-616142

**Comment by kd-ods** [comment]
@KDuerden - it looks to me like you're proposing to use these church codes as pseudo-organisation-identifiers in 360Giving data, whereas they are really identifiers for assets owned by the Church of England. Is that right?

(And have you explored other ways of embedding these codes in 360Giving data to meet your use case?)

cc @mrshll1001 here in case he has any insights to share.

**Comment by KDuerden** [comment]
It is true these are not org ID for churches as legal entities.

They are the identifiers issued and used by CoE and others to uniquely identify these assets - and it is these assets which are funded by grantmakers - eg in church conservation, maintenance etc. If you have concerns this could be treated as a XI type.

There are examples of funders using the church codes in their 360Giving data, but without an agreed prefix our tools aren't able to make matches when different funders have funded the same church in our tools.

There are also some funders who will not update their data collection/publishing pipelines to use these codes until they have been officially adopted for use in 360Giving data.

**Comment by mrshll1001** [comment]
If I'm following correctly, then what we're discussing here is whether it's acceptable to treat these identifiers of Church buildings as proxies for the actual organisations which are receiving funding, in cases where there is no viable alternative identifier?

In this sense, I'd have a concern about giving it a GB code but I do think that org-id should have it in the register; having something as a close proxy for an organisation for cases such as these is undeniably useful and I think excluding it would be a tad puritanical in this case.

At the moment, the org-id docs state that [XI is used for International Lists](https://docs.org-id.guide/en/latest/metadata/), currently used for entries such as DUNS numbers, Wikidata, etc. So I'm not entirely sure that this should be an XI list either although this is not a hill I'll die on. Would it be acceptable to have a ZZ prefix? This is defined as "Publisher Created". We could argue that the publisher is the grantmaker and that they've created the list as a proxy for organisations, and strongly tied it to an existing register of Church assets?

**Comment by neelima-j** [comment]
Can we identify whether the church is an organisation, by asking "Who is the recipient?" 

If the church is the recipient,(as seems to be the case in [the example grant](https://grantnav.threesixtygiving.org/org/360G-CCB-608393) ) does it matter that it is also the asset?

**Comment by KDuerden** [comment]
Thanks for these comments. I raised these questions with our contact at COE, as they described these are IDs for Registration Exempt Church of England charities. 

In response to the question - do you have a view on the church codes as identifiers for these charities vs for the church building which is linked to the charity, I got the following response (edited slightly for clarity). Does this help?

> They are one and the same. The code is a unique identifier for the Church of England represent the church as an entity and everything connected to it. Financial records and congregational-based data are run off these codes.
> 
> The churches are owned locally, held in trust by the incumbent of the church (priest) and the management is run by a committee (Parochial Church Council) Most at a parish level use the parish and church as the same thing; generally, only one church exists within a parish unless multiple parishes merge.
> 
> When a charity is registered with the Charity Commission, it is done at a parish level (unless it is a trust or friends group), as the PCC is run at a parish level as the PCC is the legal entity for the parish. 
> 
> However these parish codes change too often to be used as a fixed entity across multiple funders. The church codes are the identifier used for a church by church identification, which remains consistent and prevents data loss. Parishes merge each month, and each new parish creates a new code, as the merged parish is a new entity within the CoE structure.
> 
> Should a parish have more than one church, grants would need to be awarded to specific churches as individual grants. Where a charity number exists and will cover the parish, and the charity number is used instead.
> 
> With the above, funders give grants to churches, not parishes, but we have that oddity of a church not existing in isolation, and it is attached to a legal structure that begins at the Province (Canterbury and York), to Diocese, to Archdeaconry, to Deanery, to Benefice and then to Parish, all of which are collections of the junior entity. This is a complicated process, which is why the church codes are the most straightforward method when dealing with grants and how funders report this when a charity number or HMRC code does not exist.

**Comment by mrshll1001** [comment]
Thanks for that Katherine, that was phenomenally useful.

We had a quick sense check and conference this afternoon at ODSC about this and I think we're happy to go with your original proposal for the list on the basis that the physical church is tightly bound to the organisation being represented as a recipient in the grant since they are *"one and the same"*.

A quick final sense check if you have the information: at the point where the grant is received, do you know whether the bank account will be an organisation's account representing the church? It sounds like it is, but just doing due diligence in case it differs.

In any case, I'll get to drafting the PR for this list now.

**Comment by KDuerden** [comment]
> A quick final sense check if you have the information: at the point where the grant is received, do you know whether the bank account will be an organisation's account representing the church? It sounds like it is, but just doing due diligence in case it differs.

The short answer is the bank account is associated with the PCC, so it is tied to the church, but it is paid at a parish level, albeit the funds would be restricted to the church.

**Comment by kd-ods** [comment]
Now live here: http://org-id.guide/list/GB-COE

Closing.
