### ISSUE TITLE
UPDATE: BD-ROC register search link

### ISSUE THREAD

**Issue by emmajclegg** [org-id/register#567]
The [BD-ROC page](https://org-id.guide/list/BD-ROC) link in the "Search Options" box is broken and needs updating to https://app.roc.gov.bd/psp/nc_search

**Comment by emmajclegg** [comment]
@kd-ods - could I be added to the org-id repo as a member again? (or have my contributor access checked). I can't assign or label issues like this one at the moment. Thanks

**Comment by kd-ods** [comment]
Changes now live here: http://org-id.guide/list/BD-ROC
