### ISSUE TITLE
ADD: new list SZ- for the Ministry of Commerce, Industry and Trade in Swaziland

### ISSUE THREAD

**Issue by emmajclegg** [org-id/register#570]
## Request
To add a new register to org-id.guide for the Eswatini (Swaziland) MINISTRY OF COMMERCE, INDUSTRY AND TRADE.

A potential IATI publisher has requested this, based on companies and NGOs being registered with the government body in the country. The registration numbers do not change once assigned.
https://iati.zendesk.com/agent/tickets/43865

**Comment by kd-ods** [comment]
List now live here: http://org-id.guide/list/SZ-CIT
