### ISSUE TITLE
Australian registries: deprecating AU-ACNC in favour of AU-ABN

### ISSUE THREAD

**Issue by kd-ods** [org-id/register#585]
Conversation with an officer at the UN International Office for Migration has uncovered that the org reference number used in Australia's charity and non-profit register, the [ACNC registry](https://org-id.guide/list/AU-ACNC), is in fact the business or [ABN number](https://org-id.guide/list/AU-ABN). 

Suggested resolution:

- Set the AU-ACNC record's `deprecated` value to true and edit the description to suggest use of AU-ABN as a prefix.
- Edit the AU-ABN record's description to note that ABNs are used by the ACNC, and that there is also a search facility on their website.

**Comment by kd-ods** [comment]
@emmajclegg - would you have time to sense-check my resolution here? The issue was uncovered via an IATI publisher's query to org-id. I'll send you the details.

**Comment by emmajclegg** [comment]
Hi @kd-ods - sorry for the slight delay getting to this. Based on information on the ACNC website (mainly [this page](https://www.acnc.gov.au/tools/topic-guides/australian-business-number-abn#:~:text=An%20Australian%20Business%20Number%20(ABN,online%20on%20the%20ABR%20website.))), your proposed changes make sense to me.

We don't have many [Australian IATI publishers ](https://iatiregistry.org/publisher/?q=au-&sort=title+asc), but two have registered using AU-ACNC, so I suggest we keep some record of it. This is the search page which could replace the current broken links: https://www.acnc.gov.au/charity/charities. It includes a search by ABN number

Let me know if you want me to review any code of page changes.

**Comment by emmajclegg** [comment]
@kd-ods - please shout if I missed a notification about reviewing a pull request for this (I don't trust my notification set-up to prompt me!). Happy to help
