### ISSUE TITLE
[BIPA-Namibia] Requesting for ORG-ID 

### ISSUE THREAD

**Issue by BIPA-Andy** [org-id/register#586]
## Proposal

**What open data standard are you working with? (e.g. 'OCDS', '360Giving', 'BODS' etc.)**
BODS

**The name of the list (or the organization that manages the list)**
Business and Intellectual Property Authority (BIPA)

**A suggested code for the list (optional)**
Scheme: NA-BIPA
Scheme Name: Business and Intellectual Property Authority (BIPA), Republic of Namibia 

**A short description of the list**
Business and Intellectual Property Authority (BIPA) is a established as a juristic person in terms of section 3 of the BIPA Act, 2016 (Act No.8 of 2016) and is a Public Enterprise as defined in the Public Enterprises Governance Act, 2019 (Act No.1 of 2019) of Republic of Namibia. BIPA is the focal point for the registration of business and industrial property, and is responsible for the administration and protection of business and intellectual property. 

**The country or countries that the list covers**
Republic of Namibia

**The legal form or organizations that the list covers**
Domestic Companies 
Foreign Companies 
Section 21 Company (an association not for gain incorporated under section 21 of the Companies Act)
Close Corporation 
exclude Trusts

**Any specific sectors that the list covers**
All sectors 

**A URL for information on the list, and a URL for looking up identifiers (if available)**
N/A (not for public)

**Any information on available open data copies of this list**
N/A (not for public)

**One or more examples of identifier from this list, and how you found them**
N/A (not for public)
org_no (internal unique identifier) for api 
display business registration number

**Comment by kd-ods** [comment]
Thank you, @BIPA-Andy - I'll work this up into an org-id entry. I'll also include the https://www.bipa.na/search/ link in the entry so that people can look up registration numbers.

**Comment by kd-ods** [comment]
Record here: https://org-id.guide/list/NA-BIPA
