### ISSUE TITLE
PROPOSAL: PermID

### ISSUE THREAD

**Issue by pmackay** [org-id/register#59]
## Proposal

**The name of the list, or the organization that manages the list**

PermID

**A suggested code for the list [optional]**

PID ?

**A short description of the list**

>Every day, professionals deal with disorganized and non-standard data that requires difficult and costly efforts before it can be used. To address these challenges, Thomson Reuters created the Open PermID initiative to provide a means for our clients, partners and the open community to seamlessly navigate our vast data offerings.

>Thomson Reuters Permanent Identifier (PermID) is a machine readable identifier that provides a unique reference for data item. Unlike most identifiers, PermID provides comprehensive identification across a wide variety of entity types including organizations, instruments, funds, issuers and people. PermID never changes and is unambiguous, making it ideal as a reference identifier. Thomson Reuters has been using PermID in the center of our own information model and knowledge graph for over seven years.

**The country or countries that the list covers**

Global

**The legal form or organizations that the list covers**

Companies

**Any specific sectors that the list covers**

**A URL for information on the list, and a URL for looking up identifiers [if available]**

https://permid.org/

Example for John Lewis: https://permid.org/search?num=5&start=1&selected=all&=undefined&q=john%20lewis

**Any information on available open data copies of this list**

Accessible via API and bulk download: https://permid.org/faq#entitiesSupported

**One or more examples of identifier from this list, and how you found them**

https://permid.org/1-4295895026

**Comment by BobHarper1** [comment]
@pmackay Thank you for your suggestion. I've created a PR for the addition of the suggested list from branch XI-PID. Could you check https://github.com/org-id/register/pull/71/files to see if I have missed anything?

**Comment by pmackay** [comment]
Looks good to me :)
