### ISSUE TITLE
Mention the SIREN open data file

### ISSUE THREAD

**Issue by joelgombin** [org-id/register#63]
## Correction

Since January 2017, France has put the SIREN file (which has all companies and their SIRET code) in open data. The raw file are available [here](https://www.data.gouv.fr/fr/datasets/base-sirene-des-entreprises-et-de-leurs-etablissements-siren-siret/), and OpenDataSoft has made a nice interface + API to the base [here](https://public.opendatasoft.com/explore/dataset/sirene/api/). Should this be mentionned in [this page](http://org-id.guide/list/FR-RCS)?

**Comment by timgdavies** [comment]
@BobHarper1 Could you look at getting FR-RCS updated with this change.

**Comment by BobHarper1** [comment]
Thanks @joelgombin, as this is a minor change I've added this directly in https://github.com/org-id/register/commit/46b2d432b6ef569091920ba35fd929b2f3123941
