### ISSUE TITLE
REQUEST: Ministère de l'Intérieur et de la Décentralisation - Mauritania

### ISSUE THREAD

**Issue by amy-silcock** [org-id/register#69]
The organisation Réseau Mauritanien pour l’Education pour Tous (RMEPT) is needing an organisation identifier. The information I currently have is:

They are currently registered with the Ministère de l'Intérieur et de la Décentralisation in Mauritania, with a receipt number #0435

Please could you look in this.

**Comment by BobHarper1** [comment]
Amy, thanks very much for your request. We will carry out some research on this and get back to you in a few days with any follow up actions.

**Comment by BobHarper1** [comment]
Dear Amy,

Having researched your request, we have found that RMEPT is present on the [United Nations Office for the Coordination of Humanitarian Affairs - Financial Tracking Services Identifiers](http://org-id.guide/list/XM-OCHA) list. This is a "fall-back" multi-national list of identifiers for humanitarian organisations who are not on accessible national registers. You can find the [full xml of that list here](http://fts.unocha.org/api/v1/Organization.xml).

We could not find a public list for the Ministère de l'Intérieur et de la Décentralisation. Therefore, I would suggest using the identifier from the UN list `XM-OCHA-15802`.

I trust this answers your enquiry. Please let me know if you need anything else.
