### ISSUE TITLE
PROPOSAL: Registro Federal de Contribuyentes de México

### ISSUE THREAD

**Issue by RegulEsteban** [org-id/register#82]
## Proposal

**The name of the list, or the organization that manages the list**
Registro Federal de Contribuyentes de México 

**A suggested code for the list [optional]**

**A short description of the list**
A URL used for validating identifiers of all mexican legal entities.

**The country or countries that the list covers**
Mexico

**The legal form or organizations that the list covers**
Mexican legal entities

**Any specific sectors that the list covers**

**A URL for information on the list, and a URL for looking up identifiers [if available]**
https://portalsat.plataforma.sat.gob.mx/ConsultaRFC/

**Any information on available open data copies of this list**

**One or more examples of identifier from this list, and how you found them**

**Comment by timgdavies** [comment]
The code MX-RFC is suggested for this list and a pul request to create this is open at #90

**Comment by timgdavies** [comment]
This code is now live.
