### ISSUE TITLE
Ururka Dhalinyarada Gobolada Waqooyi Soomaaliya Ee MMidnimo

### ISSUE THREAD

**Issue by yonors** [org-id/register#87]
## Request

**What type of organization do you want identifiers for?** [ Government / NGO or Charity / Government / other]

**In which countries are the organizations you want identifiers for based?**: 

**Do you have examples of organizations you need identifiers for?**

## Proposal

**The name of the list (or the organization that manages the list)**

**A suggested code for the list (optional)**

**A short description of the list**

**The country or countries that the list covers**

**The legal form or organizations that the list covers**

**Any specific sectors that the list covers**

**A URL for information on the list, and a URL for looking up identifiers (if available)**

**Any information on available open data copies of this list**

**One or more examples of identifier from this list, and how you found them**

**Comment by timgdavies** [comment]
No contents in this request. Closing.
