### ISSUE TITLE
GB-SEED and GB-IRN

### ISSUE THREAD

**Issue by timgdavies** [org-id/register#89]
There is an outstanding pull request against the IATI Organization Identifier list at https://github.com/IATI/IATI-Codelists-NonEmbedded/pull/123 for GB-SEED and GB-IRN (numbers to identify Northern Ireland and Scottish Schools) which was missed in the migration to org-id.guide.

This needs research and inclusion in the lists.

**Comment by BobHarper1** [comment]
Think I know where to find the NI at least

**Comment by timgdavies** [comment]
These codes are now live.
